export
CONFIG_PLATFORM=an8855
#
# AN8855 features
#
ifeq ($(AIR_SUPPORT_ACE),1)
CONFIG_ACE=y
CONFIG_PDMA=y
CONFIG_PDMA_COMMON=y
CONFIG_ETHERNETIF=y
CONFIG_PBUF=y
#CONFIG_GPHY_EN8851 is not set
ifeq ($(AIR_SUPPORT_ACE_ETHERNET_LOG),1)
CONFIG_ACE_CMD_DEBUG=y
endif
endif
CONFIG_NDS32=y
CONFIG_GPIO=y
#CONFIG_GPIO_COMMON is not set
CONFIG_I2C=y
#CONFIG_I2C_COMMON is not set
CONFIG_SLED=y
#CONFIG_SLED_EN8851 is not set
CONFIG_SPI=y
CONFIG_SPI_COMMON=y
CONFIG_TIMER=y
CONFIG_TIMER_COMMON=y
CONFIG_UART=y
CONFIG_UART_COMMON=y
CONFIG_GPHY_AN8855=y
# end of AN8855 features