ifdef CMW_CONFIG
include $(CMW_CONFIG)
else
include $(AIR_MW_DIR)/project/$(PROJECT)/make/config.mk
endif

include $(AIR_MW_SYSTEM)/make/make_prologue.mk

include $(AIR_MW_SYSTEM)/make/make_epilogue.mk

