/* FILE NAME:   hal_coral_reg.h
 * PURPOSE:
 *      Define the chip registers in AIR SDK.
 * NOTES:
 */

#ifndef HAL_CORAL_REG_H
#define HAL_CORAL_REG_H

/* INCLUDE FILE DECLARATIONS
 */

/* NAMING CONSTANT DECLARATIONS
 */

/* EN8851 register map perport offset is 0x200 */
#define CORAL_PORT_CTRL_PORT_OFFSET (0x200)

#define CORAL_VTCR_ADDR         (0x10200600)
#define CORAL_VTCR_VID_OFFT     (0)
#define CORAL_VTCR_VID_LENG     (12)
#define CORAL_VTCR_VID_RELMASK  (0x00000FFF)
#define CORAL_VTCR_VID_MASK     (CORAL_VTCR_VID_RELMASK << CORAL_VTCR_VID_OFFT)
#define CORAL_VTCR_FUNC_OFFT    (12)
#define CORAL_VTCR_FUNC_LENG    (4)
#define CORAL_VTCR_FUNC_RELMASK (0x0000000F)
#define CORAL_VTCR_FUNC_MASK    (CORAL_VTCR_FUNC_RELMASK << CORAL_VTCR_FUNC_OFFT)
#define CORAL_VTCR_BUSY_OFFT    (31)
#define CORAL_VTCR_BUSY_LENG    (1)
#define CORAL_VTCR_BUSY_RELMASK (0x00000001)
#define CORAL_VTCR_BUSY_MASK    (CORAL_VTCR_BUSY_RELMASK << CORAL_VTCR_BUSY_OFFT)

#define CORAL_VLNWDATA0 (0x10200604)
#define CORAL_VLNWDATA1 (0x10200608)
#define CORAL_VLNWDATA2 (0x1020060c)
#define CORAL_VLNWDATA3 (0x10200610)
#define CORAL_VLNWDATA4 (0x10200614)
#define CORAL_VLNRDATA0 (0x10200618)
#define CORAL_VLNRDATA1 (0x1020061c)
#define CORAL_VLNRDATA2 (0x10200620)
#define CORAL_VLNRDATA3 (0x10200624)
#define CORAL_VLNRDATA4 (0x10200628)

/* Field of VLAN*/
#define CORAL_VLN_TYPE_MAC_VOICE_SURVEILLANCE_BASE (0 << 1)
#define CORAL_VLN_TYPE_IPV4_BASE                   (1 << 1)
#define CORAL_VLN_TYPE_SELECTIVE_QINQ_BASE         (2 << 1)

/* Field of Selecive QinQ */
#define CORAL_SELECTIVE_QINQ_VLAN_ENTRY_INVAILD (0x0)
#define CORAL_SELECTIVE_QINQ_VLAN_ENTRY_VAILD   (0x1)
#define CORAL_SELECTIVE_QINQ_ETHERTYPE_OFFSET   (4)
#define CORAL_SELECTIVE_QINQ_CVID_OFFSET        (20)
#define CORAL_SELECTIVE_QINQ_CVID_PRI_OFFSET    (0)
#define CORAL_SELECTIVE_QINQ_UNTAG_PKT_OFFSET   (12)
#define CORAL_SELECTIVE_QINQ_SVID_PRI_OFFSET    (13)
#define CORAL_SELECTIVE_QINQ_SVID_OFFSET        (16)

#define CORAL_SELECTIVE_QINQ_ETHERTYPE_LENG (16)
#define CORAL_SELECTIVE_QINQ_CVID_LENG      (12)
#define CORAL_SELECTIVE_QINQ_CVID_PRI_LENG  (3)
#define CORAL_SELECTIVE_QINQ_SVID_LENG      (12)
#define CORAL_SELECTIVE_QINQ_SVID_PRI_LENG  (3)

#define CORAL_SELECTIVE_QINQ_ETHERTYPE_MSK_OFFSET (8)
#define CORAL_SELECTIVE_QINQ_CVID_MSK_OFFSET      (24)
#define CORAL_SELECTIVE_QINQ_CVID_PRI_MSK_OFFSET  (4)

/* Field of MAC-based VLAN*/
#define CORAL_MAC_BASED_VLAN_ENTRY_INVALID  (0x0)
#define CORAL_MAC_BASED_VLAN_ENTRY_VALID    (0x1)
#define CORAL_MAC_BASED_VLAN_MACADDR_OFFSET (4)
#define CORAL_MAC_BASED_VLAN_MACMASK_OFFSET (20)
#define CORAL_MAC_BASED_VLAN_PRI_OFFSET     (26)
#define CORAL_MAC_BASED_VLAN_CVID_OFFSET    (29)

#define CORAL_MAC_BASED_VLAN_MACMASK_LENG   (6)
#define CORAL_MAC_BASED_VLAN_PRI_LENG       (3)
#define CORAL_MAC_BASED_VLAN_MACADDR_L_LENG (28)
#define CORAL_MAC_BASED_VLAN_MACADDR_H_LENG (20)
#define CORAL_MAC_BASED_VLAN_CVID_LENG      (12)
#define CORAL_MAC_BASED_VLAN_CVID_L_LENG    (3)
#define CORAL_MAC_BASED_VLAN_CVID_H_LENG    (9)

/* Field of IPv4-based VLAN */
#define CORAL_IPV4_BASED_VLAN_ENTRY_INVALID (0)
#define CORAL_IPV4_BASED_VLAN_ENTRY_VALID   (1)
#define CORAL_IPV4_BASED_VLAN_IPADDR_OFFSET (4)
#define CORAL_IPV4_BASED_VLAN_IPMASK_OFFSET (4)
#define CORAL_IPV4_BASED_VLAN_PRI_OFFSET    (4)
#define CORAL_IPV4_BASED_VLAN_CVID_OFFSET   (7)

#define CORAL_IPV4_BASED_VLAN_IPADDR_L_LENG (28)
#define CORAL_IPV4_BASED_VLAN_IPADDR_H_LENG (4)
#define CORAL_IPV4_BASED_VLAN_IPMASK_L_LENG (28)
#define CORAL_IPV4_BASED_VLAN_IPMASK_H_LENG (4)
#define CORAL_IPV4_BASED_VLAN_PRI_LENG      (3)
#define CORAL_IPV4_BASED_VLAN_CVID_LENG     (12)

/* Field of IPv6-based VLAN */
#define CORAL_IPV6_BASED_VLAN_ENTRY_INVALID (0)
#define CORAL_IPV6_BASED_VLAN_ENTRY_VALID   (1)
#define CORAL_IPV6_BASED_VLAN_IPADDR_OFFSET (1)
#define CORAL_IPV6_BASED_VLAN_IPMASK_OFFSET (1)
#define CORAL_IPV6_BASED_VLAN_PRI_OFFSET    (9)
#define CORAL_IPV6_BASED_VLAN_CVID_OFFSET   (12)

#define CORAL_IPV6_BASED_VLAN_IPADDR_LENG (31)
#define CORAL_IPV6_BASED_VLAN_IPMASK_LENG (8)
#define CORAL_IPV6_BASED_VLAN_PRI_LENG    (3)
#define CORAL_IPV6_BASED_VLAN_CVID_LENG   (12)

/* Field of Protocol-based VLAN */
#define CORAL_PROTOCOL_BASED_VLAN_ENTRY_INVALID         (0)
#define CORAL_PROTOCOL_BASED_VLAN_ENTRY_VALID           (1)
#define CORAL_PROTOCOL_BASED_VLAN_FRAME_TYPE_OFFSET     (1)
#define CORAL_PROTOCOL_BASED_VLAN_FRAME_TYPE_ETHERNET   (0)
#define CORAL_PROTOCOL_BASED_VLAN_FRAME_TYPE_RFC1042    (1)
#define CORAL_PROTOCOL_BASED_VLAN_FRAME_TYPE_SNAP_OTHER (2)
#define CORAL_PROTOCOL_BASED_VLAN_FRAME_TYPE_LLC_OTHER  (3)
#define CORAL_PROTOCOL_BASED_VLAN_TYPE_VALUE_L_OFFSET   (4)
#define CORAL_PROTOCOL_BASED_VLAN_TYPE_VALUE_H_OFFSET   (0)
#define CORAL_PROTOCOL_BASED_VLAN_GROUP_ID_OFFSET       (12)

#define CORAL_PROTOCOL_BASED_VLAN_FRAME_TYPE_LENG   (3)
#define CORAL_PROTOCOL_BASED_VLAN_TYPE_VALUE_L_LENG (28)
#define CORAL_PROTOCOL_BASED_VLAN_TYPE_VALUE_H_LENG (12)
#define CORAL_PROTOCOL_BASED_VLAN_GROUP_ID_LENG     (2)

/* ARL Register Base */
#define CORAL_REG_ARL_BASE_ADDRESS (0x10200000)

/* Global Control Base */
/* fields of ARL Global Control */
#define CORAL_AGC                      (CORAL_REG_ARL_BASE_ADDRESS + 0x000C)
#define CORAL_CSR_BCSTRM_EXC_MG        (25)
#define CORAL_CSR_LOCAL_EN_OFFT        (7)
#define CORAL_CSR_LOCAL_EN_LENG        (1)
#define CORAL_AGC_MAC_MOVE_EN_OFFT     (28)
#define CORAL_AGC_MAC_MOVE_EN_LENG     (1)
#define CORAL_AGC_ACLRATE_EXC_MG_OFFT  (26)
#define CORAL_AGC_ACLRATE_EXC_MG_LENG  (1)
#define CORAL_AGC_BCSTRM_EXC_MG_OFFT   (25)
#define CORAL_AGC_BCSTRM_EXC_MG_LENG   (1)
#define CORAL_AGC_MAC_OLD_RPLC_HW_OFFT (23)
#define CORAL_AGC_MAC_OLD_RPLC_HW_LENG (1)
#define CORAL_AGC_COMP_BNUM_OFFT       (8)
#define CORAL_AGC_COMP_BNUM_LENG       (7)

/* fields of MAC Forward Control */
#define CORAL_MFC                 (CORAL_REG_ARL_BASE_ADDRESS + 0x0010)
#define CORAL_CSR_CPU_PORT        (8)
#define CORAL_CSR_CPU_PORT_LENGTH (5)
#define CORAL_CSR_CPU_PORT_EN     (15)

/* fields of IGMP Snooping Control */
#define CORAL_ISC                 (CORAL_REG_ARL_BASE_ADDRESS + 0x0018)
#define CORAL_ISC_CSR_IGMPV3_EN   (1 << 0)
#define CORAL_ISC_CSR_IGMPV3V2_EN (1 << 1)

/* fields of Default Router Port Control */
#define CORAL_DRP (CORAL_REG_ARL_BASE_ADDRESS + 0x00C8)

/* fields of IGMP Query Port Control */
#define CORAL_QRYP (CORAL_REG_ARL_BASE_ADDRESS + 0x00D8)

/* fields of queue setting*/
#define CORAL_PEM1 (CORAL_REG_ARL_BASE_ADDRESS + 0x0048)
#define CORAL_PEM2 (CORAL_REG_ARL_BASE_ADDRESS + 0x004c)
#define CORAL_PEM3 (CORAL_REG_ARL_BASE_ADDRESS + 0x0050)
#define CORAL_PEM4 (CORAL_REG_ARL_BASE_ADDRESS + 0x0054)

#define CORAL_PIM1 (CORAL_REG_ARL_BASE_ADDRESS + 0x0058)
#define CORAL_PIM2 (CORAL_REG_ARL_BASE_ADDRESS + 0x005c)
#define CORAL_PIM3 (CORAL_REG_ARL_BASE_ADDRESS + 0x0060)
#define CORAL_PIM4 (CORAL_REG_ARL_BASE_ADDRESS + 0x0064)
#define CORAL_PIM5 (CORAL_REG_ARL_BASE_ADDRESS + 0x0068)
#define CORAL_PIM6 (CORAL_REG_ARL_BASE_ADDRESS + 0x006c)
#define CORAL_PIM7 (CORAL_REG_ARL_BASE_ADDRESS + 0x0070)

/* fields of AAC*/
#define CORAL_AAC                   (CORAL_REG_ARL_BASE_ADDRESS + 0x00A0)
#define CORAL_AAC_AGE_UNIT_OFFSET   (0)
#define CORAL_AAC_AGE_UNIT_LENGTH   (11)
#define CORAL_AAC_AGE_CNT_OFFSET    (12)
#define CORAL_AAC_AGE_CNT_LENGTH    (9)
#define CORAL_AAC_AUTO_FLUSH_OFFSET (28)
#define CORAL_AAC_AUTO_FLUSH_LENGTH (1)

/* fields of ARL Global Security Control */
#define CORAL_AGSC                      (CORAL_REG_ARL_BASE_ADDRESS + 0x00B0)
#define CORAL_AGSC_GLB_SA_CNT_EN_OFFT   (31)
#define CORAL_AGSC_GLB_SA_CNT_EN_LENGTH (1)

#define CORAL_AGSC_GLB_SA_LRN_CNT_OFFT   (16)
#define CORAL_AGSC_GLB_SA_LRN_CNT_LENGTH (13)

#define CORAL_AGSC_GLB_ZERO_SA_LRN_EN_OFFT   (15)
#define CORAL_AGSC_GLB_ZERO_SA_LRN_EN_LENGTH (1)

#define CORAL_AGSC_GLB_MAC_SA_LRN_OFFT   (0)
#define CORAL_AGSC_GLB_MAC_SA_LRN_LENGTH (13)

/* Register of Forwarding Control Base address */
#define CORAL_UNUF   (CORAL_REG_ARL_BASE_ADDRESS + 0x00B4)
#define CORAL_UNMF   (CORAL_REG_ARL_BASE_ADDRESS + 0x00B8)
#define CORAL_BCF    (CORAL_REG_ARL_BASE_ADDRESS + 0x00BC)
#define CORAL_UNIPMF (CORAL_REG_ARL_BASE_ADDRESS + 0x00DC)

/* fields of AGDIS */
#define CORAL_AGDIS             (CORAL_REG_ARL_BASE_ADDRESS + 0x00C0)
#define CORAL_AGDIS_PORT_OFFSET (0)
#define CORAL_AGDIS_PORT_LENGTH (32)

/* fields of ATC */
#define CORAL_ATC                   (CORAL_REG_ARL_BASE_ADDRESS + 0x0300)
#define CORAL_ATC_CMD_OFFSET        (0)
#define CORAL_ATC_CMD_LENGTH        (3)
#define CORAL_ATC_SAT_OFFSET        (4)
#define CORAL_ATC_SAT_LENGTH        (3)
#define CORAL_ATC_MAT_OFFSET        (7)
#define CORAL_ATC_MAT_LENGTH        (5)
#define CORAL_ATC_ENTRY_HIT_OFFSET  (12)
#define CORAL_ATC_ENTRY_HIT_LENGTH  (4)
#define CORAL_ATC_ADDR_OFFSET       (16)
#define CORAL_ATC_ADDR_LENGTH       (10)
#define CORAL_ATC_SINGLE_HIT_OFFSET (30)
#define CORAL_ATC_SINGLE_HIT_LENGTH (1)
#define CORAL_ATC_BUSY_OFFSET       (31)
#define CORAL_ATC_BUSY_LENGTH       (1)

enum
{
    _ATC_CMD_READ = 0,
    _ATC_CMD_WRITE,
    _ATC_CMD_CLEAN,
    _ATC_CMD_SEARCH = 4,
    _ATC_CMD_SEARCH_NEXT,
    _ATC_CMD_LAST
};

#define CORAL_ATC_CMD_READ        (_ATC_CMD_READ << CORAL_ATC_CMD_OFFSET)
#define CORAL_ATC_CMD_WRITE       (_ATC_CMD_WRITE << CORAL_ATC_CMD_OFFSET)
#define CORAL_ATC_CMD_CLEAN       (_ATC_CMD_CLEAN << CORAL_ATC_CMD_OFFSET)
#define CORAL_ATC_CMD_SEARCH      (_ATC_CMD_SEARCH << CORAL_ATC_CMD_OFFSET)
#define CORAL_ATC_CMD_SEARCH_NEXT (_ATC_CMD_SEARCH_NEXT << CORAL_ATC_CMD_OFFSET)

enum
{
    _ATC_SAT_MAC = 0,
    _ATC_SAT_DIP,
    _ATC_SAT_SIP,
    _ATC_SAT_ADDR,
    _ATC_SAT_HALF_DIP,
    _ATC_SAT_HALF_SIP,
    _ATC_SAT_LAST
};

#define CORAL_ATC_SAT_MAC      (_ATC_SAT_MAC << CORAL_ATC_SAT_OFFSET)
#define CORAL_ATC_SAT_DIP      (_ATC_SAT_DIP << CORAL_ATC_SAT_OFFSET)
#define CORAL_ATC_SAT_SIP      (_ATC_SAT_SIP << CORAL_ATC_SAT_OFFSET)
#define CORAL_ATC_SAT_ADDR     (_ATC_SAT_ADDR << CORAL_ATC_SAT_OFFSET)
#define CORAL_ATC_SAT_HALF_DIP (_ATC_SAT_HALF_DIP << CORAL_ATC_SAT_OFFSET)
#define CORAL_ATC_SAT_HALF_SIP (_ATC_SAT_HALF_SIP << CORAL_ATC_SAT_OFFSET)

enum
{
    _ATC_MAT_ALL = 0,
    _ATC_MAT_MAC,
    _ATC_MAT_DYNAMIC_MAC,
    _ATC_MAT_STATIC_MAC,
    _ATC_MAT_DIP,
    _ATC_MAT_DIPV4,
    _ATC_MAT_DIPV6,
    _ATC_MAT_SIP,
    _ATC_MAT_SIPV4,
    _ATC_MAT_SIPV6,
    _ATC_MAT_MAC_BY_VID,
    _ATC_MAT_MAC_BY_FID,
    _ATC_MAT_MAC_BY_PORT,
    _ATC_MAT_SIP_BY_DIPV4,
    _ATC_MAT_SIP_BY_SIPV4,
    _ATC_MAT_SIP_BY_DIPV6,
    _ATC_MAT_SIP_BY_SIPV6,
    _ATC_MAT_MAC_BY_LIFETIME_VID,
    _ATC_MAT_MAC_BY_LIFETIME_FID,
    _ATC_MAT_MAC_BY_LIFETIME_PORT,
    _ATC_MAT_LAST
};

#define CORAL_ATC_MAT_ALL                  (_ATC_MAT_ALL << CORAL_ATC_MAT_OFFSET)
#define CORAL_ATC_MAT_MAC                  (_ATC_MAT_MAC << CORAL_ATC_MAT_OFFSET)
#define CORAL_ATC_MAT_DYNAMIC_MAC          (_ATC_MAT_DYNAMIC_MAC << CORAL_ATC_MAT_OFFSET)
#define CORAL_ATC_MAT_STATIC_MAC           (_ATC_MAT_STATIC_MAC << CORAL_ATC_MAT_OFFSET)
#define CORAL_ATC_MAT_DIP                  (_ATC_MAT_DIP << CORAL_ATC_MAT_OFFSET)
#define CORAL_ATC_MAT_DIPV4                (_ATC_MAT_DIPV4 << CORAL_ATC_MAT_OFFSET)
#define CORAL_ATC_MAT_DIPV6                (_ATC_MAT_DIPV6 << CORAL_ATC_MAT_OFFSET)
#define CORAL_ATC_MAT_SIP                  (_ATC_MAT_SIP << CORAL_ATC_MAT_OFFSET)
#define CORAL_ATC_MAT_SIPV4                (_ATC_MAT_SIPV4 << CORAL_ATC_MAT_OFFSET)
#define CORAL_ATC_MAT_SIPV6                (_ATC_MAT_SIPV6 << CORAL_ATC_MAT_OFFSET)
#define CORAL_ATC_MAT_MAC_BY_VID           (_ATC_MAT_MAC_BY_VID << CORAL_ATC_MAT_OFFSET)
#define CORAL_ATC_MAT_MAC_BY_FID           (_ATC_MAT_MAC_BY_FID << CORAL_ATC_MAT_OFFSET)
#define CORAL_ATC_MAT_MAC_BY_PORT          (_ATC_MAT_MAC_BY_PORT << CORAL_ATC_MAT_OFFSET)
#define CORAL_ATC_MAT_SIP_BY_DIPV4         (_ATC_MAT_SIP_BY_DIPV4 << CORAL_ATC_MAT_OFFSET)
#define CORAL_ATC_MAT_SIP_BY_SIPV4         (_ATC_MAT_SIP_BY_SIPV4 << CORAL_ATC_MAT_OFFSET)
#define CORAL_ATC_MAT_SIP_BY_DIPV6         (_ATC_MAT_SIP_BY_DIPV6 << CORAL_ATC_MAT_OFFSET)
#define CORAL_ATC_MAT_SIP_BY_SIPV6         (_ATC_MAT_SIP_BY_SIPV6 << CORAL_ATC_MAT_OFFSET)
#define CORAL_ATC_MAT_MAC_BY_LIFETIME_VID  (_ATC_MAT_MAC_BY_LIFETIME_VID << CORAL_ATC_MAT_OFFSET)
#define CORAL_ATC_MAT_MAC_BY_LIFETIME_FID  (_ATC_MAT_MAC_BY_LIFETIME_FID << CORAL_ATC_MAT_OFFSET)
#define CORAL_ATC_MAT_MAC_BY_LIFETIME_PORT (_ATC_MAT_MAC_BY_LIFETIME_PORT << CORAL_ATC_MAT_OFFSET)

#define CORAL_ATC_START_BUSY (0x01 << CORAL_ATC_BUSY_OFFSET)

/* fields of ATA1 */
#define CORAL_ATA1                     (CORAL_REG_ARL_BASE_ADDRESS + 0x0304)
#define CORAL_ATA1_MAC_ADDR_MSB_OFFSET (0)
#define CORAL_ATA1_MAC_ADDR_MSB_LENGTH (32)
#define CORAL_ATA1_SAT_ADDR_OFFSET     (0)
#define CORAL_ATA1_SAT_ADDR_LENGTH     (10)
#define CORAL_ATA1_SAT_BANK_OFFSET     (16)
#define CORAL_ATA1_SAT_BANK_LENGTH     (4)

/* fields of ATA2 */
#define CORAL_ATA2                     (CORAL_REG_ARL_BASE_ADDRESS + 0x0308)
#define CORAL_ATA2_MAC_AGETIME_OFFSET  (0)
#define CORAL_ATA2_MAC_AGETIME_LENGTH  (9)
#define CORAL_ATA2_MAC_LIFETIME_OFFSET (9)
#define CORAL_ATA2_MAC_LIFETIME_LENGTH (1)
#define CORAL_ATA2_MAC_UNAUTH_OFFSET   (10)
#define CORAL_ATA2_MAC_UNAUTH_LENGTH   (1)
#define CORAL_ATA2_MAC_ADDR_LSB_OFFSET (16)
#define CORAL_ATA2_MAC_ADDR_LSB_LENGTH (16)

/* fields of ATA3 */
#define CORAL_ATA3 (CORAL_REG_ARL_BASE_ADDRESS + 0x030C)

/* fields of ATA4 */
#define CORAL_ATA4 (CORAL_REG_ARL_BASE_ADDRESS + 0x0310)

/* fields of ATA5 */
#define CORAL_ATA5 (CORAL_REG_ARL_BASE_ADDRESS + 0x0314)

/* fields of ATA6 */
#define CORAL_ATA6 (CORAL_REG_ARL_BASE_ADDRESS + 0x0318)

/* fields of ATA7 */
#define CORAL_ATA7 (CORAL_REG_ARL_BASE_ADDRESS + 0x031C)

/* fields of ATA8 */
#define CORAL_ATA8 (CORAL_REG_ARL_BASE_ADDRESS + 0x0320)

/* fields of ATWD */
#define CORAL_ATWD                  (CORAL_REG_ARL_BASE_ADDRESS + 0x0324)
#define CORAL_ATWD_MAC_LIVE_OFFSET  (0)
#define CORAL_ATWD_MAC_LIVE_LENGTH  (1)
#define CORAL_ATWD_MAC_LEAK_OFFSET  (1)
#define CORAL_ATWD_MAC_LEAK_LENGTH  (1)
#define CORAL_ATWD_MAC_UPRI_OFFSET  (2)
#define CORAL_ATWD_MAC_UPRI_LENGTH  (3)
#define CORAL_ATWD_MAC_FWD_OFFSET   (5)
#define CORAL_ATWD_MAC_FWD_LENGTH   (3)
#define CORAL_ATWD_MAC_MIR_OFFSET   (8)
#define CORAL_ATWD_MAC_MIR_LENGTH   (2)
#define CORAL_ATWD_MAC_ETAG_OFFSET  (12)
#define CORAL_ATWD_MAC_ETAG_LENGTH  (3)
#define CORAL_ATWD_MAC_IVL_OFFSET   (15)
#define CORAL_ATWD_MAC_IVL_LENGTH   (1)
#define CORAL_ATWD_MAC_VID_OFFSET   (16)
#define CORAL_ATWD_MAC_VID_LENGTH   (12)
#define CORAL_ATWD_MAC_FID_OFFSET   (28)
#define CORAL_ATWD_MAC_FID_LENGTH   (4)
#define CORAL_ATWD_IPMC_LIVE_OFFSET (0)
#define CORAL_ATWD_IPMC_LIVE_LENGTH (1)
#define CORAL_ATWD_IPMC_LEAK_OFFSET (1)
#define CORAL_ATWD_IPMC_LEAK_LENGTH (1)
#define CORAL_ATWD_IPMC_UPRI_OFFSET (2)
#define CORAL_ATWD_IPMC_UPRI_LENGTH (3)
#define CORAL_ATWD_IPMC_IPV6_OFFSET (5)
#define CORAL_ATWD_IPMC_IPV6_LENGTH (1)
#define CORAL_ATWD_IPMC_ETAG_OFFSET (12)
#define CORAL_ATWD_IPMC_ETAG_LENGTH (3)
#define CORAL_ATWD_IPMC_VID_OFFSET  (16)
#define CORAL_ATWD_IPMC_VID_LENGTH  (12)

/* fields of ATWD2 */
#define CORAL_ATWD2                  (CORAL_REG_ARL_BASE_ADDRESS + 0x0328)
#define CORAL_ATWD2_MAC_PORT_OFFSET  (0)
#define CORAL_ATWD2_MAC_PORT_LENGTH  (11)
#define CORAL_ATWD2_IPMC_PORT_OFFSET (0)
#define CORAL_ATWD2_IPMC_PORT_LENGTH (11)

/* fields of ATWDS */
#define CORAL_ATRDS                 (CORAL_REG_ARL_BASE_ADDRESS + 0x0330)
#define CORAL_ATRDS_MAC_SEL_OFFSET  (0)
#define CORAL_ATRDS_MAC_SEL_LENGTH  (2)
#define CORAL_ATRDS_IPMC_SEL_OFFSET (0)
#define CORAL_ATRDS_IPMC_SEL_LENGTH (2)

/* fields of ATRD0 */
#define CORAL_ATRD0                     (CORAL_REG_ARL_BASE_ADDRESS + 0x0334)
#define CORAL_ATRD0_MAC_LIVE_OFFSET     (0)
#define CORAL_ATRD0_MAC_LIVE_LENGTH     (1)
#define CORAL_ATRD0_MAC_LIFETIME_OFFSET (1)
#define CORAL_ATRD0_MAC_LIFETIME_LENGTH (2)
#define CORAL_ATRD0_MAC_TYPE_OFFSET     (3)
#define CORAL_ATRD0_MAC_TYPE_LENGTH     (2)
#define CORAL_ATRD0_MAC_LEAK_OFFSET     (5)
#define CORAL_ATRD0_MAC_LEAK_LENGTH     (1)
#define CORAL_ATRD0_MAC_UPRI_OFFSET     (6)
#define CORAL_ATRD0_MAC_UPRI_LENGTH     (3)
#define CORAL_ATRD0_MAC_IVL_OFFSET      (9)
#define CORAL_ATRD0_MAC_IVL_LENGTH      (1)
#define CORAL_ATRD0_MAC_IVL_LENGTH      (1)
#define CORAL_ATRD0_MAC_VID_OFFSET      (10)
#define CORAL_ATRD0_MAC_VID_LENGTH      (12)
#define CORAL_ATRD0_MAC_ETAG_OFFSET     (22)
#define CORAL_ATRD0_MAC_ETAG_LENGTH     (3)
#define CORAL_ATRD0_MAC_FID_OFFSET      (25)
#define CORAL_ATRD0_MAC_FID_LENGTH      (4)
#define CORAL_ATRD0_MAC_UNAUTH_OFFSET   (31)
#define CORAL_ATRD0_MAC_UNAUTH_LENGTH   (1)
#define CORAL_ATRD0_IPMC_LIVE_OFFSET    (0)
#define CORAL_ATRD0_IPMC_LIVE_LENGTH    (1)
#define CORAL_ATRD0_IPMC_TYPE_OFFSET    (3)
#define CORAL_ATRD0_IPMC_TYPE_LENGTH    (2)
#define CORAL_ATRD0_IPMC_LEAK_OFFSET    (5)
#define CORAL_ATRD0_IPMC_LEAK_LENGTH    (1)
#define CORAL_ATRD0_IPMC_UPRI_OFFSET    (6)
#define CORAL_ATRD0_IPMC_UPRI_LENGTH    (3)
#define CORAL_ATRD0_IPMC_IPV6_OFFSET    (9)
#define CORAL_ATRD0_IPMC_IPV6_LENGTH    (1)
#define CORAL_ATRD0_IPMC_IVL_LENGTH     (1)
#define CORAL_ATRD0_IPMC_VID_OFFSET     (10)
#define CORAL_ATRD0_IPMC_VID_LENGTH     (12)
#define CORAL_ATRD0_IPMC_ETAG_OFFSET    (22)
#define CORAL_ATRD0_IPMC_ETAG_LENGTH    (3)

/* fields of ATRD1 */
#define CORAL_ATRD1                     (CORAL_REG_ARL_BASE_ADDRESS + 0x0338)
#define CORAL_ATRD1_MAC_FWD_OFFSET      (0)
#define CORAL_ATRD1_MAC_FWD_LENGTH      (3)
#define CORAL_ATRD1_MAC_AGETIME_OFFSET  (3)
#define CORAL_ATRD1_MAC_AGETIME_LENGTH  (9)
#define CORAL_ATRD1_MAC_MIR_OFFSET      (12)
#define CORAL_ATRD1_MAC_MIR_LENGTH      (2)
#define CORAL_ATRD1_MAC_ADDR_LSB_OFFSET (16)
#define CORAL_ATRD1_MAC_ADDR_LSB_LENGTH (16)
#define CORAL_ATRD1_IPMC_DIP_OFFSET     (0)
#define CORAL_ATRD1_IPMC_DIP_LENGTH     (32)

/* fields of ATRD2 */
#define CORAL_ATRD2                     (CORAL_REG_ARL_BASE_ADDRESS + 0x033C)
#define CORAL_ATRD2_MAC_ADDR_MSB_OFFSET (0)
#define CORAL_ATRD2_MAC_ADDR_MSB_LENGTH (32)
#define CORAL_ATRD2_IPMC_SIP_OFFSET     (0)
#define CORAL_ATRD2_IPMC_SIP_LENGTH     (32)

/* fields of ATRD3 */
#define CORAL_ATRD3                  (CORAL_REG_ARL_BASE_ADDRESS + 0x0340)
#define CORAL_ATRD3_MAC_PORT_OFFSET  (0)
#define CORAL_ATRD3_MAC_PORT_LENGTH  (11)
#define CORAL_ATRD3_IPMC_PORT_OFFSET (0)
#define CORAL_ATRD3_IPMC_PORT_LENGTH (11)

/* fields of LOGMACPORT */
#define CORAL_LOGMACPORT             (CORAL_REG_ARL_BASE_ADDRESS + 0x350)
#define CORAL_LOGMACPORT_PORT_OFFSET (0)
#define CORAL_LOGMACPORT_PORT_LENGTH (11)

/* fields of LOGMACDATA */
#define CORAL_LOGMACDATA                 (CORAL_REG_ARL_BASE_ADDRESS + 0x354)
#define CORAL_LOGMACDATA_BANK_OFFSET     (0)
#define CORAL_LOGMACDATA_BANK_LENGTH     (4)
#define CORAL_LOGMACDATA_ADDR_OFFSET     (4)
#define CORAL_LOGMACDATA_ADDR_LENGTH     (10)
#define CORAL_LOGMACDATA_PORTMOVE_OFFSET (15)
#define CORAL_LOGMACDATA_PORTMOVE_LENGTH (1)
#define CORAL_LOGMACDATA_REPLACE_OFFSET  (16)
#define CORAL_LOGMACDATA_REPLACE_LENGTH  (1)
#define CORAL_LOGMACDATA_EMPTY_OFFSET    (19)
#define CORAL_LOGMACDATA_EMPTY_LENGTH    (1)
#define CORAL_LOGMACDATA_CNT_OFFSET      (20)
#define CORAL_LOGMACDATA_CNT_LENGTH      (5)
#define CORAL_LOGMACDATA_NEXT_OFFSET     (31)
#define CORAL_LOGMACDATA_NEXT_LENGTH     (1)

/* fields of LOGAGEPORT */
#define CORAL_LOGAGEPORT             (CORAL_REG_ARL_BASE_ADDRESS + 0x358)
#define CORAL_LOGAGEPORT_PORT_OFFSET (0)
#define CORAL_LOGAGEPORT_PORT_LENGTH (11)

/* fields of LOGAGEDATA0 */
#define CORAL_LOGAGEDATA0              (CORAL_REG_ARL_BASE_ADDRESS + 0x35C)
#define CORAL_LOGAGEDATA0_FID_OFFSET   (0)
#define CORAL_LOGAGEDATA0_FID_LENGTH   (4)
#define CORAL_LOGAGEDATA0_VID_OFFSET   (4)
#define CORAL_LOGAGEDATA0_VID_LENGTH   (12)
#define CORAL_LOGAGEDATA0_IVL_OFFSET   (16)
#define CORAL_LOGAGEDATA0_IVL_LENGTH   (1)
#define CORAL_LOGAGEDATA0_EMPTY_OFFSET (19)
#define CORAL_LOGAGEDATA0_EMPTY_LENGTH (1)
#define CORAL_LOGAGEDATA0_CNT_OFFSET   (20)
#define CORAL_LOGAGEDATA0_CNT_LENGTH   (5)
#define CORAL_LOGAGEDATA0_NEXT_OFFSET  (31)
#define CORAL_LOGAGEDATA0_NEXT_LENGTH  (1)

/* fields of LOGAGEDATA1 */
#define CORAL_LOGAGEDATA1 (CORAL_REG_ARL_BASE_ADDRESS + 0x360)

/* fields of LOGAGEDATA2 */
#define CORAL_LOGAGEDATA2 (CORAL_REG_ARL_BASE_ADDRESS + 0x364)

/* fields of MACLMTC */
#define CORAL_MACLMTC                     (CORAL_REG_ARL_BASE_ADDRESS + 0x0370)
#define CORAL_MACLMTC_LMT_TICK_OFFSET     (0)
#define CORAL_MACLMTC_LMT_TICK_LENGTH     (3)
#define CORAL_MACLMTC_SA_FULL_DROP_OFFSET (4)
#define CORAL_MACLMTC_SA_FULL_DROP_LENGTH (1)
#define CORAL_MACLMTC_PORT_MV_DROP_OFFSET (5)
#define CORAL_MACLMTC_PORT_MV_DROP_LENGTH (1)
#define CORAL_MACLMTC_EXC_MNG_OFFSET      (30)
#define CORAL_MACLMTC_EXC_MNG_LENGTH      (1)
#define CORAL_MACLMTC_EN_OFFSET           (31)
#define CORAL_MACLMTC_EN_LENGTH           (1)

/* ACL ARP Rule format selector */
#define CORAL_ACL_ARP_SEL (CORAL_REG_ARL_BASE_ADDRESS + 0x053C)

/* fields of MACLMTTH */
#define CORAL_MACLMTTH                        (CORAL_REG_ARL_BASE_ADDRESS + 0x0374)
#define CORAL_MACLMTTH_SA_FULL_CPU_THR_OFFSET (0)
#define CORAL_MACLMTTH_SA_FULL_CPU_THR_LENGTH (8)
#define CORAL_MACLMTTH_PORT_MV_CPU_THR_OFFSET (8)
#define CORAL_MACLMTTH_PORT_MV_CPU_THR_LENGTH (8)

/* fields of MAUTHC */
#define CORAL_MAUTHC                         (CORAL_REG_ARL_BASE_ADDRESS + 0x03A0)
#define CORAL_MAUTHC_MAC_AUTH_OFFSET         (0)
#define CORAL_MAUTHC_MAC_AUTH_LENGTH         (1)
#define CORAL_MAUTHC_AUTH_FW_OFFSET          (4)
#define CORAL_MAUTHC_AUTH_FW_LENGTH          (2)
#define CORAL_MAUTHC_AUTH_FW_MAC             (0)
#define CORAL_MAUTHC_AUTH_FW_DROP            (2)
#define CORAL_MAUTHC_AUTH_FW_CPU             (3)
#define CORAL_MAUTHC_UNAUTH_FW_OFFSET        (6)
#define CORAL_MAUTHC_UNAUTH_FW_LENGTH        (2)
#define CORAL_MAUTHC_UNAUTH_FW_MAC           (0)
#define CORAL_MAUTHC_UNAUTH_FW_DROP          (2)
#define CORAL_MAUTHC_UNAUTH_FW_CPU           (3)
#define CORAL_MAUTHC_AUTH_PORT_MOVE_OFFSET   (8)
#define CORAL_MAUTHC_AUTH_PORT_MOVE_LENGTH   (1)
#define CORAL_MAUTHC_UNAUTH_PORT_MOVE_OFFSET (9)
#define CORAL_MAUTHC_UNAUTH_PORT_MOVE_LENGTH (1)

/* fields of GVMC */
#define CORAL_GVMC             (CORAL_REG_ARL_BASE_ADDRESS + 0x03A8)
#define CORAL_GVMC_GMEM_OFFSET (0)
#define CORAL_GVMC_GMEM_LENGTH (32)

/* fields of ingress and egress rate control */
#define CORAL_IRLCR(p)          (CORAL_REG_ARL_BASE_ADDRESS + (p * CORAL_PORT_CTRL_PORT_OFFSET) + 0x4000)
#define CORAL_ERLCR(p)          (CORAL_REG_ARL_BASE_ADDRESS + (p * CORAL_PORT_CTRL_PORT_OFFSET) + 0xC040)
#define CORAL_REG_RATE_CIR_OFFT (0)
#define CORAL_REG_RATE_CIR_LENG (19)
#define CORAL_REG_TB_EN_OFFT    (19)
#define CORAL_REG_RATE_TB_OFFT  (20)
#define CORAL_REG_RATE_TB_LENG  (4)
#define CORAL_REG_RATE_CBS_OFFT (24)
#define CORAL_REG_RATE_CBS_LENG (7)
#define CORAL_REG_RATE_EN_OFFT  (31)

/* fields of SFCR */
#define CORAL_SFCR(p)                  (CORAL_REG_ARL_BASE_ADDRESS + (p * CORAL_PORT_CTRL_PORT_OFFSET) + 0x4070)
#define CORAL_SFLOW_SAMPLING_RATE_OFFT (0)
#define CORAL_SFLOW_SAMPLING_RATE_LENG (24)
#define CORAL_SFLOW_SAMPLING_NUM_OFFT  (24)
#define CORAL_SFLOW_SAMPLING_NUM_LENG  (8)

/* fields of IBCR */
#define CORAL_IBCR(p)                        (CORAL_REG_ARL_BASE_ADDRESS + (p * CORAL_PORT_CTRL_PORT_OFFSET) + 0x40B0)
#define CORAL_REG_IGC_STOP_REFILL_TOKEN_OFFT (8)
#define CORAL_REG_IGC_STOP_REFILL_TOKEN_LENG (4)

/* fields of global ingress and egress rate control */
#define CORAL_GIRLCR               (CORAL_REG_ARL_BASE_ADDRESS + 0x7E24)
#define CORAL_GERLCR               (CORAL_REG_ARL_BASE_ADDRESS + 0xFE00)
#define CORAL_REG_IPG_BYTE_OFFT    (0)
#define CORAL_REG_IPG_BYTE_LENG    (8)
#define CORAL_REG_MFRM_EX_OFFT     (9)
#define CORAL_REG_MFRM_EX_LENG     (1)
#define CORAL_SFLOW_MFRM_EX_OFFT   (25)
#define CORAL_SFLOW_MFRM_EX_LENG   (1)
#define CORAL_L1_RATE_IPG_BYTE_CNT (0x18)
#define CORAL_L2_RATE_IPG_BYTE_CNT (0x04)

/* BMU Global Reg Base */
#define CORAL_BMU_GLOBAL (CORAL_REG_ARL_BASE_ADDRESS + 0x7E00)

/* fields of FPLC(Free Page Link Count Register ) */
#define CORAL_FPLC                          (CORAL_BMU_GLOBAL + 0x0)
#define CORAL_FPLC_MIN_FREE_PL_CNT_RST_OFFT (31)
#define CORAL_FPLC_MIN_FREE_PL_CNT_RST_LENG (1)
#define CORAL_FPLC_MIN_FREE_PL_CNT_OFFT     (16)
#define CORAL_FPLC_MIN_FREE_PL_CNT_LENG     (12)
#define CORAL_FPLC_FREE_PL_CNT_OFFT         (0)
#define CORAL_FPLC_FREE_PL_CNT_LENG         (12)

/* fields of GFCCR0(Global Flow Control Register0) */
#define CORAL_GFCCR0                  (CORAL_BMU_GLOBAL + 0x4)
#define CORAL_GFCCR0_FREE_BLK_HI_OFFT (15)
#define CORAL_GFCCR0_FREE_BLK_HI_LENG (10)
#define CORAL_GFCCR0_FREE_BLK_LO_OFFT (0)
#define CORAL_GFCCR0_FREE_BLK_LO_LENG (10)

/* fields of GFCCR1(Global Flow Control Register1) */
#define CORAL_GFCCR1                  (CORAL_BMU_GLOBAL + 0x8)
#define CORAL_GFCCR1_PORT_BLK_HI_OFFT (20)
#define CORAL_GFCCR1_PORT_BLK_HI_LENG (10)
#define CORAL_GFCCR1_PORT_BLK_LO_OFFT (10)
#define CORAL_GFCCR1_PORT_BLK_LO_LENG (10)
#define CORAL_GFCCR1_QUE_BLK_HI_OFFT  (0)
#define CORAL_GFCCR1_QUE_BLK_HI_LENG  (10)

/* fields of GFCCR2(Global Flow Control Register2) */
#define CORAL_GFCCR2                 (CORAL_BMU_GLOBAL + 0xC)
#define CORAL_GFCCR2_QUE_BLK_Q7_OFFT (24)
#define CORAL_GFCCR2_QUE_BLK_Q7_LENG (8)
#define CORAL_GFCCR2_QUE_BLK_Q6_OFFT (16)
#define CORAL_GFCCR2_QUE_BLK_Q6_LENG (8)
#define CORAL_GFCCR2_QUE_BLK_Q5_OFFT (8)
#define CORAL_GFCCR2_QUE_BLK_Q5_LENG (8)
#define CORAL_GFCCR2_QUE_BLK_Q4_OFFT (0)
#define CORAL_GFCCR2_QUE_BLK_Q4_LENG (8)

/* fields of GFCCR3(Global Flow Control Register3) */
#define CORAL_GFCCR3                 (CORAL_BMU_GLOBAL + 0x10)
#define CORAL_GFCCR3_QUE_BLK_Q3_OFFT (24)
#define CORAL_GFCCR3_QUE_BLK_Q3_LENG (8)
#define CORAL_GFCCR3_QUE_BLK_Q2_OFFT (16)
#define CORAL_GFCCR3_QUE_BLK_Q2_LENG (8)
#define CORAL_GFCCR3_QUE_BLK_Q1_OFFT (8)
#define CORAL_GFCCR3_QUE_BLK_Q1_LENG (8)
#define CORAL_GFCCR3_QUE_BLK_Q0_OFFT (0)
#define CORAL_GFCCR3_QUE_BLK_Q0_LENG (8)

/* field of l3 unicast routing table */
#define CORAL_RATCR              (CORAL_BMU_GLOBAL + 0x30)
#define CORAL_RATDPL             (CORAL_BMU_GLOBAL + 0x34)
#define CORAL_RATDPH             (CORAL_BMU_GLOBAL + 0x38)
#define CORAL_RAT_SEL_DA_OFFT    (31)
#define CORAL_RAT_SEL_DA_LENG    (1)
#define CORAL_RAT_SEL_WRITE_OFFT (30)
#define CORAL_RAT_SEL_WRITE_LENG (1)
#define CORAL_RAT_ADDR_OFFT      (0)
#define CORAL_RAT_ADDR_DA_LENG   (8)
#define CORAL_RAT_ADDR_SA_LENG   (4)
#define CORAL_RAT_DATA_L_OFFT    (0)
#define CORAL_RAT_DATA_L_LENG    (32)
#define CORAL_RAT_DATA_H_OFFT    (0)
#define CORAL_RAT_DATA_H_LENG    (16)

/* fields of PCPCR(Packet/Page Count Probe Control Register) */
#define CORAL_PCPCR                 (CORAL_BMU_GLOBAL + 0x48)
#define CORAL_PCPCR_PACKET_SEL_OFFT (31)
#define CORAL_PCPCR_PACKET_SEL_LENG (1)
#define CORAL_PCPCR_PORT_SEL_OFFT   (8)
#define CORAL_PCPCR_PORT_SEL_LENG   (5)
#define CORAL_PCPCR_QUEUE_SEL_OFFT  (0)
#define CORAL_PCPCR_QUEUE_SEL_LENG  (4)

/* fields of PCPSR(Packet/Page Count Probe Statuc Register) */
#define CORAL_PCPSR              (CORAL_BMU_GLOBAL + 0x4C)
#define CORAL_PCPSR_COUNTER_OFFT (0)
#define CORAL_PCPSR_COUNTER_LENG (11)

/* fields of CTRDDCR(CPU TX or RX Drop disable Control Register) */
#define CORAL_CTRDDCR                      (CORAL_BMU_GLOBAL + 0xF8)
#define CORAL_CTRDDCR_CPU_TX_DROP_DIS_OFFT (0)
#define CORAL_CTRDDCR_CPU_TX_DROP_DIS_LENG (11)

/* Port Control Base */
#define CORAL_PORT_CTRL_BASE         (0x8000)
#define CORAL_REG_ARL_PORT_BASE_ADDR (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_BASE)
#define CORAL_PORT_CTRL_REG(p, r)    (CORAL_PORT_CTRL_BASE + (p) * CORAL_PORT_CTRL_PORT_OFFSET + (r))

#define CORAL_SSC(p) (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x00))

#define CORAL_PCR(p)                  (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x04))
#define CORAL_PCR_PORT_VLAN_OFFT      (0)
#define CORAL_PCR_PORT_VLAN_LENG      (2)
#define CORAL_PCR_PORT_VLAN_RELMASK   (0x00000003)
#define CORAL_PCR_PORT_VLAN_MASK      (CORAL_PCR_PORT_VLAN_RELMASK << CORAL_PCR_PORT_VLAN_OFFT)
#define CORAL_PCR_UP_TO_CTAG_PRI_OFFT (11)
#define CORAL_PCR_UP_TO_DSCP_OFFT     (12)
#define CORAL_PCR_PORT_RX_MIR_OFFT    (16)
#define CORAL_PCR_PORT_RX_MIR_LENG    (4)
#define CORAL_PCR_PORT_TX_MIR_OFFT    (20)
#define CORAL_PCR_PORT_TX_MIR_LENG    (4)
#define CORAL_PCR_PORT_PRI_OFFT       (24)
#define CORAL_PCR_PORT_PRI_LENG       (3)
#define CORAL_PCR_PORT_PRI_RELMASK    (0x00000007)
#define CORAL_PCR_PORT_PRI_MASK       (CORAL_PCR_PORT_PRI_RELMASK << CORAL_PCR_PORT_PRI_OFFT)
#define CORAL_PCR_UP_TO_STAG_PRI_OFFT (27)
#define CORAL_PCR_EG_TAG_OFFT         (28)
#define CORAL_PCR_EG_TAG_LENG         (2)
#define CORAL_PCR_EG_TAG_RELMASK      (0x00000003)
#define CORAL_PCR_EG_TAG_MASK         (CORAL_PCR_EG_TAG_RELMASK << CORAL_PCR_EG_TAG_OFFT)

/* fields of PIC */
#define CORAL_PIC(p)                         (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x08))
#define CORAL_PIC_PORT_IGMP_CTRL_CSR_IPM_01  (1 << 8)
#define CORAL_PIC_PORT_IGMP_CTRL_CSR_IPM_33  (1 << 9)
#define CORAL_PIC_PORT_IGMP_CTRL_CSR_IPM_224 (1 << 10)

/* fields of PSC */
#define CORAL_PSC(p)                (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x0C))
#define CORAL_PSC_RX_LOCK_OFFSET    (0)
#define CORAL_PSC_RX_LOCK_LENGTH    (1)
#define CORAL_PSC_DIS_LRN_OFFSET    (4)
#define CORAL_PSC_DIS_LRN_LENGTH    (1)
#define CORAL_PSC_SA_CNT_EN_OFFSET  (5)
#define CORAL_PSC_SA_CNT_EN_LENGTH  (1)
#define CORAL_PSC_SA_CNT_LMT_OFFSET (8)
#define CORAL_PSC_SA_CNT_LMT_LENGTH (13)

#define CORAL_PVC(p)                       (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x10))
#define CORAL_PVC_ACC_FRM_OFFT             (0)
#define CORAL_PVC_ACC_FRM_LENG             (2)
#define CORAL_PVC_ACC_FRM_RELMASK          (0x00000003)
#define CORAL_PVC_ACC_FRM_MASK             (CORAL_PVC_ACC_FRM_RELMASK << CORAL_PVC_ACC_FRM_OFFT)
#define CORAL_PVC_UC_LKYV_EN_OFFT          (2)
#define CORAL_PVC_UC_LKYV_EN_LENG          (1)
#define CORAL_PVC_UC_LKYV_EN_RELMASK       (0x00000001)
#define CORAL_PVC_UC_LKYV_EN_MASK          (CORAL_PVC_UC_LKYV_EN_RELMASK << CORAL_PVC_UC_LKYV_EN_OFFT)
#define CORAL_PVC_MC_LKYV_EN_OFFT          (3)
#define CORAL_PVC_MC_LKYV_EN_LENG          (1)
#define CORAL_PVC_MC_LKYV_EN_RELMASK       (0x00000001)
#define CORAL_PVC_MC_LKYV_EN_MASK          (CORAL_PVC_MC_LKYV_EN_RELMASK << CORAL_PVC_MC_LKYV_EN_OFFT)
#define CORAL_PVC_BC_LKYV_EN_OFFT          (4)
#define CORAL_PVC_BC_LKYV_EN_LENG          (1)
#define CORAL_PVC_BC_LKYV_EN_RELMASK       (0x00000001)
#define CORAL_PVC_BC_LKYV_EN_MASK          (CORAL_PVC_BC_LKYV_EN_RELMASK << CORAL_PVC_BC_LKYV_EN_OFFT)
#define CORAL_PVC_SPTAG_EN_OFFT            (5)
#define CORAL_PVC_SPTAG_EN_LENG            (1)
#define CORAL_PVC_SPTAG_EN_RELMASK         (0x00000001)
#define CORAL_PVC_SPTAG_EN_MASK            (CORAL_PVC_SPTAG_EN_RELMASK << CORAL_PVC_SPTAG_EN_OFFT)
#define CORAL_PVC_VLAN_ATTR_OFFT           (6)
#define CORAL_PVC_VLAN_ATTR_LENG           (2)
#define CORAL_PVC_VLAN_ATTR_RELMASK        (0x00000003)
#define CORAL_PVC_VLAN_ATTR_MASK           (CORAL_PVC_VLAN_ATTR_RELMASK << CORAL_PVC_VLAN_ATTR_OFFT)
#define CORAL_PVC_EG_TAG_OFFT              (8)
#define CORAL_PVC_EG_TAG_LENG              (3)
#define CORAL_PVC_EG_TAG_RELMASK           (0x00000007)
#define CORAL_PVC_EG_TAG_MASK              (CORAL_PVC_EG_TAG_RELMASK << CORAL_PVC_EG_TAG_OFFT)
#define CORAL_PVC_SPTAG_MODE_OFFT          (11)
#define CORAL_PVC_SPTAG_MODE_LENG          (1)
#define CORAL_PVC_SPTAG_MODE_RELMASK       (0x00000001)
#define CORAL_PVC_SPTAG_MODE_MASK          (CORAL_PVC_SPTAG_MODE_RELMASK << CORAL_PVC_SPTAG_MODE_OFFT)
#define CORAL_PVC_CPU_BYPASS_TRUNK_OFFT    (12)
#define CORAL_PVC_CPU_BYPASS_TRUNK_LENG    (1)
#define CORAL_PVC_CPU_BYPASS_TRUNK_RELMASK (0x00000001)
#define CORAL_PVC_CPU_BYPASS_TRUNK_MASK    (CORAL_PVC_CPU_BYPASS_TRUNK_RELMASK << CORAL_PVC_CPU_BYPASS_TRUNK_OFFT)
#define CORAL_PVC_STAG_VPID_OFFT           (16)
#define CORAL_PVC_STAG_VPID_LENG           (16)
#define CORAL_PVC_STAG_VPID_RELMASK        (0x0000FFFF)
#define CORAL_PVC_STAG_VPID_MASK           (CORAL_PVC_STAG_VPID_RELMASK << CORAL_PVC_STAG_VPID_OFFT)

#define CORAL_PPBV1(p)                  (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x14))
#define CORAL_PPBV1_G0_PORT_VID_OFFT    (0)
#define CORAL_PPBV1_G0_PORT_VID_LENG    (12)
#define CORAL_PPBV1_G0_PORT_VID_RELMASK (0x00000FFF)
#define CORAL_PPBV1_G0_PORT_VID_MASK    (CORAL_PPBV1_G0_PORT_VID_RELMASK << CORAL_PPBV1_G0_PORT_VID_OFFT)

#define CORAL_PPBV2(p) (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x18))
#define CORAL_PUPW(p)  (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x30))

#define CORAL_EG_TPID(p)                   (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x40))
#define CORAL_EG_TPID_CSR_ETAG_TPID_0_OFFT (0)
#define CORAL_EG_TPID_CSR_ETAG_TPID_1_OFFT (16)
#define CORAL_EG_TPID_TPID_RELMASK         (0x0000FFFF)
#define CORAL_EG_TPID_TPID_MASK(offt)      (CORAL_EG_TPID_TPID_RELMASK << (offt))

#define CORAL_PVID(p)                 (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x48))
#define CORAL_PVID_CTAG_VID_OFFT      (0)
#define CORAL_PVID_CTAG_VID_LENG      (12)
#define CORAL_PVID_CTAG_VID_RELMASK   (0x00000FFF)
#define CORAL_PVID_CTAG_PORT_VID_MASK (CORAL_PVID_CTAG_VID_RELMASK << CORAL_PVID_CTAG_VID_OFFT)
#define CORAL_PVID_CTAG_PRI_OFFT      (12)
#define CORAL_PVID_CTAG_PRI_LENG      (3)
#define CORAL_PVID_CTAG_PRI_RELMASK   (0x00000007)
#define CORAL_PVID_CTAG_PORT_PRI_MASK (CORAL_PVID_CTAG_PRI_RELMASK << CORAL_PVID_CTAG_PRI_OFFT)
#define CORAL_PVID_STAG_VID_OFFT      (16)
#define CORAL_PVID_STAG_VID_LENG      (12)
#define CORAL_PVID_STAG_VID_RELMASK   (0x00000FFF)
#define CORAL_PVID_STAG_PORT_VID_MASK (CORAL_PVID_STAG_VID_RELMASK << CORAL_PVID_STAG_VID_OFFT)
#define CORAL_PVID_STAG_PRI_OFFT      (28)
#define CORAL_PVID_STAG_PRI_LENG      (3)
#define CORAL_PVID_STAG_PRI_RELMASK   (0x00000007)
#define CORAL_PVID_STAG_PORT_PRI_MASK (CORAL_PVID_STAG_PRI_RELMASK << CORAL_PVID_STAG_PRI_OFFT)

#define CORAL_PORTMATRIX(p) (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x44))

#define CORAL_PFFC(p)              (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x3C))
#define CORAL_CSR_FORCE_FW_EN_OFFT (31)
#define CORAL_CSR_FORCE_FW_EN_LENG (1)

#define CORAL_MIR (CORAL_REG_ARL_BASE_ADDRESS + (0xCC))
/* fields of MIR */
#define CORAL_MIR_BASE_OFFSET         (8)
#define CORAL_MIR_EN_OFFSET(p)        ((p) * CORAL_MIR_BASE_OFFSET + 0x07)
#define CORAL_MIR_EN_LEN              (1)
#define CORAL_MIR_PORT_OFFSET(p)      ((p) * CORAL_MIR_BASE_OFFSET + 0x00)
#define CORAL_MIR_PORT_LEN            (5)
#define CORAL_MIR_TAG_TX_EN_OFFSET(p) ((p) * CORAL_MIR_BASE_OFFSET + 0x06)
#define CORAL_MIR_TAG_TX_EN_LEN       (1)

#define CORAL_ABSTC (CORAL_REG_ARL_BASE_ADDRESS + 0xC4)
/* fields of MAC and Multicast */
#define CORAL_ATWD_IPM_VLD_OFFSET    (0)  /* bit[0]     */
#define CORAL_ATWD_IPM_LEAKY_OFFSET  (1)  /* bit[1]     */
#define CORAL_ATWD_IPM_UPRI_OFFSET   (2)  /* bit[4:2]   */
#define CORAL_ATWD_IPM_IPV6_OFFSET   (5)  /* bit[5]     */
#define CORAL_ATWD_IPM_EG_TAG_OFFSET (12) /* bit[14:12] */
#define CORAL_ATWD_IPM_VID_OFFSET    (16) /* bit[27:16] */

#define CORAL_ATWD_IPM_VLD_RANGE    (1)
#define CORAL_ATWD_IPM_LEAKY_RANGE  (1)
#define CORAL_ATWD_IPM_UPRI_RANGE   (3)
#define CORAL_ATWD_IPM_IPV6_RANGE   (1)
#define CORAL_ATWD_IPM_EG_TAG_RANGE (3)
#define CORAL_ATWD_IPM_VID_RANGE    (12)

#define CORAL_ATRD0_IPM_LEAKY_OFFSET (5)  /* bit[5] */
#define CORAL_ATRD0_IPM_LEAKY_RANGE  (1)
#define CORAL_ATRD0_IPM_VID_OFFSET   (10) /* bit[21:10] */
#define CORAL_ATRD0_IPM_VID_RANGE    (12)

/* BSR perport register map*/
#define CORAL_ARL_PORT_BSR_ADDR(p)       (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x50))
#define CORAL_ARL_PORT_BSR1_ADDR(p)      (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x54))
#define CORAL_ARL_PORT_BSR_EXT1_ADDR(p)  (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x58))
#define CORAL_ARL_PORT_BSR1_EXT1_ADDR(p) (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x5c))
#define CORAL_ARL_PORT_BSR_EXT2_ADDR(p)  (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x60))
#define CORAL_ARL_PORT_BSR1_EXT2_ADDR(p) (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x64))
#define CORAL_ARL_PORT_BSR_EXT3_ADDR(p)  (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x68))
#define CORAL_ARL_PORT_BSR1_EXT3_ADDR(p) (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x6c))

#define CORAL_ARL_PORT_BSTBS_ADDR(p)      (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x74))
#define CORAL_ARL_PORT_BSTBS_EXT1_ADDR(p) (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x78))
#define CORAL_ARL_PORT_BSTBS_EXT2_ADDR(p) (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x7c))
#define CORAL_ARL_PORT_BSTBS_EXT3_ADDR(p) (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x80))

/* fields of IGMP and MLD Message Control */
#define CORAL_IMMC(p)             (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0xA0))
#define CORAL_REG_MLD_MANG_OFFT   (30)
#define CORAL_REG_MLD_MANG_LENGTH (1)

#define CORAL_REG_MLD_BPDU_OFFT   (28)
#define CORAL_REG_MLD_BPDU_LENGTH (1)

#define CORAL_REG_MLD_PORT_FWD_OFFT   (16)
#define CORAL_REG_MLD_PORT_FWD_LENGTH (3)

#define CORAL_REG_IGMP_MANG_OFFT   (14)
#define CORAL_REG_IGMP_MANG_LENGTH (1)

#define CORAL_REG_IGMP_BPDU_OFFT   (12)
#define CORAL_REG_IGMP_BPDU_LENGTH (1)

#define CORAL_REG_IGMP_PORT_FWD_OFFT   (0)
#define CORAL_REG_IGMP_PORT_FWD_LENGTH (3)

/* fields of ARP and PPPoE Control */
#define CORAL_APC(p)                (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0xA4))
#define CORAL_REG_PPPOE_MANG_OFFT   (30)
#define CORAL_REG_PPPOE_MANG_LENGTH (1)

#define CORAL_REG_PPPOE_BPDU_OFFT   (28)
#define CORAL_REG_PPPOE_BPDU_LENGTH (1)

#define CORAL_REG_PPPOE_PORT_FWD_OFFT   (16)
#define CORAL_REG_PPPOE_PORT_FWD_LENGTH (3)

#define CORAL_REG_ARP_MANG_OFFT   (14)
#define CORAL_REG_ARP_MANG_LENGTH (1)

#define CORAL_REG_ARP_BPDU_OFFT   (12)
#define CORAL_REG_ARP_BPDU_LENGTH (1)

#define CORAL_REG_ARP_PORT_FWD_OFFT   (0)
#define CORAL_REG_ARP_PORT_FWD_LENGTH (3)

/* fields of PAE (un-tagged/ tagged) Control */
#define CORAL_PAC(p)                  (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0xA8))
#define CORAL_REG_TAG_PAE_MANG_OFFT   (30)
#define CORAL_REG_TAG_PAE_MANG_LENGTH (1)

#define CORAL_REG_TAG_PAE_BPDU_OFFT   (28)
#define CORAL_REG_TAG_PAE_BPDU_LENGTH (1)

#define CORAL_REG_TAG_PAE_PORT_FWD_OFFT   (16)
#define CORAL_REG_TAG_PAE_PORT_FWD_LENGTH (3)

#define CORAL_REG_UTAG_PAE_MANG_OFFT   (14)
#define CORAL_REG_UTAG_PAE_MANG_LENGTH (1)

#define CORAL_REG_UTAG_PAE_BPDU_OFFT   (12)
#define CORAL_REG_UTAG_PAE_BPDU_LENGTH (1)

#define CORAL_REG_UTAG_PAE_PORT_FWD_OFFT   (0)
#define CORAL_REG_UTAG_PAE_PORT_FWD_LENGTH (3)

/* fields of REV_01 and REV_02 Control */
#define CORAL_RGAC1(p)               (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0xAC))
#define CORAL_REG_REV_02_MANG_OFFT   (30)
#define CORAL_REG_REV_02_MANG_LENGTH (1)

#define CORAL_REG_REV_02_BPDU_OFFT   (28)
#define CORAL_REG_REV_02_BPDU_LENGTH (1)

#define CORAL_REG_REV_02_PORT_FWD_OFFT   (16)
#define CORAL_REG_REV_02_PORT_FWD_LENGTH (3)

#define CORAL_REG_REV_01_MANG_OFFT   (14)
#define CORAL_REG_REV_01_MANG_LENGTH (1)

#define CORAL_REG_REV_01_BPDU_OFFT   (12)
#define CORAL_REG_REV_01_BPDU_LENGTH (1)

#define CORAL_REG_REV_01_PORT_FWD_OFFT   (0)
#define CORAL_REG_REV_01_PORT_FWD_LENGTH (3)

/* fields of REV_03 and REV_0E Control */
#define CORAL_RGAC2(p)               (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0xB0))
#define CORAL_REG_REV_0E_MANG_OFFT   (30)
#define CORAL_REG_REV_0E_MANG_LENGTH (1)

#define CORAL_REG_REV_0E_BPDU_OFFT   (28)
#define CORAL_REG_REV_0E_BPDU_LENGTH (1)

#define CORAL_REG_REV_0E_PORT_FWD_OFFT   (16)
#define CORAL_REG_REV_0E_PORT_FWD_LENGTH (3)

#define CORAL_REG_REV_03_MANG_OFFT   (14)
#define CORAL_REG_REV_03_MANG_LENGTH (1)

#define CORAL_REG_REV_03_BPDU_OFFT   (12)
#define CORAL_REG_REV_03_BPDU_LENGTH (1)

#define CORAL_REG_REV_03_PORT_FWD_OFFT   (0)
#define CORAL_REG_REV_03_PORT_FWD_LENGTH (3)

/* fields of REV_10 and REV_20 Control */
#define CORAL_RGAC3(p)               (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0xB4))
#define CORAL_REG_REV_20_MANG_OFFT   (30)
#define CORAL_REG_REV_20_MANG_LENGTH (1)

#define CORAL_REG_REV_20_BPDU_OFFT   (28)
#define CORAL_REG_REV_20_BPDU_LENGTH (1)

#define CORAL_REG_REV_20_PORT_FWD_OFFT   (16)
#define CORAL_REG_REV_20_PORT_FWD_LENGTH (3)

#define CORAL_REG_REV_10_MANG_OFFT   (14)
#define CORAL_REG_REV_10_MANG_LENGTH (1)

#define CORAL_REG_REV_10_BPDU_OFFT   (12)
#define CORAL_REG_REV_10_BPDU_LENGTH (1)

#define CORAL_REG_REV_10_PORT_FWD_OFFT   (0)
#define CORAL_REG_REV_10_PORT_FWD_LENGTH (3)

/* fields of REV_21 and REV_UN Control */
#define CORAL_RGAC4(p)               (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0xB8))
#define CORAL_REG_REV_UN_MANG_OFFT   (30)
#define CORAL_REG_REV_UN_MANG_LENGTH (1)

#define CORAL_REG_REV_UN_BPDU_OFFT   (28)
#define CORAL_REG_REV_UN_BPDU_LENGTH (1)

#define CORAL_REG_REV_UN_PORT_FWD_OFFT   (16)
#define CORAL_REG_REV_UN_PORT_FWD_LENGTH (3)

#define CORAL_REG_REV_21_MANG_OFFT   (14)
#define CORAL_REG_REV_21_MANG_LENGTH (1)

#define CORAL_REG_REV_21_BPDU_OFFT   (12)
#define CORAL_REG_REV_21_BPDU_LENGTH (1)

#define CORAL_REG_REV_21_PORT_FWD_OFFT   (0)
#define CORAL_REG_REV_21_PORT_FWD_LENGTH (3)

/* fields of DHCP v4/v6 Control */
#define CORAL_DHCP(p)                (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0xBC))
#define CORAL_REG_DHCP_6_MANG_OFFT   (30)
#define CORAL_REG_DHCP_6_MANG_LENGTH (1)

#define CORAL_REG_DHCP_6_BPDU_OFFT   (28)
#define CORAL_REG_DHCP_6_BPDU_LENGTH (1)

#define CORAL_REG_DHCP_6_PORT_FWD_OFFT   (16)
#define CORAL_REG_DHCP_6_PORT_FWD_LENGTH (3)

#define CORAL_REG_DHCP_4_MANG_OFFT   (14)
#define CORAL_REG_DHCP_4_MANG_LENGTH (1)

#define CORAL_REG_DHCP_4_BPDU_OFFT   (12)
#define CORAL_REG_DHCP_4_BPDU_LENGTH (1)

#define CORAL_REG_DHCP_4_PORT_FWD_OFFT   (0)
#define CORAL_REG_DHCP_4_PORT_FWD_LENGTH (3)

/* fields of BPDU Control */
#define CORAL_BPC(p)                (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0xC0))
#define CORAL_REG_TTL_0_MANG_OFFT   (30)
#define CORAL_REG_TTL_0_MANG_LENGTH (1)

#define CORAL_REG_TTL_0_BPDU_OFFT   (28)
#define CORAL_REG_TTL_0_BPDU_LENGTH (1)

#define CORAL_REG_TTL_0_PORT_FWD_OFFT   (16)
#define CORAL_REG_TTL_0_PORT_FWD_LENGTH (3)

#define CORAL_REG_BPDU_MANG_OFFT   (14)
#define CORAL_REG_BPDU_MANG_LENGTH (1)

#define CORAL_REG_BPDU_BPDU_OFFT   (12)
#define CORAL_REG_BPDU_BPDU_LENGTH (1)

#define CORAL_REG_BPDU_EG_TAG_OFFT   (9)
#define CORAL_REG_BPDU_EG_TAG_LENGTH (3)

#define CORAL_REG_BPDU_PORT_FWD_OFFT   (0)
#define CORAL_REG_BPDU_PORT_FWD_LENGTH (3)

/* fields of LLDP Control */
#define CORAL_LCC(p)               (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0xC8))
#define CORAL_REG_LLDP_MANG_OFFT   (14)
#define CORAL_REG_LLDP_MANG_LENGTH (1)

#define CORAL_REG_LLDP_BPDU_OFFT   (12)
#define CORAL_REG_LLDP_BPDU_LENGTH (1)

#define CORAL_REG_LLDP_PORT_FWD_OFFT   (0)
#define CORAL_REG_LLDP_PORT_FWD_LENGTH (3)

/* fields of Management Frame Priority Control */
#define CORAL_MFP1(p)                (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x90))
#define CORAL_MFP1_IGMP_PRI_OFFT     (0)
#define CORAL_MFP1_MLD_PRI_OFFT      (4)
#define CORAL_MFP1_ARP_PRI_OFFT      (8)
#define CORAL_MFP1_PPPOE_PRI_OFFT    (12)
#define CORAL_MFP1_UTAG_PAE_PRI_OFFT (16)
#define CORAL_MFP1_TAG_PAE_PRI_OFFT  (20)
#define CORAL_MFP1_REV_01_PRI_OFFT   (24)
#define CORAL_MFP1_REV_02_PRI_OFFT   (28)

#define CORAL_MFP2(p)              (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x94))
#define CORAL_MFP2_REV_03_PRI_OFFT (0)
#define CORAL_MFP2_REV_0E_PRI_OFFT (4)
#define CORAL_MFP2_REV_10_PRI_OFFT (8)
#define CORAL_MFP2_REV_20_PRI_OFFT (12)
#define CORAL_MFP2_REV_21_PRI_OFFT (16)
#define CORAL_MFP2_REV_UN_PRI_OFFT (20)
#define CORAL_MFP2_DHCP_4_PRI_OFFT (24)
#define CORAL_MFP2_DHCP_6_PRI_OFFT (28)

#define CORAL_MFP3(p)             (CORAL_REG_ARL_BASE_ADDRESS + CORAL_PORT_CTRL_REG(p, 0x98))
#define CORAL_MFP3_BPDU_PRI_OFFT  (0)
#define CORAL_MFP3_TTL_0_PRI_OFFT (4)
#define CORAL_MFP3_LLDP_PRI_OFFT  (16)

#define CORAL_MFP_PRI_LENGTH (4)

/* fields of port mac control */
#define CORAL_GMAC_PORT_BASE (0x10210000)

#define CORAL_PMCR(p)                    (CORAL_GMAC_PORT_BASE + ((p) * CORAL_PORT_CTRL_PORT_OFFSET))
#define CORAL_MCR_FORCE_LINK_OFFT        (24)
#define CORAL_MCR_FORCE_LINK_LENG        (1)
#define CORAL_MCR_FORCE_DUPLEX_OFFT      (25)
#define CORAL_MCR_FORCE_DUPLEX_LENG      (1)
#define CORAL_MCR_FORCE_SPEED_OFFT       (28)
#define CORAL_MCR_FORCE_SPEED_LENG       (3)
#define CORAL_MCR_FORCE_FLOWCTRL_TX_OFFT (4)
#define CORAL_MCR_FORCE_FLOWCTRL_TX_LENG (1)
#define CORAL_MCR_FORCE_FLOWCTRL_RX_OFFT (5)
#define CORAL_MCR_FORCE_FLOWCTRL_RX_LENG (1)
#define CORAL_MCR_EEE_100_EN_OFFT        (6)
#define CORAL_MCR_EEE_1G_EN_OFFT         (7)
#define CORAL_MCR_EEE_2P5G_EN_OFFT       (8)
#define CORAL_MCR_EEE_5G_EN_OFFT         (9)
#define CORAL_MCR_EEE_10G_EN_OFFT        (10)
#define CORAL_MCR_EEE_EN_LENG            (1)
#define CORAL_MCR_BACK_PRESSURE_OFFT     (11)
#define CORAL_MCR_BACK_PRESSURE_LENG     (1)
#define CORAL_MCR_FORCE_MAC_PRE_OFFT     (14)
#define CORAL_MCR_FORCE_RX_ENABLE_OFFT   (15)
#define CORAL_MCR_FORCE_RX_ENABLE_LENG   (1)
#define CORAL_MCR_FORCE_TX_ENABLE_OFFT   (16)
#define CORAL_MCR_FORCE_TX_ENABLE_LENG   (1)
#define CORAL_MCR_IPG_CFG_OFFT           (20)
#define CORAL_MCR_IPG_CFG_LENG           (3)
#define CORAL_MCR_FORCE_MODE_OFFT        (31)
#define CORAL_MCR_FORCE_MODE_LENG        (1)

#define CORAL_PMSR(p)                   (CORAL_GMAC_PORT_BASE + (p * CORAL_PORT_CTRL_PORT_OFFSET) + 0x10)
#define CORAL_REG_PORT_LINK_OFFT        (24)
#define CORAL_REG_PORT_LINK_LENG        (1)
#define CORAL_REG_PORT_DUPLEX_OFFT      (25)
#define CORAL_REG_PORT_DUPLEX_LENG      (1)
#define CORAL_REG_PORT_SPEED_OFFT       (28)
#define CORAL_REG_PORT_SPEED_LENG       (3)
#define CORAL_REG_PORT_TX_FLOWCTRL_OFFT (4)
#define CORAL_REG_PORT_TX_FLOWCTRL_LENG (1)
#define CORAL_REG_PORT_RX_FLOWCTRL_OFFT (5)
#define CORAL_REG_PORT_RX_FLOWCTRL_LENG (1)
#define CORAL_REG_PORT_EEE_100_EN_OFFT  (6)
#define CORAL_REG_PORT_EEE_1G_EN_OFFT   (7)
#define CORAL_REG_PORT_EEE_2P5G_EN_OFFT (8)
#define CORAL_REG_PORT_EEE_EN_LENG      (1)
#define CORAL_REG_PORT_LPI_STS_OFFT     (11)
#define CORAL_REG_PORT_LPI_STS_LENG     (1)

/* fields of global mac control */
#define CORAL_GMAC_GLOBAL_BASE (0x10213E00)

#define CORAL_GMACCR              (CORAL_GMAC_GLOBAL_BASE)
#define CORAL_MAX_RX_PKT_LEN_OFFT (0)
#define CORAL_MAX_RX_PKT_LEN_LENG (2)
#define CORAL_MAX_RX_JUMBO_OFFT   (4)
#define CORAL_MAX_RX_JUMBO_LENG   (4)
#define CORAL_GMACCR_MTCC_OFFT    (8)
#define CORAL_GMACCR_MTCC_LENG    (4)

#define CORAL_SMACCR0 (CORAL_GMAC_GLOBAL_BASE + 0x10)
#define CORAL_SMACCR1 (CORAL_GMAC_GLOBAL_BASE + 0x14)

#define CORAL_CKGCR (CORAL_GMAC_GLOBAL_BASE + 0x1C)

#define CORAL_CKG_LNKDN_GLB_STOP (0x03)

#define CORAL_MIB_CCR                 (CORAL_GMAC_GLOBAL_BASE + 0x30)
#define CORAL_MIB_CCR_MIB_ENABLE      (1 << 31)
#define CORAL_MIB_CCR_RX_OCT_CNT_GOOD (1 << 7)
#define CORAL_MIB_CCR_RX_OCT_CNT_BAD  (1 << 6)
#define CORAL_MIB_CCR_TX_OCT_CNT_GOOD (1 << 5)
#define CORAL_MIB_CCR_TX_OCT_CNT_BAD  (1 << 4)

#define CORAL_MIB_PCLR         (CORAL_GMAC_GLOBAL_BASE + 0x34)
#define CORAL_MIB_PCLR_PORT(p) (1 << p)

#define CORAL_LPDETTXCR             (CORAL_GMAC_GLOBAL_BASE + 0x100)
#define CORAL_LPDETRXCR             (CORAL_GMAC_GLOBAL_BASE + 0x104)
#define CORAL_LPDETCR               (CORAL_GMAC_GLOBAL_BASE + 0x108)
#define CORAL_LPDETCR_OVER_RXPAUSE  (1 << 11)
#define CORAL_LPDETCR_PERIOD_1S     (1 << 7)
#define CORAL_LPDETRXSR             (CORAL_GMAC_GLOBAL_BASE + 0x110)
#define CORAL_LPDETTXSR             (CORAL_GMAC_GLOBAL_BASE + 0x114)
#define CORAL_LPDET_SA_MSB          (CORAL_GMAC_GLOBAL_BASE + 0x120)
#define CORAL_LPDET_FRAME_TYPE_OFFT (16)
#define CORAL_LPDET_FRAME_TYPE_LENG (16)
#define CORAL_LPDET_SMAC_MASK       (0xFFFF)
#define CORAL_LPDET_SA_LSB          (CORAL_GMAC_GLOBAL_BASE + 0x124)

/* Fields of SGMII control */
#define CORAL_SGMII_BASE_ADDR (0x10220000)
#define CORAL_SGMII_PORT_OFFT (0x10000)

#define CORAL_FPGA_USED_ADDR(p) (0x1022A400 + (p * CORAL_SGMII_PORT_OFFT))
#define CORAL_FPGA_USED_VAL     (0x01000000)

#define CORAL_PCS_CTRL(p)                    (CORAL_SGMII_BASE_ADDR + (p * CORAL_SGMII_PORT_OFFT))
#define CORAL_PCS_ADV_ABILITY(p)             (CORAL_SGMII_BASE_ADDR + (p * CORAL_SGMII_PORT_OFFT) + 0x10)
#define CORAL_REG_TX_ABILITY_SGMII_OFFT      (0)
#define CORAL_REG_TX_ABILITY_SGMII_LENG      (1)
#define CORAL_REG_1000BASEX_FULL_DUPLEX_OFFT (5)

/* CL37 tx ability*/
#define CORAL_REG_CL_FULL_DUPLEX_OFFT (5)
#define CORAL_REG_CL_HALF_DUPLEX_OFFT (6)
#define CORAL_REG_CL_PAUSE_OFFT       (7)
#define CORAL_REG_CL_PAUSE_LENG       (2)
/* SGMII tx ability */
#define CORAL_REG_SG_SPEED_OFFT       (10)
#define CORAL_REG_SG_SPEED_LENG       (2)
#define CORAL_REG_SG_FULL_DUPLEX_OFFT (12)
#define CORAL_REG_SG_FULL_DUPLEX_LENG (1)

#define CORAL_SGMII_IF_MODE(p)       (CORAL_SGMII_BASE_ADDR + (p * CORAL_SGMII_PORT_OFFT) + 0x34)
#define CORAL_REG_IF_MODE_OFFT       (0)
#define CORAL_REG_IF_MODE_LENG       (6)
#define CORAL_REG_IF_MODE_1000BASEX  (0x22)
#define CORAL_REG_IF_MODE_SGMII      (0x23)
#define CORAL_REG_IF_MODE_AN_OFFT    (1)
#define CORAL_REG_IF_MODE_SPEED_OFFT (2)
#define CORAL_REG_IF_MODE_SPEED_LENG (2)
/* 0:Full, 1:Half */
#define CORAL_REG_IF_MODE_FULL_DUPLEX_OFFT (4)
#define CORAL_REG_REMOTE_FAULT_OFFT        (8)

#define CORAL_HSGMII_PCS_CTRL_1(p)      (CORAL_SGMII_BASE_ADDR + (p * CORAL_SGMII_PORT_OFFT) + 0xA00)
#define CORAL_REG_HSGMII_AN_ENABLE_OFFT (10)

#define CORAL_HSGMII_PCS_CTRL(p)        (CORAL_SGMII_BASE_ADDR + (p * CORAL_SGMII_PORT_OFFT) + 0xA14)
#define CORAL_REG_SGMII_EN_OFFT         (0)
#define CORAL_REG_SGMII_EN_LENG         (1)
#define CORAL_REG_SGMII_RATEADAPT_OFFT  (1)
#define CORAL_REG_SGMII_RATEADAPT_LENG  (1)
#define CORAL_REG_SGMII_TX_EN_OFFT      (4)
#define CORAL_REG_SGMII_TX_EN_LENG      (1)
#define CORAL_REG_SGMII_FORCE_1000_OFFT (12)
#define CORAL_REG_SGMII_FORCE_1000_LENG (1)
#define CORAL_REG_SGMII_FORCE_100_OFFT  (13)
#define CORAL_REG_SGMII_FORCE_100_LENG  (1)
#define CORAL_REG_SGMII_FORCE_10_OFFT   (14)
#define CORAL_REG_SGMII_FORCE_10_LENG   (1)

#define CORAL_HSGMII_PCS_STATUS(p)    (CORAL_SGMII_BASE_ADDR + (p * CORAL_SGMII_PORT_OFFT) + 0xB04)
#define CORAL_REG_HSGMII_AN_DONE_OFFT (0)
#define CORAL_REG_HSGMII_RX_SYNC_OFFT (5)

#define CORAL_MII_RA_AN(p)       (CORAL_SGMII_BASE_ADDR + (p * CORAL_SGMII_PORT_OFFT) + 0x6300)
#define CORAL_REG_RA_AN_EN0_OFFT (0)

#define CORAL_SGMII_PHYA_11(p)    (CORAL_SGMII_BASE_ADDR + (p * CORAL_SGMII_PORT_OFFT) + 0xA02C)
#define CORAL_REG_TPHY_MODE_OFFT  (0)
#define CORAL_REG_TPHY_MODE_LENG  (2)
#define CORAL_REG_TPHY_SPEED_OFFT (2)
#define CORAL_REG_TPHY_SPEED_LENG (2)

#define CORAL_FPGA_CTRL(p) (CORAL_SGMII_BASE_ADDR + (p * CORAL_SGMII_PORT_OFFT) + 0xA400)

#define CORAL_PORT_TRUNK_OFFSET (0x0400)
#define CORAL_PTC               (CORAL_REG_ARL_BASE_ADDRESS + (CORAL_PORT_TRUNK_OFFSET + 0x00))
/* fields of PTC */
#define CORAL_PTC_INFO_OFFT      (0)
#define CORAL_PTC_INFO_LEN       (7)
#define CORAL_PTC_INFO_SEL_SP    (1 << 0)
#define CORAL_PTC_INFO_SEL_SA    (1 << 1)
#define CORAL_PTC_INFO_SEL_DA    (1 << 2)
#define CORAL_PTC_INFO_SEL_SIP   (1 << 3)
#define CORAL_PTC_INFO_SEL_DIP   (1 << 4)
#define CORAL_PTC_INFO_SEL_SPORT (1 << 5)
#define CORAL_PTC_INFO_SEL_DPORT (1 << 6)
#define CORAL_PTC_SP_SEL         (1 << 20)

#define CORAL_PTC_HASH_CONTROL_OFFT (8)
#define CORAL_PTC_HASH_CONTROL_LEN  (2)

#define CORAL_PTSEED (CORAL_REG_ARL_BASE_ADDRESS + (CORAL_PORT_TRUNK_OFFSET + 0x04))

#define CORAL_PTGC                    (CORAL_REG_ARL_BASE_ADDRESS + (CORAL_PORT_TRUNK_OFFSET + 0x08))
#define CORAL_PTGC_GROUP_EN_OFFSET(g) (g)
#define CORAL_PTGC_GROUP_EN_LEN       (1)

#define CORAL_PTG_BASE (8)

#define CORAL_PTG_1(g)               (CORAL_REG_ARL_BASE_ADDRESS + (CORAL_PORT_TRUNK_OFFSET + 0x0C + ((g) * 0x8)))
#define CORAL_PTG_2(g)               (CORAL_REG_ARL_BASE_ADDRESS + (CORAL_PORT_TRUNK_OFFSET + 0x10 + ((g) * 0x8)))
#define CORAL_PTGN_PORT_OFFSET(p)    ((CORAL_PTG_BASE * ((p) % 4)) + 0x0)
#define CORAL_PTGN_PORT_LEN          (5)
#define CORAL_PTGN_PORT_EN_OFFSET(p) ((CORAL_PTG_BASE * ((p) % 4)) + 0x7)
#define CORAL_PTGN_PORT_EN_LEN       (1)

/* Register of MIB Base address */
#define CORAL_MIB_BASE        (CORAL_REG_ARL_BASE_ADDRESS + 0x14000)
#define CORAL_MIB_PORT_OFFSET (0x0200)

#define CORAL_MIB_TCDPC(p)    (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x00)
#define CORAL_MIB_TCEPC(p)    (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x04)
#define CORAL_MIB_TUPC(p)     (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x08)
#define CORAL_MIB_TMPC(p)     (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x0C)
#define CORAL_MIB_TBPC(p)     (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x10)
#define CORAL_MIB_TCEC(p)     (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x14)
#define CORAL_MIB_TSCEC(p)    (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x18)
#define CORAL_MIB_TMCEC(p)    (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x1C)
#define CORAL_MIB_TDEC(p)     (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x20)
#define CORAL_MIB_TLCEC(p)    (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x24)
#define CORAL_MIB_TXCEC(p)    (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x28)
#define CORAL_MIB_TPPC(p)     (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x2C)
#define CORAL_MIB_TL64PC(p)   (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x30)
#define CORAL_MIB_TL65PC(p)   (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x34)
#define CORAL_MIB_TL128PC(p)  (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x38)
#define CORAL_MIB_TL256PC(p)  (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x3C)
#define CORAL_MIB_TL512PC(p)  (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x40)
#define CORAL_MIB_TL1024PC(p) (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x44)
#define CORAL_MIB_TL1519PC(p) (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x48)
#define CORAL_MIB_TOCL(p)     (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x4C)
#define CORAL_MIB_TOCH(p)     (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x50)
#define CORAL_MIB_TODPC(p)    (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x54)
#define CORAL_MIB_TOCL2(p)    (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x58)
#define CORAL_MIB_TOCH2(p)    (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x5C)

#define CORAL_MIB_RDPC(p)     (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x80)
#define CORAL_MIB_RFPC(p)     (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x84)
#define CORAL_MIB_RUPC(p)     (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x88)
#define CORAL_MIB_RMPC(p)     (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x8C)
#define CORAL_MIB_RBPC(p)     (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x90)
#define CORAL_MIB_RAEPC(p)    (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x94)
#define CORAL_MIB_RCEPC(p)    (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x98)
#define CORAL_MIB_RUSPC(p)    (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x9C)
#define CORAL_MIB_RFEPC(p)    (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0xA0)
#define CORAL_MIB_ROSPC(p)    (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0xA4)
#define CORAL_MIB_RJEPC(p)    (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0xA8)
#define CORAL_MIB_RPPC(p)     (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0xAC)
#define CORAL_MIB_RL64PC(p)   (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0xB0)
#define CORAL_MIB_RL65PC(p)   (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0xB4)
#define CORAL_MIB_RL128PC(p)  (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0xB8)
#define CORAL_MIB_RL256PC(p)  (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0xBC)
#define CORAL_MIB_RL512PC(p)  (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0xC0)
#define CORAL_MIB_RL1024PC(p) (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0xC4)
#define CORAL_MIB_RL1519PC(p) (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0xC8)
#define CORAL_MIB_ROCL(p)     (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0xCC)
#define CORAL_MIB_ROCH(p)     (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0xD0)
#define CORAL_MIB_RCDPC(p)    (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0xD4)
#define CORAL_MIB_RIDPC(p)    (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0xD8)
#define CORAL_MIB_RADPC(p)    (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0xDC)
#define CORAL_MIB_ROCL2(p)    (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0xEC)
#define CORAL_MIB_ROCH2(p)    (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0xF0)
#define CORAL_MIB_RXCDPC(p)   (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0xFC)

#define CORAL_MIB_TMIB_HF_STS(p) (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x7C)
#define CORAL_MIB_RMIB_HF_STS(p) (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0x100)

#define CORAL_MIB_FCDPC(p)  (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0xE0)
#define CORAL_MIB_WRDPC(p)  (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0xE4)
#define CORAL_MIB_MRDPC(p)  (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0xE8)
#define CORAL_MIB_RSFSPC(p) (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0xF4)
#define CORAL_MIB_RSFTPC(p) (CORAL_MIB_BASE + (p) * CORAL_MIB_PORT_OFFSET + 0xF8)

/* Register of DoS Attack Prevention address */
#define CORAL_ATTACK_PREVENT_GLB         (CORAL_REG_ARL_BASE_ADDRESS + 0x0540)
#define CORAL_ATTACK_PREVENT_GLB_EN_OFFT (0)
#define CORAL_ATTACK_PREVENT_GLB_EN_LENG (1)

#define CORAL_ATTACK_LENGTH_CFG       (CORAL_ATTACK_PREVENT_GLB + 0x04)
#define CORAL_ATTACK_LENGTH_THLD_OFFT (0)
#define CORAL_ATTACK_LENGTH_THLD_LENG (16)

#define CORAL_ATTACK_TCP_FLAG_CFG        (CORAL_ATTACK_PREVENT_GLB + 0x08)
#define CORAL_ATTACK_TCP_FLAG_MSK        (CORAL_ATTACK_PREVENT_GLB + 0x0c)
#define CORAL_ATTACK_TCP_SETTING_OFFT(i) ((i) * (CORAL_ATTACK_TCP_SETTING_LENG + 1))
#define CORAL_ATTACK_TCP_SETTING_LENG    (9)
#define CORAL_ATTACK_TCP_FLAG_SEL_NS     (1 << 8)
#define CORAL_ATTACK_TCP_FLAG_SEL_CWR    (1 << 7)
#define CORAL_ATTACK_TCP_FLAG_SEL_ECE    (1 << 6)
#define CORAL_ATTACK_TCP_FLAG_SEL_URG    (1 << 5)
#define CORAL_ATTACK_TCP_FLAG_SEL_ACK    (1 << 4)
#define CORAL_ATTACK_TCP_FLAG_SEL_PSH    (1 << 3)
#define CORAL_ATTACK_TCP_FLAG_SEL_RST    (1 << 2)
#define CORAL_ATTACK_TCP_FLAG_SEL_SYN    (1 << 1)
#define CORAL_ATTACK_TCP_FLAG_SEL_FIN    (1 << 0)

#define CORAL_ATTACK_ACTION_CFG          (CORAL_ATTACK_PREVENT_GLB + 0x10)
#define CORAL_ATTACK_ACTION_CFG_PID_OFFT (4)
#define CORAL_ATTACK_ACTION_CFG_PID_LENG (5)

/* for both ATTACK_ACTION_CFG and ATTACK_RATE_CFG */
#define CORAL_ATTACK_CFG_DONE_OFFT  (31)
#define CORAL_ATTACK_CFG_DONE_LENG  (1)
#define CORAL_ATTACK_CFG_CLEAR_OFFT (2)
#define CORAL_ATTACK_CFG_WR_OFFT    (1)
#define CORAL_ATTACK_CFG_EN_OFFT    (0)

#define CORAL_ATTACK_FUNC_CFG         (CORAL_ATTACK_PREVENT_GLB + 0x14)
#define CORAL_ATTACK_TCP_HDR_MIN_OFFT (0)
#define CORAL_ATTACK_TCP_HDR_MIN_LENG (4)

#define CORAL_ATTACK_ACTION_REG_LENG      (32)
#define CORAL_ATTACK_ACTION_SRAM_WR_DATA0 (CORAL_ATTACK_PREVENT_GLB + 0x18)
#define CORAL_ATTACK_ACTION_SRAM_WR_DATA1 (CORAL_ATTACK_PREVENT_GLB + 0x1c)
#define CORAL_ATTACK_ACTION_SRAM_WR_DATA2 (CORAL_ATTACK_PREVENT_GLB + 0x2c)

#define CORAL_ATTACK_ACTION_RATE_ID_LENG (7)
#define CORAL_ATTACK_ACTION_RATE_EN_LENG (1)
#define CORAL_ATTACK_ACTION_DROP_LENG    (1)

#define CORAL_ATTACK_ACTION_LENG (CORAL_ATTACK_ACTION_RATE_ID_LENG + CORAL_ATTACK_ACTION_RATE_EN_LENG + \
                                  CORAL_ATTACK_ACTION_DROP_LENG)
#define CORAL_ATTACK_RATE_EN_OFFT(g) ((g) + CORAL_ATTACK_ACTION_RATE_ID_LENG)
#define CORAL_ATTACK_DROP_EN_OFFT(g) ((g) + CORAL_ATTACK_ACTION_RATE_ID_LENG + CORAL_ATTACK_ACTION_RATE_EN_LENG)

#define CORAL_ATTACK_ACTION_SRAM_RE_DATA0 (CORAL_ATTACK_PREVENT_GLB + 0x20)
#define CORAL_ATTACK_ACTION_SRAM_RE_DATA1 (CORAL_ATTACK_PREVENT_GLB + 0x24)
#define CORAL_ATTACK_ACTION_SRAM_RE_DATA2 (CORAL_ATTACK_PREVENT_GLB + 0x28)

#define CORAL_ATTACK_RATE_CFG               (CORAL_ATTACK_PREVENT_GLB + 0x30)
#define CORAL_ATTACK_RATE_CFG_RATE_ID_OFFT  (4)
#define CORAL_ATTACK_RATE_CFG_RATE_ID_LENG  (7)
#define CORAL_ATTACK_RATE_SRAM_WR_DATA0     (CORAL_ATTACK_PREVENT_GLB + 0x38)
#define CORAL_ATTACK_RATE_SRAM_WR_DATA1     (CORAL_ATTACK_PREVENT_GLB + 0x3c)
#define CORAL_ATTACK_RATE_WR_CFG_LENG       (16)
#define CORAL_ATTACK_RATE_WR_TICK_SEL_LENG  (1)
#define CORAL_ATTACK_RATE_TIME_SPAN_OFFT    (0)
#define CORAL_ATTACK_RATE_PKT_NUM_THLD_OFFT (16)
#define CORAL_ATTACK_RATE_BLOCK_TIME_OFFT   (0)
#define CORAL_ATTACK_RATE_TICK_SEL_OFFT     (16)
#define CORAL_ATTACK_RATE_SRAM_RE_DATA0     (CORAL_ATTACK_PREVENT_GLB + 0x40)
#define CORAL_ATTACK_RATE_SRAM_RE_DATA1     (CORAL_ATTACK_PREVENT_GLB + 0x44)

#define CORAL_ATTACK_DROP_CNT        (CORAL_ATTACK_PREVENT_GLB + 0x50)
#define CORAL_ATTACK_DROP_CNT_CLR    (CORAL_ATTACK_DROP_CNT + 0x04)
#define CORAL_ATTACK_DROP_CNT_CLR_A0 (1 << 0)
/* Register of ACL address */
#define CORAL_ARL_GLOBAL_CNTRL    (CORAL_REG_ARL_BASE_ADDRESS + 0x00c)
#define CORAL_ACL_BASE            (CORAL_REG_ARL_BASE_ADDRESS + 0x500)
#define CORAL_ACL_GLOBAL_CFG      (CORAL_ACL_BASE + 0x00)
#define CORAL_ACL_PORT_EN         (CORAL_ACL_BASE + 0x04)
#define CORAL_ACL_GROUP_CFG       (CORAL_ACL_BASE + 0x08)
#define CORAL_ACL_MEM_CFG         (CORAL_ACL_BASE + 0x0c)
#define CORAL_ACL_MEM_CFG_WDATA0  (CORAL_ACL_BASE + 0x10)
#define CORAL_ACL_MEM_CFG_WDATA1  (CORAL_ACL_BASE + 0x14)
#define CORAL_ACL_MEM_CFG_WDATA2  (CORAL_ACL_BASE + 0x18)
#define CORAL_ACL_MEM_CFG_WDATA3  (CORAL_ACL_BASE + 0x1c)
#define CORAL_ACL_MEM_CFG_RDATA0  (CORAL_ACL_BASE + 0x20)
#define CORAL_ACL_MEM_CFG_RDATA1  (CORAL_ACL_BASE + 0x24)
#define CORAL_ACL_MEM_CFG_RDATA2  (CORAL_ACL_BASE + 0x28)
#define CORAL_ACL_MEM_CFG_RDATA3  (CORAL_ACL_BASE + 0x2c)
#define CORAL_ACL_STATUS          (CORAL_ACL_BASE + 0x30)
#define CORAL_ACL_MIB_CNT_CFG     (CORAL_ACL_BASE + 0x34)
#define CORAL_ACL_MIB_CNT         (CORAL_ACL_BASE + 0x38)
#define CORAL_ACL_TRTCM           (CORAL_REG_ARL_BASE_ADDRESS + 0x100)
#define CORAL_ACL_TRTCMA          (CORAL_REG_ARL_BASE_ADDRESS + 0x104)
#define CORAL_ACL_TRTCM_CBS_WDATA (CORAL_REG_ARL_BASE_ADDRESS + 0x108)
#define CORAL_ACL_TRTCM_EBS_WDATA (CORAL_REG_ARL_BASE_ADDRESS + 0x10C)
#define CORAL_ACL_TRTCM_CIR_WDATA (CORAL_REG_ARL_BASE_ADDRESS + 0x110)
#define CORAL_ACL_TRTCM_EIR_WDATA (CORAL_REG_ARL_BASE_ADDRESS + 0x114)
#define CORAL_ACL_TRTCM_CBS_RDATA (CORAL_REG_ARL_BASE_ADDRESS + 0x118)
#define CORAL_ACL_TRTCM_EBS_RDATA (CORAL_REG_ARL_BASE_ADDRESS + 0x11C)
#define CORAL_ACL_TRTCM_CIR_RDATA (CORAL_REG_ARL_BASE_ADDRESS + 0x120)
#define CORAL_ACL_TRTCM_EIR_RDATA (CORAL_REG_ARL_BASE_ADDRESS + 0x124)
#define CORAL_ACLRMC              (CORAL_REG_ARL_BASE_ADDRESS + 0x470)
#define CORAL_ACLRMD1             (CORAL_REG_ARL_BASE_ADDRESS + 0x474)
#define CORAL_ACLRMD2             (CORAL_REG_ARL_BASE_ADDRESS + 0x478)

#define CORAL_ACL_EN_MASK                  (0x1)
#define CORAL_ACL_PORT_BITMASK             (0x7ff)
#define CORAL_ACL_MEM_CFG_DONE_OFFSET      (31)
#define CORAL_ACL_MEM_CFG_RULE_ID_OFFSET   (16)
#define CORAL_ACL_MEM_CFG_TCAM_CELL_OFFSET (12)
#define CORAL_ACL_MEM_CFG_DATA_BN_OFFSET   (8)
#define CORAL_ACL_MEM_CFG_MEM_SEL_OFFSET   (4)
#define CORAL_ACL_MEM_CFG_FUNC_SEL_OFFSET  (1)
#define CORAL_ACL_MEM_CFG_EN               (1)
#define CORAL_ACL_ACT_GROUP_END_0_OFFSET   (7)
#define CORAL_ACL_ACT_GROUP_END_1_OFFSET   (15)
#define CORAL_ACL_ACT_GROUP_END_2_OFFSET   (21)
#define CORAL_ACL_LAST_LINE_0_OFFSET       (0)
#define CORAL_ACL_LAST_LINE_1_OFFSET       (8)
#define CORAL_ACL_LAST_LINE_2_OFFSET       (16)
#define CORAL_ACL_LAST_LINE_3_OFFSET       (24)
#define CORAL_ACL_LAST_LINE_MASK           (0x1f)
#define CORAL_ACL_MIB_SEL_OFFSET           (4)
#define CORAL_ACL_MIB_CLEAR                (1)
#define CORAL_ACL_MIB_SEL_MASK             (0x3f)
#define CORAL_ACL_TRTCM_EN_OFFSET          (31)
#define CORAL_ACL_TRTCM_BUSY_OFFSET        (31)
#define CORAL_ACL_TRTCM_WRITE              (1U << 27)
#define CORAL_ACL_TRTCM_READ               (0U << 27)
#define CORAL_ACL_TRTCM_ID_OFFSET          (0)
#define CORAL_ACL_TRTCM_ID_MASK            (0x1f)
#define CORAL_ACL_TRTCM_CBS_OFFSET         (0)
#define CORAL_ACL_TRTCM_CBS_MASK           (0x3ffff)
#define CORAL_ACL_TRTCM_EBS_OFFSET         (0)
#define CORAL_ACL_TRTCM_EBS_MASK           (0x3ffff)
#define CORAL_ACL_TRTCM_CIR_OFFSET         (0)
#define CORAL_ACL_TRTCM_CIR_MASK           (0x3ffff)
#define CORAL_ACL_TRTCM_EIR_OFFSET         (0)
#define CORAL_ACL_TRTCM_EIR_MASK           (0x3ffff)
#define CORAL_ACL_RATE_BUSY_OFFSET         (31)
#define CORAL_ACL_RATE_WRITE               (1U << 30)
#define CORAL_ACL_RATE_READ                (0U << 30)
#define CORAL_ACL_RATE_ID_OFFSET           (20)
#define CORAL_ACL_RATE_ID_MASK             (0x1f)
#define CORAL_ACL_RATE_EN_OFFSET           (19)
#define CORAL_ACL_RATE_EN                  (1U << 19)
#define CORAL_ACL_RATE_DIS                 (0U << 19)
#define CORAL_ACL_RATE_TOKEN_MASK          (0xffff)

#define CORAL_ACL_UDF_BASE (CORAL_REG_ARL_BASE_ADDRESS + 0x200)
#define CORAL_ACL_AUTC     (CORAL_ACL_UDF_BASE + 0x00)
#define CORAL_ACL_AUTW0    (CORAL_ACL_UDF_BASE + 0x08)
#define CORAL_ACL_AUTW1    (CORAL_ACL_UDF_BASE + 0x0c)
#define CORAL_ACL_AUTW2    (CORAL_ACL_UDF_BASE + 0x10)
#define CORAL_ACL_AUTR0    (CORAL_ACL_UDF_BASE + 0x20)
#define CORAL_ACL_AUTR1    (CORAL_ACL_UDF_BASE + 0x24)
#define CORAL_ACL_AUTR2    (CORAL_ACL_UDF_BASE + 0x28)

#define CORAL_ACL_UDF_ACC_OFFSET (31)
#define CORAL_ACL_UDF_READ_MASK  (0x0)
#define CORAL_ACL_UDF_WRITE_MASK (0x1)
#define CORAL_ACL_UDF_CLEAR_MASK (0x2)
#define CORAL_ACL_UDF_CMD_OFFSET (28)
#define CORAL_ACL_UDF_READ       (CORAL_ACL_UDF_READ_MASK << CORAL_ACL_UDF_CMD_OFFSET)
#define CORAL_ACL_UDF_WRITE      (CORAL_ACL_UDF_WRITE_MASK << CORAL_ACL_UDF_CMD_OFFSET)
#define CORAL_ACL_UDF_CLEAR      (CORAL_ACL_UDF_CLEAR_MASK << CORAL_ACL_UDF_CMD_OFFSET)
#define CORAL_ACL_UDF_ADDR_MASK  (0xf)

/* Register of DPCR */
#define CORAL_BMU_PORT_BASE          (0x10204000)
#define CORAL_DPCR_COLOR_OFFSET      (0x20)
#define CORAL_DPCR_QUEUE_OFFSET      (0x4)
#define CORAL_FPC_RXCTRL(p)          (0x10218000 + (p * CORAL_PORT_CTRL_PORT_OFFSET) + 0x04)
#define CORAL_FPC_RXCTRL_FP_CNT_OFFT (0)
#define CORAL_FPC_RXCTRL_FP_CNT_LENG (3)
#define CORAL_DPCR_EN(p)             (CORAL_BMU_PORT_BASE + (p * CORAL_PORT_CTRL_PORT_OFFSET) + 0x08)
#define CORAL_DPCR_BASE              (CORAL_BMU_PORT_BASE + 0x10)
#define CORAL_DPCR(p, c, q)          (CORAL_DPCR_BASE + (p * CORAL_PORT_CTRL_PORT_OFFSET) + (c * CORAL_DPCR_COLOR_OFFSET) + (q * CORAL_DPCR_QUEUE_OFFSET))

#define CORAL_DPCR_HIGH_THRSH_OFFSET (11)
#define CORAL_DPCR_PBB_OFFSET        (22)
#define CORAL_DPCR_LOW_THRSH_WIDTH   (0x7ff)
#define CORAL_DPCR_HIGH_THRSH_WIDTH  (0x7ff)
#define CORAL_DPCR_PBB_WIDTH         (0x3ff)
#define CORAL_DP_MFRM_EX_OFFSET      (24)
/*Register of Min-Max shaper value*/
/*SCH perport base addr*/
#define CORAL_REG_SCH_PORT_ADDRESS (CORAL_REG_ARL_BASE_ADDRESS + 0xc000)

#define CORAL_MMSCR0_Q0(p) (CORAL_REG_SCH_PORT_ADDRESS + CORAL_PORT_CTRL_PORT_OFFSET * (p))
#define CORAL_MMSCR1_Q0(p) (CORAL_REG_SCH_PORT_ADDRESS + CORAL_PORT_CTRL_PORT_OFFSET * (p) + 0x4)
#define CORAL_MMSCR0_Q1(p) (CORAL_REG_SCH_PORT_ADDRESS + CORAL_PORT_CTRL_PORT_OFFSET * (p) + 0x8)
#define CORAL_MMSCR1_Q1(p) (CORAL_REG_SCH_PORT_ADDRESS + CORAL_PORT_CTRL_PORT_OFFSET * (p) + 0xc)
#define CORAL_MMSCR0_Q2(p) (CORAL_REG_SCH_PORT_ADDRESS + CORAL_PORT_CTRL_PORT_OFFSET * (p) + 0x10)
#define CORAL_MMSCR1_Q2(p) (CORAL_REG_SCH_PORT_ADDRESS + CORAL_PORT_CTRL_PORT_OFFSET * (p) + 0x14)
#define CORAL_MMSCR0_Q3(p) (CORAL_REG_SCH_PORT_ADDRESS + CORAL_PORT_CTRL_PORT_OFFSET * (p) + 0x18)
#define CORAL_MMSCR1_Q3(p) (CORAL_REG_SCH_PORT_ADDRESS + CORAL_PORT_CTRL_PORT_OFFSET * (p) + 0x1c)
#define CORAL_MMSCR0_Q4(p) (CORAL_REG_SCH_PORT_ADDRESS + CORAL_PORT_CTRL_PORT_OFFSET * (p) + 0x20)
#define CORAL_MMSCR1_Q4(p) (CORAL_REG_SCH_PORT_ADDRESS + CORAL_PORT_CTRL_PORT_OFFSET * (p) + 0x24)
#define CORAL_MMSCR0_Q5(p) (CORAL_REG_SCH_PORT_ADDRESS + CORAL_PORT_CTRL_PORT_OFFSET * (p) + 0x28)
#define CORAL_MMSCR1_Q5(p) (CORAL_REG_SCH_PORT_ADDRESS + CORAL_PORT_CTRL_PORT_OFFSET * (p) + 0x2c)
#define CORAL_MMSCR0_Q6(p) (CORAL_REG_SCH_PORT_ADDRESS + CORAL_PORT_CTRL_PORT_OFFSET * (p) + 0x30)
#define CORAL_MMSCR1_Q6(p) (CORAL_REG_SCH_PORT_ADDRESS + CORAL_PORT_CTRL_PORT_OFFSET * (p) + 0x34)
#define CORAL_MMSCR0_Q7(p) (CORAL_REG_SCH_PORT_ADDRESS + CORAL_PORT_CTRL_PORT_OFFSET * (p) + 0x38)
#define CORAL_MMSCR1_Q7(p) (CORAL_REG_SCH_PORT_ADDRESS + CORAL_PORT_CTRL_PORT_OFFSET * (p) + 0x3c)

/* Register of serial LED control */
#define CORAL_SLED_CTRL0 (0x10283024) /* FIXME check correctness 1358 to 1495 */
#define CORAL_SLED_CTRL1 (0x10283028)
/* Per port LED control b[23..8] */
#define CORAL_SLED_SRC_SEL         (0x1028302c)
#define CORAL_SLED_FLASH_SET_CTRL0 (0x10283030)
#define CORAL_SLED_FLASH_SET_CTRL1 (0x10283034)
#define CORAL_SLED_FLASH_SET_CTRL2 (0x10283038)
#define CORAL_SLED_FLASH_SET_CTRL3 (0x1028303c)

/* fields of serial LED control register */
#define CORAL_SLED_SOURCE_NORMAL_MODE       (0)
#define CORAL_SLED_SOURCE_INTERLEAVING_MODE (1 << 0)
#define CORAL_SLED_NUM_LED0                 (1 << 1)
#define CORAL_SLED_NUM_LED0_LED1            (2 << 1)
#define CORAL_SLED_NUM_LED0_LED1_LED2       (3 << 1)
#define CORAL_SLED_OUTPUT_TRANSITION_MODE   (0)
#define CORAL_SLED_OUTPUT_CONTINUOUS_MODE   (1 << 3)
#define CORAL_SLED_FALLING_EDGE             (0)
#define CORAL_SLED_RISING_EDGE              (1 << 4)

/* Register of parallel LED control */
#define CORAL_RG_GPIO_L_INV_REG           (0x1000000C)
#define CORAL_RG_GPIO_LED_SEL(gpio)       (0x1000001C + (((gpio) / 4) * 4))
#define CORAL_RG_GPIO_LED_MASK(gpio)      (0xFF << (((gpio) % 4) * 8))
#define CORAL_RG_GPIO_LED_VAL(gpio, data) (((data) & 0xFF) << (((gpio) % 4) * 8))
#define CORAL_RG_GPIO_EN_REG              (0x1000007C)
#define CORAL_RG_GPIO_INVERSE             (0x1000000C)

/* GPIO flash map config*/
#define CORAL_RG_GPIO_FLASH_MODE_CFG (0x1000a334)
#define CORAL_RG_GPIO_RSP_MODE_CFG   (0x1000a338)
#define CORAL_RG_GPIO_FLASH_PRD_SET0 (0x1000a33c)
#define CORAL_RG_GPIO_FLASH_PRD_SET1 (0x1000a340)
#define CORAL_RG_GPIO_FLASH_PRD_SET2 (0x1000a344)
#define CORAL_RG_GPIO_FLASH_PRD_SET3 (0x1000a348) /* period 7 & 6 */

#define CORAL_RG_GPIO_FLASH_MAP_CFG0 (0x1000a34c)
#define CORAL_RG_GPIO_FLASH_MAP_CFG1 (0x1000a350) /* map 12,13,13,15 */
#define CORAL_RG_CYCLE_CFG_VALUE0    (0x1000a398)
#define CORAL_RG_CYCLE_CFG_VALUE1    (0x1000a39C)

#define CORAL_GPIO_WAVE_ACTIVE_LOW  (0x000000ff)
#define CORAL_GPIO_WAVE_ACTIVE_HIGH (0x00ff0000)

#define CORAL_GPIO_WAVE_LED_ON  (0xeeee0000)
#define CORAL_GPIO_WAVE_LED_OFF (0xffff0000)

/**************************************** SIF MODULE *****************************************/
/* HW Trap Normal Mode Read Back Register, used for I2C Mode */
#define CORAL_REG_RGS_CPU_EN (0x100000A8UL)

/* I2C Master Register Base */
#define CORAL_REG_SIF_MASTER0_BASE_ADDRESS (0x10008000UL)
#define CORAL_REG_SIF_AUTO_CTRL            (0xA0UL)
#define CORAL_AUTOMODE_EN_BIT              (31UL)
#define CORAL_AUTOMODE_EN_MSK              (0x1UL)

/* I2C Master Register Offset */
#define CORAL_SIF_SIFMCTL0 (0x40UL)
#define CORAL_SIF_SIFMCTL1 (0x44UL)
#define CORAL_SIF_SIFMD0   (0x50UL)
#define CORAL_SIF_SIFMD1   (0x54UL)

/* SIFM Configuration Register 0 Mask */
#define CORAL_SIF_EN_MSK        (1UL)
#define CORAL_SIF_SDA_STATE_MSK (1UL)
#define CORAL_SIF_SCL_STATE_MSK (1UL)
#define CORAL_SIF_CLK_DIV_MSK   (0xfffUL)

/* SIFM Configuration Register 1 Mask */
#define CORAL_SIF_TRI_MSK   (1UL)
#define CORAL_SIF_MODE_MSK  (0x7UL)
#define CORAL_SIF_PGLEN_MSK (0x7UL)
#define CORAL_SIF_ACK_MSK   (0xffUL)

/* HW Trap Normal Mode Bit */
#define CORAL_CPU_I2C0_MODE_BIT (4UL)

/* SIFM Configuration Register 0 Bit Position */
#define CORAL_SIF_EN_BIT        (1UL)
#define CORAL_SIF_SDA_STATE_BIT (2UL)
#define CORAL_SIF_SCL_STATE_BIT (3UL)
#define CORAL_SIF_CLK_DIV_BIT   (16UL)

/* SIFM Configuration Register 1 Bit Position */
#define CORAL_SIF_TRI_BIT   (0UL)
#define CORAL_SIF_MODE_BIT  (4UL)
#define CORAL_SIF_PGLEN_BIT (8UL)
#define CORAL_SIF_ACK_BIT   (16UL)

/* SIFM Configuration Register 0 Shifted Mask */
#define CORAL_SIF_EN_SM        ((CORAL_SIF_EN_MSK) << (CORAL_SIF_EN_BIT))
#define CORAL_SIF_SDA_STATE_SM ((CORAL_SIF_SDA_STATE_MSK) << (CORAL_SIF_SDA_STATE_BIT))
#define CORAL_SIF_SCL_STATE_SM ((CORAL_SIF_SCL_STATE_MSK) << (CORAL_SIF_SCL_STATE_BIT))
#define CORAL_SIF_CLK_DIV_SM   ((CORAL_SIF_CLK_DIV_MSK) << (CORAL_SIF_CLK_DIV_BIT))

/* SIFM Configuration Register 1 Mask */
#define CORAL_SIF_TRI_SM   ((CORAL_SIF_TRI_MSK) << (CORAL_SIF_TRI_BIT))
#define CORAL_SIF_MODE_SM  ((CORAL_SIF_MODE_MSK) << (CORAL_SIF_MODE_BIT))
#define CORAL_SIF_PGLEN_SM ((CORAL_SIF_PGLEN_MSK) << (CORAL_SIF_PGLEN_BIT))
#define CORAL_SIF_ACK_SM   ((CORAL_SIF_ACK_MSK) << (CORAL_SIF_ACK_BIT))

/**************************************** SIF MODULE *****************************************/

/**************************************** PERIPHERAL *****************************************/
/* peripheral register definition */
#define CORAL_REG_GPIO0_MODE          (0x10006000UL)
#define CORAL_REG_GPIO8_MODE          (0x10006004UL)
#define CORAL_REG_GPIO16_MODE         (0x10006008UL)
#define CORAL_REG_HWTRAP2IOMUX_BYPASS (0x10006010UL)

#define CORAL_REG_HWTRAP (0x10000044UL)

#define CORAL_GPIO19_MODE_SCL (3UL)
#define CORAL_GPIO20_MODE_SDA (3UL)

#define CORAL_PIN_SCL (19UL)
#define CORAL_PIN_SDA (20UL)

#define CORAL_PINCTRL_GROUP_SIZE  (8UL)
#define CORAL_PINCTRL_FIELD_WIDTH (4UL)
#define CORAL_PINCTRL_FIELD_MSK   (0xFUL)
#define CORAL_PINCTRL_PINx_OFS(x) (((x % CORAL_PINCTRL_GROUP_SIZE) * CORAL_PINCTRL_FIELD_WIDTH))

/* GPIO Register definition */
#define CORAL_REG_GPIOCTRL  (0x1000A300UL)
#define CORAL_REG_GPIOCTRL1 (0x1000A320UL)

#define CORAL_REG_GPIODATA (0x1000A304UL)

#define CORAL_REG_GPIOOE (0x1000A314UL)

#define CORAL_REG_GPIOINT (0x1000A308UL)

#define CORAL_REG_GPIOINTEDG  (0x1000A30CUL)
#define CORAL_REG_GPIOINTEDG1 (0x1000A380UL)

#define CORAL_REG_GPIOINTLVL  (0x1000A310UL)
#define CORAL_REG_GPIOINTLVL1 (0x1000A38CUL)

#define CORAL_REG_GPIO_AUX_CFG(gpio, data) (((data) & 0xF) << (((gpio) % 8) * 4))
#define CORAL_REG_GPIO_MODE_SEL(gpio)      (CORAL_REG_GPIO0_MODE + (((gpio) / 8) * 4))
/**************************************** PERIPHERAL *****************************************/
#define CORAL_REG_BGPOR_CTRL1        (0x10000124UL)
#define CORAL_REG_CLK_CPU_ICG_ENABLE (0x10005034UL)
#define CORAL_REG_HUID_HIGH          (0x1000A5B4UL)
#define CORAL_REG_HUID_LOW           (0x1000A5B0UL)

#define CORAL_REG_IO_CFG0 (0x1000A700UL)
#define CORAL_REG_IO_CFG1 (0x1000A710UL)
#define CORAL_REG_IO_CFG2 (0x1000A720UL)

#define CORAL_REG_IO_SMI_BITS  (0x3F000000UL)
#define CORAL_REG_IO_I2C_BIT19 (0x38000000UL)
#define CORAL_REG_IO_I2C_BIT20 (0x7UL)

/* MACRO FUNCTION DECLARATIONS
 */

/* DATA TYPE DECLARATIONS
 */

/* EXPORTED SUBPROGRAM SPECIFICATIONS
 */

#endif /* HAL_CORAL_REG_H */
