################################################################################
include $(AIR_MW_SYSTEM)/config.mk

################################################################################
# IPV6
AIR_SUPPORT_IPV6                        = ENABLED
# SNMP
AIR_SUPPORT_SNMP                        = ENABLED
# ICMP CLIENT
AIR_SUPPORT_ICMP_CLIENT                 = ENABLED
# VLAN
AIR_SUPPORT_VOICE_VLAN                  = ENABLED
AIR_SUPPORT_VOVLAN_SECURITY             = DISABLED
AIR_SUPPORT_SURVEILLANCE_VLAN           = ENABLED
# IGMP SNOOPING
AIR_SUPPORT_IGMP_SNP                    = ENABLED
AIR_SUPPORT_IGMPV3_AWARE                = ENABLED
AIR_SUPPORT_IGMP_SNP_QUERIER            = ENABLED
AIR_SUPPORT_IGMP_SNP_QUERIER_IGMPV3     = DISABLED
AIR_SUPPORT_PIM_AWARE                   = ENABLED
AIR_SUPPORT_IGMP_SNP_SEARCH_MAC_TABLE   = ENABLED
# LOOP PREVENTION
AIR_SUPPORT_LP                          = ENABLED
# DHCP SNOOPING
AIR_SUPPORT_DHCP_SNOOP                  = ENABLED
# RSTP
AIR_SUPPORT_RSTP                        = ENABLED
# RSTP_SECURITY
AIR_SUPPORT_RSTP_SECURITY               = ENABLED
# MSTP
AIR_SUPPORT_MSTP                        = ENABLED
# LLDP
AIR_SUPPORT_LLDPD                       = ENABLED
# POE
AIR_SUPPORT_POE                         = ENABLED
AIR_SUPPORT_POE_WATCHDOG                = ENABLED
# SFP
AIR_SUPPORT_SFP                         = ENABLED
AIR_SUPPORT_SFP_WITH_THREAD             = ENABLED
AIR_SUPPORT_SFP_DDM                     = ENABLED
# MQTTD
AIR_SUPPORT_MQTTD                       = DISABLED
AIR_SUPPORT_MQTTD_STARTONBOOT           = DISABLED
# CABLE DIAG
AIR_SUPPORT_CABLE_DIAG                  = ENABLED
# SNTP
AIR_SUPPORT_SNTP                        = ENABLED
# ERPS
AIR_SUPPORT_ERPS                        = ENABLED
# Second NETIF
AIR_SUPPORT_SECOND_NETIF                = DISABLED
# Management VLAN
AIR_SUPPORT_MGMT_VLAN_CFG               = ENABLED
# HTTP Server
AIR_SUPPORT_HTTPD                       = ENABLED
# HTTP security
AIR_SUPPORT_HTTPD_SECURE                = ENABLED
# REMOTE DEBUG
AIR_SUPPORT_REMOTE_DEBUG                = ENABLED
# TELNET
AIR_SUPPORT_TELNET                      = ENABLED
# SSH
AIR_SUPPORT_SSH                         = ENABLED

export AIR_SUPPORT_IPV6 AIR_SUPPORT_SNMP AIR_SUPPORT_ICMP_CLIENT
export AIR_SUPPORT_VOICE_VLAN AIR_SUPPORT_VOVLAN_SECURITY AIR_SUPPORT_SURVEILLANCE_VLAN
export AIR_SUPPORT_IGMP_SNP AIR_SUPPORT_IGMPV3_AWARE AIR_SUPPORT_IGMP_SNP_QUERIER
export AIR_SUPPORT_IGMP_SNP_QUERIER_IGMPV3 AIR_SUPPORT_PIM_AWARE AIR_SUPPORT_IGMP_SNP_SEARCH_MAC_TABLE
export AIR_SUPPORT_LP AIR_SUPPORT_DHCP_SNOOP AIR_SUPPORT_RSTP AIR_SUPPORT_MSTP AIR_SUPPORT_RSTP_SECURITY AIR_SUPPORT_LLDPD
export AIR_SUPPORT_POE AIR_SUPPORT_POE_WATCHDOG
export AIR_SUPPORT_SFP AIR_SUPPORT_SFP_WITH_THREAD AIR_SUPPORT_SFP_DDM
export AIR_SUPPORT_MQTTD AIR_SUPPORT_MQTTD_STARTONBOOT
export AIR_SUPPORT_CABLE_DIAG
export AIR_SUPPORT_SNTP
export AIR_SUPPORT_ERPS
export AIR_SUPPORT_SECOND_NETIF
export AIR_SUPPORT_MGMT_VLAN_CFG
export AIR_SUPPORT_HTTPD AIR_SUPPORT_HTTPD_SECURE
export AIR_SUPPORT_REMOTE_DEBUG
export AIR_SUPPORT_TELNET
export AIR_SUPPORT_SSH
