subdir-$(CONFIG_GPIO) += gpio/
subdir-$(CONFIG_I2C) += i2c/
subdir-$(CONFIG_PDMA) += pdma/
subdir-$(CONFIG_SLED) += sled/
subdir-$(CONFIG_SPI) += spi/
subdir-$(CONFIG_TIMER) += timer/
subdir-$(CONFIG_UART) += uart/
subdir-$(CONFIG_PINCTRL) += pinctrl/