/*******************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of Airoha Technology Corp. (C) 2021
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("AIROHA SOFTWARE")
*  RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE AIROHA SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. AIROHA SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY AIROHA SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE AIROHA SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT AIROHA'S OPTION, TO REVISE OR REPLACE THE AIROHA SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*******************************************************************************/

/* FILE NAME:   product_ref.h
 * PURPOSE:
 *      Define the initialization in AIR Magic Wand system.
 * NOTES:
 */

#ifndef MW_PRODUCT_REF_H
#define MW_PRODUCT_REF_H

/* INCLUDE FILE DECLARATIONS
 */

/* NAMING CONSTANT DECLARATIONS
 */
#define MW_PRODUCT_ID_DEFAULT       (MW_PRODUCT_ID_AN8855M_5P_AN8801SB_1P)

#define MW_PRODUCT_ID_EN8851C_MAX   (16)
#define MW_PRODUCT_ID_EN8851C_START (0)
#define MW_PRODUCT_ID_EN8851C_END   (MW_PRODUCT_ID_EN8851C_START + MW_PRODUCT_ID_EN8851C_MAX - 1)

#define MW_PRODUCT_ID_EN8853C_MAX   (32)
#define MW_PRODUCT_ID_EN8853C_START (MW_PRODUCT_ID_EN8851C_END + 1)
#define MW_PRODUCT_ID_EN8853C_END   (MW_PRODUCT_ID_EN8853C_START + MW_PRODUCT_ID_EN8853C_MAX - 1)

#define MW_PRODUCT_ID_AN8855M_MAX   (16)
#define MW_PRODUCT_ID_AN8855M_START (MW_PRODUCT_ID_EN8853C_END + 1)
#define MW_PRODUCT_ID_AN8855M_END   (MW_PRODUCT_ID_AN8855M_START + MW_PRODUCT_ID_AN8855M_MAX - 1)

#define MW_PRODUCT_ID_AN8858_MAX    (16)
#define MW_PRODUCT_ID_AN8858_START  (MW_PRODUCT_ID_AN8855M_END + 1)
#define MW_PRODUCT_ID_AN8858_END    (MW_PRODUCT_ID_AN8858_START + MW_PRODUCT_ID_AN8858_MAX - 1)

#define MW_PRODUCT_LIGHTS_DESCRIPTION_MAX_SIZE  (96)
/* MACRO FUNCTION DECLARATIONS
 */

/* DATA TYPE DECLARATIONS
 */
typedef enum
{
    /* EN8851C */
    MW_PRODUCT_ID_EN8851C_8P = MW_PRODUCT_ID_EN8851C_START,
    MW_PRODUCT_ID_EN8851C_RFB,
    MW_PRODUCT_ID_EN8851C_RFB_AN8502_4P,
    MW_PRODUCT_ID_EN8851C_RFB_AN8503_8P,
    MW_PRODUCT_ID_EN8851C_8P_2SFP,
    MW_PRODUCT_ID_EN8851C_8P_2SFP_L,
    /* Add a new product ID for EN8851C above this line. */
    MW_PRODUCT_ID_EN8851C_LAST,

    /* EN8853C */
    MW_PRODUCT_ID_EN8853C_24P = MW_PRODUCT_ID_EN8853C_START,
    MW_PRODUCT_ID_EN8853C_RFB,
    MW_PRODUCT_ID_EN8853C_AN8808Q_RFB,
    MW_PRODUCT_ID_EN8853C_24P_EN8804_4P_4SFP,
    MW_PRODUCT_ID_EN8853C_24P_1SFP,
    MW_PRODUCT_ID_EN8853C_8P_EN8804_4SFP,
    MW_PRODUCT_ID_EN8853C_8P_EN8804_8SFP,
    MW_PRODUCT_ID_EN8853C_8P_EN8804_12SFP,
    MW_PRODUCT_ID_EN8853C_8P_EN8804_16SFP,
    MW_PRODUCT_ID_EN8853C_16P_2SFP,
    /* Add a new product ID for EN8853C above this line. */
    MW_PRODUCT_ID_EN8853C_LAST,

    /* AN8855M */
    MW_PRODUCT_ID_AN8855M_5P = MW_PRODUCT_ID_AN8855M_START,
    MW_PRODUCT_ID_AN8855M_5P_1SFP,
    MW_PRODUCT_ID_AN8855M_5P_1SFP_A,
    MW_PRODUCT_ID_AN8855M_5P_AN8801SB_1P,
    MW_PRODUCT_ID_AN8855M_5P_AN8502_4P,
    /* Add a new product ID for AN8855M above this line. */
    MW_PRODUCT_ID_AN8855M_LAST,

    /* AN8858 */
    MW_PRODUCT_ID_AN8858E_8P = MW_PRODUCT_ID_AN8858_START,
    MW_PRODUCT_ID_AN8858E_8P_AN8503_8P,
    MW_PRODUCT_ID_AN8858C_8P_2SFP,
    MW_PRODUCT_ID_AN8858C_8P_2SFP_A,
    MW_PRODUCT_ID_AN8858B_6P_2SFP,
    MW_PRODUCT_ID_AN8858B_6P_2SFP_A,
    MW_PRODUCT_ID_AN8858H_8P_AN8811B_1P,
    /* Add a new product ID for AN8858 above this line. */
    MW_PRODUCT_ID_AN8858_LAST,

    MW_PRODUCT_ID_LAST = 0xFF
}MW_PRODUCT_ID_T;

typedef struct MW_PRODUCT_ID_INFO_S
{
    C8_T *descp;
    UI8_T id;
}MW_PRODUCT_ID_INFO_T;

typedef struct MW_LIGHTS_ARRAY_S
{
    MW_PRODUCT_ID_T productId;
    char up_row[MW_PRODUCT_LIGHTS_DESCRIPTION_MAX_SIZE];
    char dwn_row[MW_PRODUCT_LIGHTS_DESCRIPTION_MAX_SIZE];
}MW_LIGHTS_ARRAY_T;

/* EXPORTED SUBPROGRAM SPECIFICATIONS
 */
const MW_PRODUCT_ID_INFO_T *
mw_product_getProductIdArray(
    void);

UI32_T
mw_product_getProductIdArraySize(
    void);

const MW_PRODUCT_ID_T
mw_product_getProductId(
    void);

const MW_LIGHTS_ARRAY_T *
mw_product_getLightsArray(
    void);

UI32_T
mw_product_getLightsArraySize(
    void);
#endif

