/* FILE NAME:   hal_pearl_reg.h
 * PURPOSE:
 *      Define the chip registers in AIR SDK.
 * NOTES:
 */

#ifndef PEARL_HAL_PEARL_REG_H
#define PEARL_HAL_PEARL_REG_H

/* INCLUDE FILE DECLARATIONS
 */

/* NAMING CONSTANT DECLARATIONS
 */

/* EN8851 register map perport offset is 0x200 */
#define PEARL_PORT_CTRL_PORT_OFFSET (0x200)

#define PEARL_VTCR_ADDR         (0x10200600)
#define PEARL_VTCR_VID_OFFT     (0)
#define PEARL_VTCR_VID_LENG     (12)
#define PEARL_VTCR_VID_RELMASK  (0x00000FFF)
#define PEARL_VTCR_VID_MASK     (PEARL_VTCR_VID_RELMASK << PEARL_VTCR_VID_OFFT)
#define PEARL_VTCR_FUNC_OFFT    (12)
#define PEARL_VTCR_FUNC_LENG    (4)
#define PEARL_VTCR_FUNC_RELMASK (0x0000000F)
#define PEARL_VTCR_FUNC_MASK    (PEARL_VTCR_FUNC_RELMASK << PEARL_VTCR_FUNC_OFFT)
#define PEARL_VTCR_BUSY_OFFT    (31)
#define PEARL_VTCR_BUSY_LENG    (1)
#define PEARL_VTCR_BUSY_RELMASK (0x00000001)
#define PEARL_VTCR_BUSY_MASK    (PEARL_VTCR_BUSY_RELMASK << PEARL_VTCR_BUSY_OFFT)

#define PEARL_VLNWDATA0 (0x10200604)
#define PEARL_VLNWDATA1 (0x10200608)
#define PEARL_VLNWDATA2 (0x1020060c)
#define PEARL_VLNWDATA3 (0x10200610)
#define PEARL_VLNWDATA4 (0x10200614)
#define PEARL_VLNRDATA0 (0x10200618)
#define PEARL_VLNRDATA1 (0x1020061c)
#define PEARL_VLNRDATA2 (0x10200620)
#define PEARL_VLNRDATA3 (0x10200624)
#define PEARL_VLNRDATA4 (0x10200628)

/* Field of VLAN*/
#define PEARL_VLN_TYPE_MAC_VOICE_SURVEILLANCE_BASE (0 << 1)
#define PEARL_VLN_TYPE_IPV4_BASE                   (1 << 1)
#define PEARL_VLN_TYPE_SELECTIVE_QINQ_BASE         (2 << 1)

/* Field of Selecive QinQ */
#define PEARL_SELECTIVE_QINQ_VLAN_ENTRY_INVAILD (0x0)
#define PEARL_SELECTIVE_QINQ_VLAN_ENTRY_VAILD   (0x1)
#define PEARL_SELECTIVE_QINQ_ETHERTYPE_OFFSET   (4)
#define PEARL_SELECTIVE_QINQ_CVID_OFFSET        (20)
#define PEARL_SELECTIVE_QINQ_CVID_PRI_OFFSET    (0)
#define PEARL_SELECTIVE_QINQ_UNTAG_PKT_OFFSET   (12)
#define PEARL_SELECTIVE_QINQ_SVID_PRI_OFFSET    (13)
#define PEARL_SELECTIVE_QINQ_SVID_OFFSET        (16)

#define PEARL_SELECTIVE_QINQ_ETHERTYPE_LENG (16)
#define PEARL_SELECTIVE_QINQ_CVID_LENG      (12)
#define PEARL_SELECTIVE_QINQ_CVID_PRI_LENG  (3)
#define PEARL_SELECTIVE_QINQ_SVID_LENG      (12)
#define PEARL_SELECTIVE_QINQ_SVID_PRI_LENG  (3)

#define PEARL_SELECTIVE_QINQ_ETHERTYPE_MSK_OFFSET (8)
#define PEARL_SELECTIVE_QINQ_CVID_MSK_OFFSET      (24)
#define PEARL_SELECTIVE_QINQ_CVID_PRI_MSK_OFFSET  (4)

/* Field of MAC-based VLAN*/
#define PEARL_MAC_BASED_VLAN_ENTRY_INVALID  (0x0)
#define PEARL_MAC_BASED_VLAN_ENTRY_VALID    (0x1)
#define PEARL_MAC_BASED_VLAN_MACADDR_OFFSET (4)
#define PEARL_MAC_BASED_VLAN_MACMASK_OFFSET (20)
#define PEARL_MAC_BASED_VLAN_PRI_OFFSET     (26)
#define PEARL_MAC_BASED_VLAN_CVID_OFFSET    (29)

#define PEARL_MAC_BASED_VLAN_MACMASK_LENG   (6)
#define PEARL_MAC_BASED_VLAN_PRI_LENG       (3)
#define PEARL_MAC_BASED_VLAN_MACADDR_L_LENG (28)
#define PEARL_MAC_BASED_VLAN_MACADDR_H_LENG (20)
#define PEARL_MAC_BASED_VLAN_CVID_LENG      (12)
#define PEARL_MAC_BASED_VLAN_CVID_L_LENG    (3)
#define PEARL_MAC_BASED_VLAN_CVID_H_LENG    (9)

/* Field of IPv4-based VLAN */
#define PEARL_IPV4_BASED_VLAN_ENTRY_INVALID (0)
#define PEARL_IPV4_BASED_VLAN_ENTRY_VALID   (1)
#define PEARL_IPV4_BASED_VLAN_IPADDR_OFFSET (4)
#define PEARL_IPV4_BASED_VLAN_IPMASK_OFFSET (4)
#define PEARL_IPV4_BASED_VLAN_PRI_OFFSET    (4)
#define PEARL_IPV4_BASED_VLAN_CVID_OFFSET   (7)

#define PEARL_IPV4_BASED_VLAN_IPADDR_L_LENG (28)
#define PEARL_IPV4_BASED_VLAN_IPADDR_H_LENG (4)
#define PEARL_IPV4_BASED_VLAN_IPMASK_L_LENG (28)
#define PEARL_IPV4_BASED_VLAN_IPMASK_H_LENG (4)
#define PEARL_IPV4_BASED_VLAN_PRI_LENG      (3)
#define PEARL_IPV4_BASED_VLAN_CVID_LENG     (12)

/* Field of IPv6-based VLAN */
#define PEARL_IPV6_BASED_VLAN_ENTRY_INVALID (0)
#define PEARL_IPV6_BASED_VLAN_ENTRY_VALID   (1)
#define PEARL_IPV6_BASED_VLAN_IPADDR_OFFSET (1)
#define PEARL_IPV6_BASED_VLAN_IPMASK_OFFSET (1)
#define PEARL_IPV6_BASED_VLAN_PRI_OFFSET    (9)
#define PEARL_IPV6_BASED_VLAN_CVID_OFFSET   (12)

#define PEARL_IPV6_BASED_VLAN_IPADDR_LENG (31)
#define PEARL_IPV6_BASED_VLAN_IPMASK_LENG (8)
#define PEARL_IPV6_BASED_VLAN_PRI_LENG    (3)
#define PEARL_IPV6_BASED_VLAN_CVID_LENG   (12)

/* Field of Protocol-based VLAN */
#define PEARL_PROTOCOL_BASED_VLAN_ENTRY_INVALID         (0)
#define PEARL_PROTOCOL_BASED_VLAN_ENTRY_VALID           (1)
#define PEARL_PROTOCOL_BASED_VLAN_FRAME_TYPE_OFFSET     (1)
#define PEARL_PROTOCOL_BASED_VLAN_FRAME_TYPE_ETHERNET   (0)
#define PEARL_PROTOCOL_BASED_VLAN_FRAME_TYPE_RFC1042    (1)
#define PEARL_PROTOCOL_BASED_VLAN_FRAME_TYPE_SNAP_OTHER (2)
#define PEARL_PROTOCOL_BASED_VLAN_FRAME_TYPE_LLC_OTHER  (3)
#define PEARL_PROTOCOL_BASED_VLAN_TYPE_VALUE_L_OFFSET   (4)
#define PEARL_PROTOCOL_BASED_VLAN_TYPE_VALUE_H_OFFSET   (0)
#define PEARL_PROTOCOL_BASED_VLAN_GROUP_ID_OFFSET       (12)

#define PEARL_PROTOCOL_BASED_VLAN_FRAME_TYPE_LENG   (3)
#define PEARL_PROTOCOL_BASED_VLAN_TYPE_VALUE_L_LENG (28)
#define PEARL_PROTOCOL_BASED_VLAN_TYPE_VALUE_H_LENG (12)
#define PEARL_PROTOCOL_BASED_VLAN_GROUP_ID_LENG     (2)

/* ARL Register Base */
#define PEARL_REG_ARL_BASE_ADDRESS (0x10200000)

/* Global Control Base */
/* fields of ARL Global Control */
#define PEARL_AGC                      (PEARL_REG_ARL_BASE_ADDRESS + 0x000C)
#define PEARL_CSR_BCSTRM_EXC_MG        (25)
#define PEARL_CSR_LOCAL_EN_OFFT        (7)
#define PEARL_CSR_LOCAL_EN_LENG        (1)
#define PEARL_AGC_MAC_MOVE_EN_OFFT     (28)
#define PEARL_AGC_MAC_MOVE_EN_LENG     (1)
#define PEARL_AGC_ACLRATE_EXC_MG_OFFT  (26)
#define PEARL_AGC_ACLRATE_EXC_MG_LENG  (1)
#define PEARL_AGC_BCSTRM_EXC_MG_OFFT   (25)
#define PEARL_AGC_BCSTRM_EXC_MG_LENG   (1)
#define PEARL_AGC_MAC_OLD_RPLC_HW_OFFT (23)
#define PEARL_AGC_MAC_OLD_RPLC_HW_LENG (1)
#define PEARL_AGC_COMP_BNUM_OFFT       (8)
#define PEARL_AGC_COMP_BNUM_LENG       (7)

/* fields of MAC Forward Control */
#define PEARL_MFC                 (PEARL_REG_ARL_BASE_ADDRESS + 0x0010)
#define PEARL_CSR_CPU_PORT        (8)
#define PEARL_CSR_CPU_PORT_LENGTH (5)
#define PEARL_CSR_CPU_PORT_EN     (15)

/* fields of IGMP Snooping Control */
#define PEARL_ISC               (PEARL_REG_ARL_BASE_ADDRESS + 0x0018)
#define PEARL_ISC_CSR_IGMPV3_EN (1 << 0)

/* fields of IGMP and MLD Message Control */
#define PEARL_IMMC                (PEARL_REG_ARL_BASE_ADDRESS + 0x001C)
#define PEARL_REG_MLD_MANG_OFFT   (30)
#define PEARL_REG_MLD_MANG_LENGTH (1)

#define PEARL_REG_MLD_BPDU_OFFT   (28)
#define PEARL_REG_MLD_BPDU_LENGTH (1)

#define PEARL_REG_MLD_PRI_HIGH_OFFT   (23)
#define PEARL_REG_MLD_PRI_HIGH_LENGTH (1)

#define PEARL_REG_MLD_PORT_FWD_OFFT   (16)
#define PEARL_REG_MLD_PORT_FWD_LENGTH (3)

#define PEARL_REG_IGMP_MANG_OFFT   (14)
#define PEARL_REG_IGMP_MANG_LENGTH (1)

#define PEARL_REG_IGMP_BPDU_OFFT   (12)
#define PEARL_REG_IGMP_BPDU_LENGTH (1)

#define PEARL_REG_IGMP_PRI_HIGH_OFFT   (7)
#define PEARL_REG_IGMP_PRI_HIGH_LENGTH (1)

#define PEARL_REG_IGMP_PORT_FWD_OFFT   (0)
#define PEARL_REG_IGMP_PORT_FWD_LENGTH (3)

/* fields of ARP and PPPoE Control */
#define PEARL_APC                   (PEARL_REG_ARL_BASE_ADDRESS + 0x0020)
#define PEARL_REG_PPPOE_MANG_OFFT   (30)
#define PEARL_REG_PPPOE_MANG_LENGTH (1)

#define PEARL_REG_PPPOE_BPDU_OFFT   (28)
#define PEARL_REG_PPPOE_BPDU_LENGTH (1)

#define PEARL_REG_PPPOE_PRI_HIGH_OFFT   (23)
#define PEARL_REG_PPPOE_PRI_HIGH_LENGTH (1)

#define PEARL_REG_PPPOE_PORT_FWD_OFFT   (16)
#define PEARL_REG_PPPOE_PORT_FWD_LENGTH (3)

#define PEARL_REG_ARP_MANG_OFFT   (14)
#define PEARL_REG_ARP_MANG_LENGTH (1)

#define PEARL_REG_ARP_BPDU_OFFT   (12)
#define PEARL_REG_ARP_BPDU_LENGTH (1)

#define PEARL_REG_ARP_PRI_HIGH_OFFT   (7)
#define PEARL_REG_ARP_PRI_HIGH_LENGTH (1)

#define PEARL_REG_ARP_PORT_FWD_OFFT   (0)
#define PEARL_REG_ARP_PORT_FWD_LENGTH (3)

/* fields of PAE (un-tagged/ tagged) Control */
#define PEARL_PAC                     (PEARL_REG_ARL_BASE_ADDRESS + 0x0024)
#define PEARL_REG_TAG_PAE_MANG_OFFT   (30)
#define PEARL_REG_TAG_PAE_MANG_LENGTH (1)

#define PEARL_REG_TAG_PAE_BPDU_OFFT   (28)
#define PEARL_REG_TAG_PAE_BPDU_LENGTH (1)

#define PEARL_REG_TAG_PAE_PRI_HIGH_OFFT   (23)
#define PEARL_REG_TAG_PAE_PRI_HIGH_LENGTH (1)

#define PEARL_REG_TAG_PAE_PORT_FWD_OFFT   (16)
#define PEARL_REG_TAG_PAE_PORT_FWD_LENGTH (3)

#define PEARL_REG_UTAG_PAE_MANG_OFFT   (14)
#define PEARL_REG_UTAG_PAE_MANG_LENGTH (1)

#define PEARL_REG_UTAG_PAE_BPDU_OFFT   (12)
#define PEARL_REG_UTAG_PAE_BPDU_LENGTH (1)

#define PEARL_REG_UTAG_PAE_PRI_HIGH_OFFT   (7)
#define PEARL_REG_UTAG_PAE_PRI_HIGH_LENGTH (1)

#define PEARL_REG_UTAG_PAE_PORT_FWD_OFFT   (0)
#define PEARL_REG_UTAG_PAE_PORT_FWD_LENGTH (3)

/* fields of REV_01 and REV_02 Control */
#define PEARL_RGAC1                  (PEARL_REG_ARL_BASE_ADDRESS + 0x0028)
#define PEARL_REG_REV_02_MANG_OFFT   (30)
#define PEARL_REG_REV_02_MANG_LENGTH (1)

#define PEARL_REG_REV_02_BPDU_OFFT   (28)
#define PEARL_REG_REV_02_BPDU_LENGTH (1)

#define PEARL_REG_REV_02_PRI_HIGH_OFFT   (23)
#define PEARL_REG_REV_02_PRI_HIGH_LENGTH (1)

#define PEARL_REG_REV_02_PORT_FWD_OFFT   (16)
#define PEARL_REG_REV_02_PORT_FWD_LENGTH (3)

#define PEARL_REG_REV_01_MANG_OFFT   (14)
#define PEARL_REG_REV_01_MANG_LENGTH (1)

#define PEARL_REG_REV_01_BPDU_OFFT   (12)
#define PEARL_REG_REV_01_BPDU_LENGTH (1)

#define PEARL_REG_REV_01_PRI_HIGH_OFFT   (7)
#define PEARL_REG_REV_01_PRI_HIGH_LENGTH (1)

#define PEARL_REG_REV_01_PORT_FWD_OFFT   (0)
#define PEARL_REG_REV_01_PORT_FWD_LENGTH (3)

/* fields of REV_03 and REV_0E Control */
#define PEARL_RGAC2                  (PEARL_REG_ARL_BASE_ADDRESS + 0x002C)
#define PEARL_REG_REV_0E_MANG_OFFT   (30)
#define PEARL_REG_REV_0E_MANG_LENGTH (1)

#define PEARL_REG_REV_0E_BPDU_OFFT   (28)
#define PEARL_REG_REV_0E_BPDU_LENGTH (1)

#define PEARL_REG_REV_0E_PRI_HIGH_OFFT   (23)
#define PEARL_REG_REV_0E_PRI_HIGH_LENGTH (1)

#define PEARL_REG_REV_0E_PORT_FWD_OFFT   (16)
#define PEARL_REG_REV_0E_PORT_FWD_LENGTH (3)

#define PEARL_REG_REV_03_MANG_OFFT   (14)
#define PEARL_REG_REV_03_MANG_LENGTH (1)

#define PEARL_REG_REV_03_BPDU_OFFT   (12)
#define PEARL_REG_REV_03_BPDU_LENGTH (1)

#define PEARL_REG_REV_03_PRI_HIGH_OFFT   (7)
#define PEARL_REG_REV_03_PRI_HIGH_LENGTH (1)

#define PEARL_REG_REV_03_PORT_FWD_OFFT   (0)
#define PEARL_REG_REV_03_PORT_FWD_LENGTH (3)

/* fields of REV_10 and REV_20 Control */
#define PEARL_RGAC3                  (PEARL_REG_ARL_BASE_ADDRESS + 0x0030)
#define PEARL_REG_REV_20_MANG_OFFT   (30)
#define PEARL_REG_REV_20_MANG_LENGTH (1)

#define PEARL_REG_REV_20_BPDU_OFFT   (28)
#define PEARL_REG_REV_20_BPDU_LENGTH (1)

#define PEARL_REG_REV_20_PRI_HIGH_OFFT   (23)
#define PEARL_REG_REV_20_PRI_HIGH_LENGTH (1)

#define PEARL_REG_REV_20_PORT_FWD_OFFT   (16)
#define PEARL_REG_REV_20_PORT_FWD_LENGTH (3)

#define PEARL_REG_REV_10_MANG_OFFT   (14)
#define PEARL_REG_REV_10_MANG_LENGTH (1)

#define PEARL_REG_REV_10_BPDU_OFFT   (12)
#define PEARL_REG_REV_10_BPDU_LENGTH (1)

#define PEARL_REG_REV_10_PRI_HIGH_OFFT   (7)
#define PEARL_REG_REV_10_PRI_HIGH_LENGTH (1)

#define PEARL_REG_REV_10_PORT_FWD_OFFT   (0)
#define PEARL_REG_REV_10_PORT_FWD_LENGTH (3)

/* fields of REV_21 and REV_UN Control */
#define PEARL_RGAC4                  (PEARL_REG_ARL_BASE_ADDRESS + 0x0034)
#define PEARL_REG_REV_UN_MANG_OFFT   (30)
#define PEARL_REG_REV_UN_MANG_LENGTH (1)

#define PEARL_REG_REV_UN_BPDU_OFFT   (28)
#define PEARL_REG_REV_UN_BPDU_LENGTH (1)

#define PEARL_REG_REV_UN_PRI_HIGH_OFFT   (23)
#define PEARL_REG_REV_UN_PRI_HIGH_LENGTH (1)

#define PEARL_REG_REV_UN_PORT_FWD_OFFT   (16)
#define PEARL_REG_REV_UN_PORT_FWD_LENGTH (3)

#define PEARL_REG_REV_21_MANG_OFFT   (14)
#define PEARL_REG_REV_21_MANG_LENGTH (1)

#define PEARL_REG_REV_21_BPDU_OFFT   (12)
#define PEARL_REG_REV_21_BPDU_LENGTH (1)

#define PEARL_REG_REV_21_PRI_HIGH_OFFT   (7)
#define PEARL_REG_REV_21_PRI_HIGH_LENGTH (1)

#define PEARL_REG_REV_21_PORT_FWD_OFFT   (0)
#define PEARL_REG_REV_21_PORT_FWD_LENGTH (3)

/* fields of PEARL_DHCP v4/v6 Control */
#define PEARL_DHCP                   (PEARL_REG_ARL_BASE_ADDRESS + 0x00A4)
#define PEARL_REG_DHCP_6_MANG_OFFT   (30)
#define PEARL_REG_DHCP_6_MANG_LENGTH (1)

#define PEARL_REG_DHCP_6_BPDU_OFFT   (28)
#define PEARL_REG_DHCP_6_BPDU_LENGTH (1)

#define PEARL_REG_DHCP_6_PRI_HIGH_OFFT   (23)
#define PEARL_REG_DHCP_6_PRI_HIGH_LENGTH (1)

#define PEARL_REG_DHCP_6_PORT_FWD_OFFT   (16)
#define PEARL_REG_DHCP_6_PORT_FWD_LENGTH (3)

#define PEARL_REG_DHCP_4_MANG_OFFT   (14)
#define PEARL_REG_DHCP_4_MANG_LENGTH (1)

#define PEARL_REG_DHCP_4_BPDU_OFFT   (12)
#define PEARL_REG_DHCP_4_BPDU_LENGTH (1)

#define PEARL_REG_DHCP_4_PRI_HIGH_OFFT   (7)
#define PEARL_REG_DHCP_4_PRI_HIGH_LENGTH (1)

#define PEARL_REG_DHCP_4_PORT_FWD_OFFT   (0)
#define PEARL_REG_DHCP_4_PORT_FWD_LENGTH (3)

/* fields of Default Router Port Control */
#define PEARL_DRP (PEARL_REG_ARL_BASE_ADDRESS + 0x00C8)

/* fields of BPDU Control */
#define PEARL_BPC                   (PEARL_REG_ARL_BASE_ADDRESS + 0x00D0)
#define PEARL_REG_TTL_0_MANG_OFFT   (30)
#define PEARL_REG_TTL_0_MANG_LENGTH (1)

#define PEARL_REG_TTL_0_BPDU_OFFT   (28)
#define PEARL_REG_TTL_0_BPDU_LENGTH (1)

#define PEARL_REG_TTL_0_PRI_HIGH_OFFT   (23)
#define PEARL_REG_TTL_0_PRI_HIGH_LENGTH (1)

#define PEARL_REG_TTL_0_PORT_FWD_OFFT   (16)
#define PEARL_REG_TTL_0_PORT_FWD_LENGTH (3)

#define PEARL_REG_BPDU_MANG_OFFT   (14)
#define PEARL_REG_BPDU_MANG_LENGTH (1)

#define PEARL_REG_BPDU_BPDU_OFFT   (12)
#define PEARL_REG_BPDU_BPDU_LENGTH (1)

#define PEARL_REG_BPDU_EG_TAG_OFFT   (9)
#define PEARL_REG_BPDU_EG_TAG_LENGTH (3)

#define PEARL_REG_BPDU_PRI_HIGH_OFFT   (7)
#define PEARL_REG_BPDU_PRI_HIGH_LENGTH (1)

#define PEARL_REG_BPDU_PORT_FWD_OFFT   (0)
#define PEARL_REG_BPDU_PORT_FWD_LENGTH (3)

/* fields of IGMP Query Port Control */
#define PEARL_QRYP (PEARL_REG_ARL_BASE_ADDRESS + 0x00D8)

/* fields of queue setting*/
#define PEARL_PEM1 (PEARL_REG_ARL_BASE_ADDRESS + 0x0048)
#define PEARL_PEM2 (PEARL_REG_ARL_BASE_ADDRESS + 0x004c)
#define PEARL_PEM3 (PEARL_REG_ARL_BASE_ADDRESS + 0x0050)
#define PEARL_PEM4 (PEARL_REG_ARL_BASE_ADDRESS + 0x0054)

#define PEARL_PIM1 (PEARL_REG_ARL_BASE_ADDRESS + 0x0058)
#define PEARL_PIM2 (PEARL_REG_ARL_BASE_ADDRESS + 0x005c)
#define PEARL_PIM3 (PEARL_REG_ARL_BASE_ADDRESS + 0x0060)
#define PEARL_PIM4 (PEARL_REG_ARL_BASE_ADDRESS + 0x0064)
#define PEARL_PIM5 (PEARL_REG_ARL_BASE_ADDRESS + 0x0068)
#define PEARL_PIM6 (PEARL_REG_ARL_BASE_ADDRESS + 0x006c)
#define PEARL_PIM7 (PEARL_REG_ARL_BASE_ADDRESS + 0x0070)

/* fields of PEARL_AAC*/
#define PEARL_AAC                   (PEARL_REG_ARL_BASE_ADDRESS + 0x00A0)
#define PEARL_AAC_AGE_UNIT_OFFSET   (0)
#define PEARL_AAC_AGE_UNIT_LENGTH   (11)
#define PEARL_AAC_AGE_CNT_OFFSET    (12)
#define PEARL_AAC_AGE_CNT_LENGTH    (9)
#define PEARL_AAC_AUTO_FLUSH_OFFSET (28)
#define PEARL_AAC_AUTO_FLUSH_LENGTH (1)

/* fields of ARL Global Security Control */
#define PEARL_AGSC                      (PEARL_REG_ARL_BASE_ADDRESS + 0x00B0)
#define PEARL_AGSC_GLB_SA_CNT_EN_OFFT   (31)
#define PEARL_AGSC_GLB_SA_CNT_EN_LENGTH (1)

#define PEARL_AGSC_GLB_SA_LRN_CNT_OFFT   (16)
#define PEARL_AGSC_GLB_SA_LRN_CNT_LENGTH (12)

#define PEARL_AGSC_GLB_ZERO_SA_LRN_EN_OFFT   (15)
#define PEARL_AGSC_GLB_ZERO_SA_LRN_EN_LENGTH (1)

#define PEARL_AGSC_GLB_MAC_SA_LRN_OFFT   (0)
#define PEARL_AGSC_GLB_MAC_SA_LRN_LENGTH (12)

/* Register of Forwarding Control Base address */
#define PEARL_UNUF   (PEARL_REG_ARL_BASE_ADDRESS + 0x00B4)
#define PEARL_UNMF   (PEARL_REG_ARL_BASE_ADDRESS + 0x00B8)
#define PEARL_BCF    (PEARL_REG_ARL_BASE_ADDRESS + 0x00BC)
#define PEARL_UNIPMF (PEARL_REG_ARL_BASE_ADDRESS + 0x00DC)

/* fields of PEARL_AGDIS */
#define PEARL_AGDIS             (PEARL_REG_ARL_BASE_ADDRESS + 0x00C0)
#define PEARL_AGDIS_PORT_OFFSET (0)
#define PEARL_AGDIS_PORT_LENGTH (32)

/* fields of PEARL_ATC */
#define PEARL_ATC                   (PEARL_REG_ARL_BASE_ADDRESS + 0x0300)
#define PEARL_ATC_MAC_OFFSET        (0)
#define PEARL_ATC_MAC_LENGTH        (3)
#define PEARL_ATC_SAT_OFFSET        (4)
#define PEARL_ATC_SAT_LENGTH        (2)
#define PEARL_ATC_MAT_OFFSET        (7)
#define PEARL_ATC_MAT_LENGTH        (5)
#define PEARL_ATC_ENTRY_HIT_OFFSET  (12)
#define PEARL_ATC_ENTRY_HIT_LENGTH  (4)
#define PEARL_ATC_ADDR_OFFSET       (16)
#define PEARL_ATC_ADDR_LENGTH       (9)
#define PEARL_ATC_SINGLE_HIT_OFFSET (30)
#define PEARL_ATC_SINGLE_HIT_LENGTH (1)
#define PEARL_ATC_BUSY_OFFSET       (31)
#define PEARL_ATC_BUSY_LENGTH       (1)

enum
{
    _PEARL_ATC_CMD_READ = 0,
    _PEARL_ATC_CMD_WRITE,
    _PEARL_ATC_CMD_CLEAN,
    _PEARL_ATC_CMD_SEARCH = 4,
    _PEARL_ATC_CMD_SEARCH_NEXT,
    _PEARL_ATC_CMD_LAST
};

#define PEARL_ATC_CMD_READ        (_PEARL_ATC_CMD_READ << PEARL_ATC_MAC_OFFSET)
#define PEARL_ATC_CMD_WRITE       (_PEARL_ATC_CMD_WRITE << PEARL_ATC_MAC_OFFSET)
#define PEARL_ATC_CMD_CLEAN       (_PEARL_ATC_CMD_CLEAN << PEARL_ATC_MAC_OFFSET)
#define PEARL_ATC_CMD_SEARCH      (_PEARL_ATC_CMD_SEARCH << PEARL_ATC_MAC_OFFSET)
#define PEARL_ATC_CMD_SEARCH_NEXT (_PEARL_ATC_CMD_SEARCH_NEXT << PEARL_ATC_MAC_OFFSET)

enum
{
    _PEARL_ATC_SAT_MAC = 0,
    _PEARL_ATC_SAT_DIP,
    _PEARL_ATC_SAT_SIP,
    _PEARL_ATC_SAT_ADDR,
    _PEARL_ATC_SAT_LAST
};

#define PEARL_ATC_SAT_MAC  (_PEARL_ATC_SAT_MAC << PEARL_ATC_SAT_OFFSET)
#define PEARL_ATC_SAT_DIP  (_PEARL_ATC_SAT_DIP << PEARL_ATC_SAT_OFFSET)
#define PEARL_ATC_SAT_SIP  (_PEARL_ATC_SAT_SIP << PEARL_ATC_SAT_OFFSET)
#define PEARL_ATC_SAT_ADDR (_PEARL_ATC_SAT_ADDR << PEARL_ATC_SAT_OFFSET)

enum
{
    _PEARL_ATC_MAT_ALL = 0,
    _PEARL_ATC_MAT_MAC,
    _PEARL_ATC_MAT_DYNAMIC_MAC,
    _PEARL_ATC_MAT_STATIC_MAC,
    _PEARL_ATC_MAT_DIP,
    _PEARL_ATC_MAT_DIPV4,
    _PEARL_ATC_MAT_DIPV6,
    _PEARL_ATC_MAT_SIP,
    _PEARL_ATC_MAT_SIPV4,
    _PEARL_ATC_MAT_SIPV6,
    _PEARL_ATC_MAT_MAC_BY_VID,
    _PEARL_ATC_MAT_MAC_BY_FID,
    _PEARL_ATC_MAT_MAC_BY_PORT,
    _PEARL_ATC_MAT_SIP_BY_DIPV4,
    _PEARL_ATC_MAT_SIP_BY_SIPV4,
    _PEARL_ATC_MAT_SIP_BY_DIPV6,
    _PEARL_ATC_MAT_SIP_BY_SIPV6,
    _PEARL_ATC_MAT_MAC_BY_LIFETIME_VID,
    _PEARL_ATC_MAT_MAC_BY_LIFETIME_FID,
    _PEARL_ATC_MAT_MAC_BY_LIFETIME_PORT,
    _PEARL_ATC_MAT_LAST
};

#define PEARL_ATC_MAT_MAC                  (_PEARL_ATC_MAT_MAC << PEARL_ATC_MAT_OFFSET)
#define PEARL_ATC_MAT_DYNAMIC_MAC          (_PEARL_ATC_MAT_DYNAMIC_MAC << PEARL_ATC_MAT_OFFSET)
#define PEARL_ATC_MAT_STATIC_MAC           (_PEARL_ATC_MAT_STATIC_MAC << PEARL_ATC_MAT_OFFSET)
#define PEARL_ATC_MAT_DIP                  (_PEARL_ATC_MAT_DIP << PEARL_ATC_MAT_OFFSET)
#define PEARL_ATC_MAT_DIPV4                (_PEARL_ATC_MAT_DIPV4 << PEARL_ATC_MAT_OFFSET)
#define PEARL_ATC_MAT_DIPV6                (_PEARL_ATC_MAT_DIPV6 << PEARL_ATC_MAT_OFFSET)
#define PEARL_ATC_MAT_SIP                  (_PEARL_ATC_MAT_SIP << PEARL_ATC_MAT_OFFSET)
#define PEARL_ATC_MAT_SIPV4                (_PEARL_ATC_MAT_SIPV4 << PEARL_ATC_MAT_OFFSET)
#define PEARL_ATC_MAT_SIPV6                (_PEARL_ATC_MAT_SIPV6 << PEARL_ATC_MAT_OFFSET)
#define PEARL_ATC_MAT_MAC_BY_VID           (_PEARL_ATC_MAT_MAC_BY_VID << PEARL_ATC_MAT_OFFSET)
#define PEARL_ATC_MAT_MAC_BY_FID           (_PEARL_ATC_MAT_MAC_BY_FID << PEARL_ATC_MAT_OFFSET)
#define PEARL_ATC_MAT_MAC_BY_PORT          (_PEARL_ATC_MAT_MAC_BY_PORT << PEARL_ATC_MAT_OFFSET)
#define PEARL_ATC_MAT_SIP_BY_DIPV4         (_PEARL_ATC_MAT_SIP_BY_DIPV4 << PEARL_ATC_MAT_OFFSET)
#define PEARL_ATC_MAT_SIP_BY_SIPV4         (_PEARL_ATC_MAT_SIP_BY_SIPV4 << PEARL_ATC_MAT_OFFSET)
#define PEARL_ATC_MAT_SIP_BY_DIPV6         (_PEARL_ATC_MAT_SIP_BY_DIPV6 << PEARL_ATC_MAT_OFFSET)
#define PEARL_ATC_MAT_SIP_BY_SIPV6         (_PEARL_ATC_MAT_SIP_BY_SIPV6 << PEARL_ATC_MAT_OFFSET)
#define PEARL_ATC_MAT_MAC_BY_LIFETIME_VID  (_PEARL_ATC_MAT_MAC_BY_LIFETIME_VID << PEARL_ATC_MAT_OFFSET)
#define PEARL_ATC_MAT_MAC_BY_LIFETIME_FID  (_PEARL_ATC_MAT_MAC_BY_LIFETIME_FID << PEARL_ATC_MAT_OFFSET)
#define PEARL_ATC_MAT_MAC_BY_LIFETIME_PORT (_PEARL_ATC_MAT_MAC_BY_LIFETIME_PORT << PEARL_ATC_MAT_OFFSET)

#define PEARL_ATC_START_BUSY (0x01 << PEARL_ATC_BUSY_OFFSET)

/* fields of PEARL_ATA1 */
#define PEARL_ATA1                     (PEARL_REG_ARL_BASE_ADDRESS + 0x0304)
#define PEARL_ATA1_MAC_ADDR_MSB_OFFSET (0)
#define PEARL_ATA1_MAC_ADDR_MSB_LENGTH (32)
#define PEARL_ATA1_SAT_ADDR_OFFSET     (0)
#define PEARL_ATA1_SAT_ADDR_LENGTH     (11)
#define PEARL_ATA1_SAT_BANK_OFFSET     (16)
#define PEARL_ATA1_SAT_BANK_LENGTH     (4)

/* fields of PEARL_ATA2 */
#define PEARL_ATA2                     (PEARL_REG_ARL_BASE_ADDRESS + 0x0308)
#define PEARL_ATA2_MAC_AGETIME_OFFSET  (0)
#define PEARL_ATA2_MAC_AGETIME_LENGTH  (9)
#define PEARL_ATA2_MAC_LIFETIME_OFFSET (9)
#define PEARL_ATA2_MAC_LIFETIME_LENGTH (1)
#define PEARL_ATA2_MAC_UNAUTH_OFFSET   (10)
#define PEARL_ATA2_MAC_UNAUTH_LENGTH   (1)
#define PEARL_ATA2_MAC_ADDR_LSB_OFFSET (16)
#define PEARL_ATA2_MAC_ADDR_LSB_LENGTH (16)

/* fields of PEARL_ATA3 */
#define PEARL_ATA3 (PEARL_REG_ARL_BASE_ADDRESS + 0x030C)

/* fields of PEARL_ATA4 */
#define PEARL_ATA4 (PEARL_REG_ARL_BASE_ADDRESS + 0x0310)

/* fields of PEARL_ATA5 */
#define PEARL_ATA5 (PEARL_REG_ARL_BASE_ADDRESS + 0x0314)

/* fields of PEARL_ATA6 */
#define PEARL_ATA6 (PEARL_REG_ARL_BASE_ADDRESS + 0x0318)

/* fields of PEARL_ATA7 */
#define PEARL_ATA7 (PEARL_REG_ARL_BASE_ADDRESS + 0x031C)

/* fields of PEARL_ATA8 */
#define PEARL_ATA8 (PEARL_REG_ARL_BASE_ADDRESS + 0x0320)

/* fields of PEARL_ATWD */
#define PEARL_ATWD                 (PEARL_REG_ARL_BASE_ADDRESS + 0x0324)
#define PEARL_ATWD_MAC_LIVE_OFFSET (0)
#define PEARL_ATWD_MAC_LIVE_LENGTH (1)
#define PEARL_ATWD_MAC_LEAK_OFFSET (1)
#define PEARL_ATWD_MAC_LEAK_LENGTH (1)
#define PEARL_ATWD_MAC_UPRI_OFFSET (2)
#define PEARL_ATWD_MAC_UPRI_LENGTH (3)
#define PEARL_ATWD_MAC_FWD_OFFSET  (5)
#define PEARL_ATWD_MAC_FWD_LENGTH  (3)
#define PEARL_ATWD_MAC_MIR_OFFSET  (8)
#define PEARL_ATWD_MAC_MIR_LENGTH  (4)
#define PEARL_ATWD_MAC_ETAG_OFFSET (12)
#define PEARL_ATWD_MAC_ETAG_LENGTH (3)
#define PEARL_ATWD_MAC_IVL_OFFSET  (15)
#define PEARL_ATWD_MAC_IVL_LENGTH  (1)
#define PEARL_ATWD_MAC_VID_OFFSET  (16)
#define PEARL_ATWD_MAC_VID_LENGTH  (12)
#define PEARL_ATWD_MAC_FID_OFFSET  (28)
#define PEARL_ATWD_MAC_FID_LENGTH  (4)

/* fields of PEARL_ATWD2 */
#define PEARL_ATWD2                 (PEARL_REG_ARL_BASE_ADDRESS + 0x0328)
#define PEARL_ATWD2_MAC_PORT_OFFSET (0)
#define PEARL_ATWD2_MAC_PORT_LENGTH (29)

/* fields of ATWDS */
#define PEARL_ATRDS                (PEARL_REG_ARL_BASE_ADDRESS + 0x0330)
#define PEARL_ATRD0_MAC_SEL_OFFSET (0)
#define PEARL_ATRD0_MAC_SEL_LENGTH (2)

/* fields of PEARL_ATRD0 */
#define PEARL_ATRD0                     (PEARL_REG_ARL_BASE_ADDRESS + 0x0334)
#define PEARL_ATRD0_MAC_LIVE_OFFSET     (0)
#define PEARL_ATRD0_MAC_LIVE_LENGTH     (1)
#define PEARL_ATRD0_MAC_LIFETIME_OFFSET (1)
#define PEARL_ATRD0_MAC_LIFETIME_LENGTH (2)
#define PEARL_ATRD0_MAC_TYPE_OFFSET     (3)
#define PEARL_ATRD0_MAC_TYPE_LENGTH     (2)
#define PEARL_ATRD0_MAC_LEAK_OFFSET     (5)
#define PEARL_ATRD0_MAC_LEAK_LENGTH     (1)
#define PEARL_ATRD0_MAC_UPRI_OFFSET     (6)
#define PEARL_ATRD0_MAC_UPRI_LENGTH     (3)
#define PEARL_ATRD0_MAC_IVL_OFFSET      (9)
#define PEARL_ATRD0_MAC_IVL_LENGTH      (1)
#define PEARL_ATRD0_MAC_VID_OFFSET      (10)
#define PEARL_ATRD0_MAC_VID_LENGTH      (12)
#define PEARL_ATRD0_MAC_ETAG_OFFSET     (22)
#define PEARL_ATRD0_MAC_ETAG_LENGTH     (3)
#define PEARL_ATRD0_MAC_FID_OFFSET      (25)
#define PEARL_ATRD0_MAC_FID_LENGTH      (4)
#define PEARL_ATRD1_MAC_UNAUTH_OFFSET   (31)
#define PEARL_ATRD1_MAC_UNAUTH_LENGTH   (1)

/* fields of PEARL_ATRD1 */
#define PEARL_ATRD1                     (PEARL_REG_ARL_BASE_ADDRESS + 0x0338)
#define PEARL_ATRD1_MAC_FWD_OFFSET      (0)
#define PEARL_ATRD1_MAC_FWD_LENGTH      (3)
#define PEARL_ATRD1_MAC_AGETIME_OFFSET  (3)
#define PEARL_ATRD1_MAC_AGETIME_LENGTH  (9)
#define PEARL_ATRD1_MAC_MIR_OFFSET      (12)
#define PEARL_ATRD1_MAC_MIR_LENGTH      (4)
#define PEARL_ATRD1_MAC_ADDR_LSB_OFFSET (16)
#define PEARL_ATRD1_MAC_ADDR_LSB_LENGTH (16)

/* fields of PEARL_ATRD2 */
#define PEARL_ATRD2                     (PEARL_REG_ARL_BASE_ADDRESS + 0x033C)
#define PEARL_ATRD2_MAC_ADDR_MSB_OFFSET (0)
#define PEARL_ATRD2_MAC_ADDR_MSB_LENGTH (32)

/* fields of PEARL_ATRD3 */
#define PEARL_ATRD3                 (PEARL_REG_ARL_BASE_ADDRESS + 0x0340)
#define PEARL_ATRD3_MAC_PORT_OFFSET (0)
#define PEARL_ATRD3_MAC_PORT_LENGTH (29)

/* fields of PEARL_LOGMACPORT */
#define PEARL_LOGMACPORT             (PEARL_REG_ARL_BASE_ADDRESS + 0x350)
#define PEARL_LOGMACPORT_PORT_OFFSET (0)
#define PEARL_LOGMACPORT_PORT_LENGTH (29)

/* fields of PEARL_LOGMACDATA */
#define PEARL_LOGMACDATA                 (PEARL_REG_ARL_BASE_ADDRESS + 0x354)
#define PEARL_LOGMACDATA_BANK_OFFSET     (0)
#define PEARL_LOGMACDATA_BANK_LENGTH     (4)
#define PEARL_LOGMACDATA_ADDR_OFFSET     (4)
#define PEARL_LOGMACDATA_ADDR_LENGTH     (11)
#define PEARL_LOGMACDATA_PORTMOVE_OFFSET (15)
#define PEARL_LOGMACDATA_PORTMOVE_LENGTH (1)
#define PEARL_LOGMACDATA_REPLACE_OFFSET  (16)
#define PEARL_LOGMACDATA_REPLACE_LENGTH  (1)
#define PEARL_LOGMACDATA_EMPTY_OFFSET    (19)
#define PEARL_LOGMACDATA_EMPTY_LENGTH    (1)
#define PEARL_LOGMACDATA_CNT_OFFSET      (20)
#define PEARL_LOGMACDATA_CNT_LENGTH      (5)
#define PEARL_LOGMACDATA_NEXT_OFFSET     (31)
#define PEARL_LOGMACDATA_NEXT_LENGTH     (1)

/* fields of PEARL_LOGAGEPORT */
#define PEARL_LOGAGEPORT             (PEARL_REG_ARL_BASE_ADDRESS + 0x358)
#define PEARL_LOGAGEPORT_PORT_OFFSET (0)
#define PEARL_LOGAGEPORT_PORT_LENGTH (29)

/* fields of PEARL_LOGAGEDATA0 */
#define PEARL_LOGAGEDATA0              (PEARL_REG_ARL_BASE_ADDRESS + 0x35C)
#define PEARL_LOGAGEDATA0_FID_OFFSET   (0)
#define PEARL_LOGAGEDATA0_FID_LENGTH   (4)
#define PEARL_LOGAGEDATA0_VID_OFFSET   (4)
#define PEARL_LOGAGEDATA0_VID_LENGTH   (12)
#define PEARL_LOGAGEDATA0_IVL_OFFSET   (16)
#define PEARL_LOGAGEDATA0_IVL_LENGTH   (1)
#define PEARL_LOGAGEDATA0_EMPTY_OFFSET (19)
#define PEARL_LOGAGEDATA0_EMPTY_LENGTH (1)
#define PEARL_LOGAGEDATA0_CNT_OFFSET   (20)
#define PEARL_LOGAGEDATA0_CNT_LENGTH   (5)
#define PEARL_LOGAGEDATA0_NEXT_OFFSET  (31)
#define PEARL_LOGAGEDATA0_NEXT_LENGTH  (1)

/* fields of PEARL_LOGAGEDATA1 */
#define PEARL_LOGAGEDATA1 (PEARL_REG_ARL_BASE_ADDRESS + 0x360)

/* fields of PEARL_LOGAGEDATA2 */
#define PEARL_LOGAGEDATA2 (PEARL_REG_ARL_BASE_ADDRESS + 0x364)

/* fields of PEARL_MACLMTC */
#define PEARL_MACLMTC                     (PEARL_REG_ARL_BASE_ADDRESS + 0x0370)
#define PEARL_MACLMTC_LMT_TICK_OFFSET     (0)
#define PEARL_MACLMTC_LMT_TICK_LENGTH     (3)
#define PEARL_MACLMTC_SA_FULL_DROP_OFFSET (4)
#define PEARL_MACLMTC_SA_FULL_DROP_LENGTH (1)
#define PEARL_MACLMTC_PORT_MV_DROP_OFFSET (5)
#define PEARL_MACLMTC_PORT_MV_DROP_LENGTH (1)
#define PEARL_MACLMTC_EXC_MNG_OFFSET      (30)
#define PEARL_MACLMTC_EXC_MNG_LENGTH      (1)
#define PEARL_MACLMTC_EN_OFFSET           (31)
#define PEARL_MACLMTC_EN_LENGTH           (1)

/* fields of PEARL_MACLMTTH */
#define PEARL_MACLMTTH                        (PEARL_REG_ARL_BASE_ADDRESS + 0x0374)
#define PEARL_MACLMTTH_SA_FULL_CPU_THR_OFFSET (0)
#define PEARL_MACLMTTH_SA_FULL_CPU_THR_LENGTH (8)
#define PEARL_MACLMTTH_PORT_MV_CPU_THR_OFFSET (8)
#define PEARL_MACLMTTH_PORT_MV_CPU_THR_LENGTH (8)

/* fields of PEARL_MAUTHC */
#define PEARL_MAUTHC                         (PEARL_REG_ARL_BASE_ADDRESS + 0x03A0)
#define PEARL_MAUTHC_MAC_AUTH_OFFSET         (0)
#define PEARL_MAUTHC_MAC_AUTH_LENGTH         (1)
#define PEARL_MAUTHC_AUTH_FW_OFFSET          (4)
#define PEARL_MAUTHC_AUTH_FW_LENGTH          (2)
#define PEARL_MAUTHC_AUTH_FW_MAC             (0)
#define PEARL_MAUTHC_AUTH_FW_DROP            (2)
#define PEARL_MAUTHC_AUTH_FW_CPU             (3)
#define PEARL_MAUTHC_UNAUTH_FW_OFFSET        (6)
#define PEARL_MAUTHC_UNAUTH_FW_LENGTH        (2)
#define PEARL_MAUTHC_UNAUTH_FW_MAC           (0)
#define PEARL_MAUTHC_UNAUTH_FW_DROP          (2)
#define PEARL_MAUTHC_UNAUTH_FW_CPU           (3)
#define PEARL_MAUTHC_AUTH_PORT_MOVE_OFFSET   (8)
#define PEARL_MAUTHC_AUTH_PORT_MOVE_LENGTH   (1)
#define PEARL_MAUTHC_UNAUTH_PORT_MOVE_OFFSET (9)
#define PEARL_MAUTHC_UNAUTH_PORT_MOVE_LENGTH (1)

/* fields of PEARL_GVMC */
#define PEARL_GVMC             (PEARL_REG_ARL_BASE_ADDRESS + 0x03A8)
#define PEARL_GVMC_GMEM_OFFSET (0)
#define PEARL_GVMC_GMEM_LENGTH (32)

/* fields of ingress and egress rate control */
#define PEARL_IRLCR(p)          (PEARL_REG_ARL_BASE_ADDRESS + (p * PEARL_PORT_CTRL_PORT_OFFSET) + 0x4000)
#define PEARL_ERLCR(p)          (PEARL_REG_ARL_BASE_ADDRESS + (p * PEARL_PORT_CTRL_PORT_OFFSET) + 0xC040)
#define PEARL_REG_RATE_CIR_OFFT (0)
#define PEARL_REG_RATE_CIR_LENG (17)
#define PEARL_REG_TB_EN_OFFT    (19)
#define PEARL_REG_RATE_TB_OFFT  (20)
#define PEARL_REG_RATE_TB_LENG  (4)
#define PEARL_REG_RATE_CBS_OFFT (24)
#define PEARL_REG_RATE_CBS_LENG (7)
#define PEARL_REG_RATE_EN_OFFT  (31)

/* fields of PEARL_SFCR */
#define PEARL_SFCR(p)                  (PEARL_REG_ARL_BASE_ADDRESS + (p * PEARL_PORT_CTRL_PORT_OFFSET) + 0x4070)
#define PEARL_SFLOW_SAMPLING_RATE_OFFT (0)
#define PEARL_SFLOW_SAMPLING_RATE_LENG (24)
#define PEARL_SFLOW_SAMPLING_NUM_OFFT  (24)
#define PEARL_SFLOW_SAMPLING_NUM_LENG  (8)

/* fields of IBCR */
#define PEARL_IBCR(p)                        (PEARL_REG_ARL_BASE_ADDRESS + (p * PEARL_PORT_CTRL_PORT_OFFSET) + 0x40B0)
#define PEARL_REG_IGC_STOP_REFILL_TOKEN_OFFT (8)
#define PEARL_REG_IGC_STOP_REFILL_TOKEN_LENG (4)

/* fields of global ingress and egress rate control */
#define PEARL_GIRLCR               (PEARL_REG_ARL_BASE_ADDRESS + 0x7E24)
#define PEARL_GERLCR               (PEARL_REG_ARL_BASE_ADDRESS + 0xFE00)
#define PEARL_REG_IPG_BYTE_OFFT    (0)
#define PEARL_REG_IPG_BYTE_LENG    (8)
#define PEARL_REG_MFRM_EX_OFFT     (9)
#define PEARL_REG_MFRM_EX_LENG     (1)
#define PEARL_SFLOW_MFRM_EX_OFFT   (25)
#define PEARL_SFLOW_MFRM_EX_LENG   (1)
#define PEARL_L1_RATE_IPG_BYTE_CNT (0x18)
#define PEARL_L2_RATE_IPG_BYTE_CNT (0x04)

/* BMU Global Reg Base */
#define PEARL_BMU_GLOBAL (PEARL_REG_ARL_BASE_ADDRESS + 0x7E00)

/* fields of PEARL_FPLC(Free Page Link Count Register ) */
#define PEARL_FPLC                          (PEARL_BMU_GLOBAL + 0x0)
#define PEARL_FPLC_MIN_FREE_PL_CNT_RST_OFFT (31)
#define PEARL_FPLC_MIN_FREE_PL_CNT_RST_LENG (1)
#define PEARL_FPLC_MIN_FREE_PL_CNT_OFFT     (16)
#define PEARL_FPLC_MIN_FREE_PL_CNT_LENG     (12)
#define PEARL_FPLC_FREE_PL_CNT_OFFT         (0)
#define PEARL_FPLC_FREE_PL_CNT_LENG         (12)

/* fields of PEARL_GFCCR1(Global Flow Control Register1) */
#define PEARL_GFCCR1                  (PEARL_BMU_GLOBAL + 0x8)
#define PEARL_GFCCR1_PORT_BLK_HI_OFFT (16)
#define PEARL_GFCCR1_PORT_BLK_HI_LENG (8)

/* field of l3 unicast routing table */
#define PEARL_RATCR              (PEARL_BMU_GLOBAL + 0x30)
#define PEARL_RATDPL             (PEARL_BMU_GLOBAL + 0x34)
#define PEARL_RATDPH             (PEARL_BMU_GLOBAL + 0x38)
#define PEARL_RAT_SEL_DA_OFFT    (31)
#define PEARL_RAT_SEL_DA_LENG    (1)
#define PEARL_RAT_SEL_WRITE_OFFT (30)
#define PEARL_RAT_SEL_WRITE_LENG (1)
#define PEARL_RAT_ADDR_OFFT      (0)
#define PEARL_RAT_ADDR_DA_LENG   (8)
#define PEARL_RAT_ADDR_SA_LENG   (4)
#define PEARL_RAT_DATA_L_OFFT    (0)
#define PEARL_RAT_DATA_L_LENG    (32)
#define PEARL_RAT_DATA_H_OFFT    (0)
#define PEARL_RAT_DATA_H_LENG    (16)

/* fields of PEARL_PCPCR(Packet/Page Count Probe Control Register) */
#define PEARL_PCPCR                 (PEARL_BMU_GLOBAL + 0x48)
#define PEARL_PCPCR_PACKET_SEL_OFFT (31)
#define PEARL_PCPCR_PACKET_SEL_LENG (1)
#define PEARL_PCPCR_PORT_SEL_OFFT   (8)
#define PEARL_PCPCR_PORT_SEL_LENG   (5)
#define PEARL_PCPCR_QUEUE_SEL_OFFT  (0)
#define PEARL_PCPCR_QUEUE_SEL_LENG  (4)

/* fields of PEARL_PCPSR(Packet/Page Count Probe Statuc Register) */
#define PEARL_PCPSR              (PEARL_BMU_GLOBAL + 0x4C)
#define PEARL_PCPSR_COUNTER_OFFT (0)
#define PEARL_PCPSR_COUNTER_LENG (11)

/* Port Control Base */
#define PEARL_PORT_CTRL_BASE         (0x8000)
#define PEARL_REG_ARL_PORT_BASE_ADDR (PEARL_REG_ARL_BASE_ADDRESS + PEARL_PORT_CTRL_BASE)
#define PEARL_PORT_CTRL_REG(p, r)    (PEARL_PORT_CTRL_BASE + (p) * PEARL_PORT_CTRL_PORT_OFFSET + (r))

#define PEARL_SSC(p) (PEARL_REG_ARL_BASE_ADDRESS + PEARL_PORT_CTRL_REG(p, 0x00))

#define PEARL_PCR(p)                  (PEARL_REG_ARL_BASE_ADDRESS + PEARL_PORT_CTRL_REG(p, 0x04))
#define PEARL_PCR_PORT_VLAN_OFFT      (0)
#define PEARL_PCR_PORT_VLAN_LENG      (2)
#define PEARL_PCR_PORT_VLAN_RELMASK   (0x00000003)
#define PEARL_PCR_PORT_VLAN_MASK      (PEARL_PCR_PORT_VLAN_RELMASK << PEARL_PCR_PORT_VLAN_OFFT)
#define PEARL_PCR_UP_TO_CTAG_PRI_OFFT (11)
#define PEARL_PCR_UP_TO_DSCP_OFFT     (12)
#define PEARL_PCR_PORT_RX_MIR_OFFT    (16)
#define PEARL_PCR_PORT_RX_MIR_LENG    (4)
#define PEARL_PCR_PORT_TX_MIR_OFFT    (20)
#define PEARL_PCR_PORT_TX_MIR_LENG    (4)
#define PEARL_PCR_PORT_PRI_OFFT       (24)
#define PEARL_PCR_PORT_PRI_LENG       (3)
#define PEARL_PCR_PORT_PRI_RELMASK    (0x00000007)
#define PEARL_PCR_PORT_PRI_MASK       (PEARL_PCR_PORT_PRI_RELMASK << PEARL_PCR_PORT_PRI_OFFT)
#define PEARL_PCR_UP_TO_STAG_PRI_OFFT (27)
#define PEARL_PCR_EG_TAG_OFFT         (28)
#define PEARL_PCR_EG_TAG_LENG         (2)
#define PEARL_PCR_EG_TAG_RELMASK      (0x00000003)
#define PEARL_PCR_EG_TAG_MASK         (PEARL_PCR_EG_TAG_RELMASK << PEARL_PCR_EG_TAG_OFFT)

/* fields of PEARL_PIC */
#define PEARL_PIC(p)                         (PEARL_REG_ARL_BASE_ADDRESS + PEARL_PORT_CTRL_REG(p, 0x08))
#define PEARL_PIC_PORT_IGMP_CTRL_CSR_IPM_01  (1 << 8)
#define PEARL_PIC_PORT_IGMP_CTRL_CSR_IPM_33  (1 << 9)
#define PEARL_PIC_PORT_IGMP_CTRL_CSR_IPM_224 (1 << 10)

/* fields of PEARL_PSC */
#define PEARL_PSC(p)                (PEARL_REG_ARL_BASE_ADDRESS + PEARL_PORT_CTRL_REG(p, 0x0C))
#define PEARL_PSC_RX_LOCK_OFFSET    (0)
#define PEARL_PSC_RX_LOCK_LENGTH    (1)
#define PEARL_PSC_DIS_LRN_OFFSET    (4)
#define PEARL_PSC_DIS_LRN_LENGTH    (1)
#define PEARL_PSC_SA_CNT_EN_OFFSET  (5)
#define PEARL_PSC_SA_CNT_EN_LENGTH  (1)
#define PEARL_PSC_SA_CNT_LMT_OFFSET (8)
#define PEARL_PSC_SA_CNT_LMT_LENGTH (12)

#define PEARL_PVC(p)                 (PEARL_REG_ARL_BASE_ADDRESS + PEARL_PORT_CTRL_REG(p, 0x10))
#define PEARL_PVC_ACC_FRM_OFFT       (0)
#define PEARL_PVC_ACC_FRM_LENG       (2)
#define PEARL_PVC_ACC_FRM_RELMASK    (0x00000003)
#define PEARL_PVC_ACC_FRM_MASK       (PEARL_PVC_ACC_FRM_RELMASK << PEARL_PVC_ACC_FRM_OFFT)
#define PEARL_PVC_UC_LKYV_EN_OFFT    (2)
#define PEARL_PVC_UC_LKYV_EN_LENG    (1)
#define PEARL_PVC_UC_LKYV_EN_RELMASK (0x00000001)
#define PEARL_PVC_UC_LKYV_EN_MASK    (PEARL_PVC_UC_LKYV_EN_RELMASK << PEARL_PVC_UC_LKYV_EN_OFFT)
#define PEARL_PVC_MC_LKYV_EN_OFFT    (3)
#define PEARL_PVC_MC_LKYV_EN_LENG    (1)
#define PEARL_PVC_MC_LKYV_EN_RELMASK (0x00000001)
#define PEARL_PVC_MC_LKYV_EN_MASK    (PEARL_PVC_MC_LKYV_EN_RELMASK << PEARL_PVC_MC_LKYV_EN_OFFT)
#define PEARL_PVC_BC_LKYV_EN_OFFT    (4)
#define PEARL_PVC_BC_LKYV_EN_LENG    (1)
#define PEARL_PVC_BC_LKYV_EN_RELMASK (0x00000001)
#define PEARL_PVC_BC_LKYV_EN_MASK    (PEARL_PVC_BC_LKYV_EN_RELMASK << PEARL_PVC_BC_LKYV_EN_OFFT)
#define PEARL_PVC_SPTAG_EN_OFFT      (5)
#define PEARL_PVC_SPTAG_EN_LENG      (1)
#define PEARL_PVC_SPTAG_EN_RELMASK   (0x00000001)
#define PEARL_PVC_SPTAG_EN_MASK      (PEARL_PVC_SPTAG_EN_RELMASK << PEARL_PVC_SPTAG_EN_OFFT)
#define PEARL_PVC_VLAN_ATTR_OFFT     (6)
#define PEARL_PVC_VLAN_ATTR_LENG     (2)
#define PEARL_PVC_VLAN_ATTR_RELMASK  (0x00000003)
#define PEARL_PVC_VLAN_ATTR_MASK     (PEARL_PVC_VLAN_ATTR_RELMASK << PEARL_PVC_VLAN_ATTR_OFFT)
#define PEARL_PVC_EG_TAG_OFFT        (8)
#define PEARL_PVC_EG_TAG_LENG        (3)
#define PEARL_PVC_EG_TAG_RELMASK     (0x00000007)
#define PEARL_PVC_EG_TAG_MASK        (PEARL_PVC_EG_TAG_RELMASK << PEARL_PVC_EG_TAG_OFFT)
#define PEARL_PVC_SPTAG_MODE_OFFT    (11)
#define PEARL_PVC_SPTAG_MODE_LENG    (1)
#define PEARL_PVC_SPTAG_MODE_RELMASK (0x00000001)
#define PEARL_PVC_SPTAG_MODE_MASK    (PEARL_PVC_SPTAG_MODE_RELMASK << PEARL_PVC_SPTAG_MODE_OFFT)
#define PEARL_PVC_STAG_VPID_OFFT     (16)
#define PEARL_PVC_STAG_VPID_LENG     (16)
#define PEARL_PVC_STAG_VPID_RELMASK  (0x0000FFFF)
#define PEARL_PVC_STAG_VPID_MASK     (PEARL_PVC_STAG_VPID_RELMASK << PEARL_PVC_STAG_VPID_OFFT)

#define PEARL_PPBV1(p)                  (PEARL_REG_ARL_BASE_ADDRESS + PEARL_PORT_CTRL_REG(p, 0x14))
#define PEARL_PPBV1_G0_PORT_VID_OFFT    (0)
#define PEARL_PPBV1_G0_PORT_VID_LENG    (12)
#define PEARL_PPBV1_G0_PORT_VID_RELMASK (0x00000FFF)
#define PEARL_PPBV1_G0_PORT_VID_MASK    (PEARL_PPBV1_G0_PORT_VID_RELMASK << PEARL_PPBV1_G0_PORT_VID_OFFT)

#define PEARL_PPBV2(p) (PEARL_REG_ARL_BASE_ADDRESS + PEARL_PORT_CTRL_REG(p, 0x18))
#define PEARL_PUPW(p)  (PEARL_REG_ARL_BASE_ADDRESS + PEARL_PORT_CTRL_REG(p, 0x30))

#define PEARL_EG_TPID(p)                   (PEARL_REG_ARL_BASE_ADDRESS + PEARL_PORT_CTRL_REG(p, 0x40))
#define PEARL_EG_TPID_CSR_ETAG_TPID_0_OFFT (0)
#define PEARL_EG_TPID_CSR_ETAG_TPID_1_OFFT (16)
#define PEARL_EG_TPID_TPID_RELMASK         (0x0000FFFF)
#define PEARL_EG_TPID_TPID_MASK(offt)      (PEARL_EG_TPID_TPID_RELMASK << (offt))

#define PEARL_PVID(p)                 (PEARL_REG_ARL_BASE_ADDRESS + PEARL_PORT_CTRL_REG(p, 0x48))
#define PEARL_PVID_CTAG_VID_OFFT      (0)
#define PEARL_PVID_CTAG_VID_LENG      (12)
#define PEARL_PVID_CTAG_VID_RELMASK   (0x00000FFF)
#define PEARL_PVID_CTAG_PORT_VID_MASK (PEARL_PVID_CTAG_VID_RELMASK << PEARL_PVID_CTAG_VID_OFFT)

#define PEARL_PSVID(p)                 (PEARL_REG_ARL_BASE_ADDRESS + PEARL_PORT_CTRL_REG(p, 0x48))
#define PEARL_PSVID_STAG_VID_OFFT      (16)
#define PEARL_PSVID_STAG_VID_LENG      (12)
#define PEARL_PSVID_STAG_VID_RELMASK   (0x00000FFF)
#define PEARL_PSVID_STAG_PORT_VID_MASK (PEARL_PSVID_STAG_VID_RELMASK << PEARL_PSVID_STAG_VID_OFFT)

#define PEARL_PORTMATRIX(p) (PEARL_REG_ARL_BASE_ADDRESS + PEARL_PORT_CTRL_REG(p, 0x44))

#define PEARL_PFFC(p)              (PEARL_REG_ARL_PORT_BASE_ADDR + ((p) * PEARL_PORT_CTRL_PORT_OFFSET) + 0x3C)
#define PEARL_CSR_FORCE_FW_EN_OFFT (31)
#define PEARL_CSR_FORCE_FW_EN_LENG (1)

#define PEARL_MIR (PEARL_REG_ARL_BASE_ADDRESS + (0xCC))
/* fields of PEARL_MIR */
#define PEARL_MIR_MIRROR_BASE_OFFSER         (8)
#define PEARL_MIR_MIRROR_EN_OFFSER(p)        ((p) * PEARL_MIR_MIRROR_BASE_OFFSER + 0x07)
#define PEARL_MIR_MIRROR_EN_LEN              (1)
#define PEARL_MIR_MIRROR_PORT_OFFSER(p)      ((p) * PEARL_MIR_MIRROR_BASE_OFFSER + 0x00)
#define PEARL_MIR_MIRROR_PORT_LEN            (5)
#define PEARL_MIR_MIRROR_TAG_TX_EN_OFFSER(p) ((p) * PEARL_MIR_MIRROR_BASE_OFFSER + 0x06)
#define PEARL_MIR_MIRROR_TAG_TX_EN_LEN       (1)

#define PEARL_ABSTC (PEARL_REG_ARL_BASE_ADDRESS + 0xC4)
/* fields of MAC and Multicast */
#define PEARL_ATWD_IPM_VLD_OFFSET    0  /* bit[0]     */
#define PEARL_ATWD_IPM_LEAKY_OFFSET  1  /* bit[1]     */
#define PEARL_ATWD_IPM_UPRI_OFFSET   2  /* bit[4:2]   */
#define PEARL_ATWD_IPM_IPV6_OFFSET   5  /* bit[5]     */
#define PEARL_ATWD_IPM_EG_TAG_OFFSET 12 /* bit[14:12] */
#define PEARL_ATWD_IPM_VID_OFFSET    16 /* bit[27:16] */

#define PEARL_ATWD_IPM_VLD_RANGE    1
#define PEARL_ATWD_IPM_LEAKY_RANGE  1
#define PEARL_ATWD_IPM_UPRI_RANGE   3
#define PEARL_ATWD_IPM_IPV6_RANGE   1
#define PEARL_ATWD_IPM_EG_TAG_RANGE 3
#define PEARL_ATWD_IPM_VID_RANGE    12

#define PEARL_ATRD0_IPM_LEAKY_OFFSET 5  /* bit[5] */
#define PEARL_ATRD0_IPM_LEAKY_RANGE  1
#define PEARL_ATRD0_IPM_VID_OFFSET   10 /* bit[21:10] */
#define PEARL_ATRD0_IPM_VID_RANGE    12

/* BSR perport register map*/
#define PEARL_ARL_PORT_BSR_ADDR(p)  (PEARL_REG_ARL_PORT_BASE_ADDR + ((p) * (PEARL_PORT_CTRL_PORT_OFFSET)) + (0x50))
#define PEARL_ARL_PORT_BSR1_ADDR(p) (PEARL_REG_ARL_PORT_BASE_ADDR + ((p) * (PEARL_PORT_CTRL_PORT_OFFSET)) + (0x58))
#define PEARL_ARL_PORT_BSR2_ADDR(p) (PEARL_REG_ARL_PORT_BASE_ADDR + ((p) * (PEARL_PORT_CTRL_PORT_OFFSET)) + (0x60))
#define PEARL_ARL_PORT_BSR3_ADDR(p) (PEARL_REG_ARL_PORT_BASE_ADDR + ((p) * (PEARL_PORT_CTRL_PORT_OFFSET)) + (0x68))

#define PEARL_ARL_PORT_BSR_EXT_ADDR(p)  (PEARL_REG_ARL_PORT_BASE_ADDR + (p) * PEARL_PORT_CTRL_PORT_OFFSET + 0x54)
#define PEARL_ARL_PORT_BSR1_EXT_ADDR(p) (PEARL_REG_ARL_PORT_BASE_ADDR + (p) * PEARL_PORT_CTRL_PORT_OFFSET + 0x5c)
#define PEARL_ARL_PORT_BSR2_EXT_ADDR(p) (PEARL_REG_ARL_PORT_BASE_ADDR + (p) * PEARL_PORT_CTRL_PORT_OFFSET + 0x64)
#define PEARL_ARL_PORT_BSR3_EXT_ADDR(p) (PEARL_REG_ARL_PORT_BASE_ADDR + (p) * PEARL_PORT_CTRL_PORT_OFFSET + 0x6c)

#define PEARL_ARL_PORT_BSR_TOKEN_10_ADDR(p)   (PEARL_REG_ARL_PORT_BASE_ADDR + (p) * PEARL_PORT_CTRL_PORT_OFFSET + 0x74)
#define PEARL_ARL_PORT_BSR_TOKEN_100_ADDR(p)  (PEARL_REG_ARL_PORT_BASE_ADDR + (p) * PEARL_PORT_CTRL_PORT_OFFSET + 0x78)
#define PEARL_ARL_PORT_BSR_TOKEN_1000_ADDR(p) (PEARL_REG_ARL_PORT_BASE_ADDR + (p) * PEARL_PORT_CTRL_PORT_OFFSET + 0x7c)
#define PEARL_ARL_PORT_BSR_TOKEN_2500_ADDR(p) (PEARL_REG_ARL_PORT_BASE_ADDR + (p) * PEARL_PORT_CTRL_PORT_OFFSET + 0x80)

#define PEARL_ARL_PORT_BSR1_TOKEN_10_ADDR(p)   (PEARL_REG_ARL_PORT_BASE_ADDR + (p) * PEARL_PORT_CTRL_PORT_OFFSET + 0x84)
#define PEARL_ARL_PORT_BSR1_TOKEN_100_ADDR(p)  (PEARL_REG_ARL_PORT_BASE_ADDR + (p) * PEARL_PORT_CTRL_PORT_OFFSET + 0x88)
#define PEARL_ARL_PORT_BSR1_TOKEN_1000_ADDR(p) (PEARL_REG_ARL_PORT_BASE_ADDR + (p) * PEARL_PORT_CTRL_PORT_OFFSET + 0x8c)
#define PEARL_ARL_PORT_BSR1_TOKEN_2500_ADDR(p) (PEARL_REG_ARL_PORT_BASE_ADDR + (p) * PEARL_PORT_CTRL_PORT_OFFSET + 0x90)

#define PEARL_ARL_PORT_BSR2_TOKEN_10_ADDR(p)   (PEARL_REG_ARL_PORT_BASE_ADDR + (p) * PEARL_PORT_CTRL_PORT_OFFSET + 0x94)
#define PEARL_ARL_PORT_BSR2_TOKEN_100_ADDR(p)  (PEARL_REG_ARL_PORT_BASE_ADDR + (p) * PEARL_PORT_CTRL_PORT_OFFSET + 0x98)
#define PEARL_ARL_PORT_BSR2_TOKEN_1000_ADDR(p) (PEARL_REG_ARL_PORT_BASE_ADDR + (p) * PEARL_PORT_CTRL_PORT_OFFSET + 0x9c)
#define PEARL_ARL_PORT_BSR2_TOKEN_2500_ADDR(p) (PEARL_REG_ARL_PORT_BASE_ADDR + (p) * PEARL_PORT_CTRL_PORT_OFFSET + 0xa0)

#define PEARL_ARL_PORT_BSR3_TOKEN_10_ADDR(p)   (PEARL_REG_ARL_PORT_BASE_ADDR + (p) * PEARL_PORT_CTRL_PORT_OFFSET + 0xa4)
#define PEARL_ARL_PORT_BSR3_TOKEN_100_ADDR(p)  (PEARL_REG_ARL_PORT_BASE_ADDR + (p) * PEARL_PORT_CTRL_PORT_OFFSET + 0xa8)
#define PEARL_ARL_PORT_BSR3_TOKEN_1000_ADDR(p) (PEARL_REG_ARL_PORT_BASE_ADDR + (p) * PEARL_PORT_CTRL_PORT_OFFSET + 0xac)
#define PEARL_ARL_PORT_BSR3_TOKEN_2500_ADDR(p) (PEARL_REG_ARL_PORT_BASE_ADDR + (p) * PEARL_PORT_CTRL_PORT_OFFSET + 0xb0)

/* fields of port mac control */
#define PEARL_GMAC_PORT_BASE (0x10210000)

#define PEARL_PMCR(p)                    (PEARL_GMAC_PORT_BASE + ((p) * PEARL_PORT_CTRL_PORT_OFFSET))
#define PEARL_MCR_FORCE_LINK_OFFT        (24)
#define PEARL_MCR_FORCE_DUPLEX_OFFT      (25)
#define PEARL_MCR_FORCE_DUPLEX_LENG      (1)
#define PEARL_MCR_FORCE_SPEED_OFFT       (28)
#define PEARL_MCR_FORCE_SPEED_LENG       (3)
#define PEARL_MCR_FORCE_FLOWCTRL_TX_OFFT (4)
#define PEARL_MCR_FORCE_FLOWCTRL_TX_LENG (1)
#define PEARL_MCR_FORCE_FLOWCTRL_RX_OFFT (5)
#define PEARL_MCR_FORCE_FLOWCTRL_RX_LENG (1)
#define PEARL_MCR_EEE_100_EN_OFFT        (6)
#define PEARL_MCR_EEE_1G_EN_OFFT         (7)
#define PEARL_MCR_EEE_2P5G_EN_OFFT       (8)
#define PEARL_MCR_BACK_PRESSURE_OFFT     (11)
#define PEARL_MCR_BACK_PRESSURE_LENG     (1)
#define PEARL_MCR_FORCE_MODE_OFFT        (31)
#define PEARL_MCR_FORCE_MODE_LENG        (1)

#define PEARL_PMSR(p)                   (PEARL_GMAC_PORT_BASE + (p * PEARL_PORT_CTRL_PORT_OFFSET) + 0x10)
#define PEARL_REG_PORT_LINK_OFFT        (24)
#define PEARL_REG_PORT_LINK_LENG        (1)
#define PEARL_REG_PORT_DUPLEX_OFFT      (25)
#define PEARL_REG_PORT_DUPLEX_LENG      (1)
#define PEARL_REG_PORT_SPEED_OFFT       (28)
#define PEARL_REG_PORT_SPEED_LENG       (3)
#define PEARL_REG_PORT_TX_FLOWCTRL_OFFT (4)
#define PEARL_REG_PORT_TX_FLOWCTRL_LENG (1)
#define PEARL_REG_PORT_RX_FLOWCTRL_OFFT (5)
#define PEARL_REG_PORT_RX_FLOWCTRL_LENG (1)
#define PEARL_REG_PORT_EEE100_STS_OFFT  (6)
#define PEARL_REG_PORT_EEE100_STS_LENG  (1)
#define PEARL_REG_PORT_EEE1G_STS_OFFT   (7)
#define PEARL_REG_PORT_EEE1G_STS_LENG   (1)
#define PEARL_REG_PORT_EEE2P5G_STS_OFFT (8)
#define PEARL_REG_PORT_EEE2P5G_STS_LENG (1)

/* fields of global mac control */
#define PEARL_GMAC_GLOBAL_BASE (0x10213E00)

#define PEARL_GMACCR              (PEARL_GMAC_GLOBAL_BASE)
#define PEARL_MAX_RX_PKT_LEN_OFFT (0)
#define PEARL_MAX_RX_PKT_LEN_LENG (2)
#define PEARL_MAX_RX_JUMBO_OFFT   (4)
#define PEARL_MAX_RX_JUMBO_LENG   (4)
#define PEARL_GMACCR_MTCC_OFFT    (8)
#define PEARL_GMACCR_MTCC_LENG    (4)

#define PEARL_SMACCR0 (PEARL_GMAC_GLOBAL_BASE + 0x10)
#define PEARL_SMACCR1 (PEARL_GMAC_GLOBAL_BASE + 0x14)

#define PEARL_CKGCR (PEARL_GMAC_GLOBAL_BASE + 0x1C)

#define PEARL_CKG_LNKDN_GLB_STOP (0x03)

#define PEARL_MIB_CCR                 (PEARL_GMAC_GLOBAL_BASE + 0x30)
#define PEARL_MIB_CCR_MIB_ENABLE      (1 << 31)
#define PEARL_MIB_CCR_RX_OCT_CNT_GOOD (1 << 7)
#define PEARL_MIB_CCR_RX_OCT_CNT_BAD  (1 << 6)
#define PEARL_MIB_CCR_TX_OCT_CNT_GOOD (1 << 5)
#define PEARL_MIB_CCR_TX_OCT_CNT_BAD  (1 << 4)

#define PEARL_MIB_PCLR         (PEARL_GMAC_GLOBAL_BASE + 0x34)
#define PEARL_MIB_PCLR_PORT(p) (1 << p)

#define PEARL_LPDETTXCR             (PEARL_GMAC_GLOBAL_BASE + 0x100)
#define PEARL_LPDETRXCR             (PEARL_GMAC_GLOBAL_BASE + 0x104)
#define PEARL_LPDETCR               (PEARL_GMAC_GLOBAL_BASE + 0x108)
#define PEARL_LPDETCR_OVER_RXPAUSE  (1 << 11)
#define PEARL_LPDETCR_PERIOD_1S     (1 << 7)
#define PEARL_LPDETRXSR             (PEARL_GMAC_GLOBAL_BASE + 0x110)
#define PEARL_LPDETTXSR             (PEARL_GMAC_GLOBAL_BASE + 0x114)
#define PEARL_LPDET_SA_MSB          (PEARL_GMAC_GLOBAL_BASE + 0x120)
#define PEARL_LPDET_FRAME_TYPE_OFFT (16)
#define PEARL_LPDET_FRAME_TYPE_LENG (16)
#define PEARL_LPDET_SMAC_MASK       (0xFFFF)
#define PEARL_LPDET_SA_LSB          (PEARL_GMAC_GLOBAL_BASE + 0x124)

/* Fields of SGMII control */
#define PEARL_SGMII_BASE_ADDR (0x10220000)
#define PEARL_SGMII_PORT_OFFT (0x10000)

#define PEARL_FPGA_USED_ADDR(p) (0x1022A400 + (p * PEARL_SGMII_PORT_OFFT))
#define PEARL_FPGA_USED_VAL     (0x01000000)

#define PEARL_PCS_CTRL(p)               (PEARL_SGMII_BASE_ADDR + (p * PEARL_SGMII_PORT_OFFT))
#define PEARL_REG_SGMII_AN_RESTART_OFFT (9)
#define PEARL_REG_SGMII_AN_RESTART_LENG (1)
#define PEARL_REG_SGMII_AN_OFFT         (12)
#define PEARL_REG_SGMII_AN_LENG         (1)

#define PEARL_PCS_ADV_ABILITY(p)             (PEARL_SGMII_BASE_ADDR + (p * PEARL_SGMII_PORT_OFFT) + 0x10)
#define PEARL_REG_TX_ABILITY_SGMII_OFFT      (0)
#define PEARL_REG_TX_ABILITY_SGMII_LENG      (1)
#define PEARL_REG_1000BASEX_FULL_DUPLEX_OFFT (5)

/* CL37 tx ability*/
#define PEARL_REG_CL_FULL_DUPLEX_OFFT (5)
#define PEARL_REG_CL_HALF_DUPLEX_OFFT (6)
#define PEARL_REG_CL_PAUSE_OFFT       (7)
#define PEARL_REG_CL_PAUSE_LENG       (2)
/* SGMII tx ability */
#define PEARL_REG_SG_SPEED_OFFT       (10)
#define PEARL_REG_SG_SPEED_LENG       (2)
#define PEARL_REG_SG_FULL_DUPLEX_OFFT (12)
#define PEARL_REG_SG_FULL_DUPLEX_LENG (1)

#define PEARL_SGMII_IF_MODE(p)       (PEARL_SGMII_BASE_ADDR + (p * PEARL_SGMII_PORT_OFFT) + 0x34)
#define PEARL_REG_IF_MODE_OFFT       (0)
#define PEARL_REG_IF_MODE_LENG       (6)
#define PEARL_REG_IF_MODE_1000BASEX  (0x22)
#define PEARL_REG_IF_MODE_SGMII      (0x23)
#define PEARL_REG_IF_MODE_AN_OFFT    (1)
#define PEARL_REG_IF_MODE_SPEED_OFFT (2)
#define PEARL_REG_IF_MODE_SPEED_LENG (2)
/* 0:Full, 1:Half */
#define PEARL_REG_IF_MODE_FULL_DUPLEX_OFFT (4)
#define PEARL_REG_REMOTE_FAULT_OFFT        (8)

#define PEARL_HSGMII_PCS_CTRL_1(p)      (PEARL_SGMII_BASE_ADDR + (p * PEARL_SGMII_PORT_OFFT) + 0xA00)
#define PEARL_REG_HSGMII_AN_ENABLE_OFFT (10)

#define PEARL_HSGMII_PCS_CTRL(p)        (PEARL_SGMII_BASE_ADDR + (p * PEARL_SGMII_PORT_OFFT) + 0xA14)
#define PEARL_REG_SGMII_EN_OFFT         (0)
#define PEARL_REG_SGMII_EN_LENG         (1)
#define PEARL_REG_SGMII_RATEADAPT_OFFT  (1)
#define PEARL_REG_SGMII_RATEADAPT_LENG  (1)
#define PEARL_REG_SGMII_TX_EN_OFFT      (4)
#define PEARL_REG_SGMII_TX_EN_LENG      (1)
#define PEARL_REG_SGMII_FORCE_1000_OFFT (12)
#define PEARL_REG_SGMII_FORCE_1000_LENG (1)
#define PEARL_REG_SGMII_FORCE_100_OFFT  (13)
#define PEARL_REG_SGMII_FORCE_100_LENG  (1)
#define PEARL_REG_SGMII_FORCE_10_OFFT   (14)
#define PEARL_REG_SGMII_FORCE_10_LENG   (1)

#define PEARL_HSGMII_PCS_STATUS(p)    (PEARL_SGMII_BASE_ADDR + (p * PEARL_SGMII_PORT_OFFT) + 0xB04)
#define PEARL_REG_HSGMII_AN_DONE_OFFT (0)
#define PEARL_REG_HSGMII_RX_SYNC_OFFT (5)

#define PEARL_MII_RA_AN(p)       (PEARL_SGMII_BASE_ADDR + (p * PEARL_SGMII_PORT_OFFT) + 0x6300)
#define PEARL_REG_RA_AN_EN0_OFFT (0)

#define PEARL_SGMII_PHYA_11(p)    (PEARL_SGMII_BASE_ADDR + (p * PEARL_SGMII_PORT_OFFT) + 0xA02C)
#define PEARL_REG_TPHY_MODE_OFFT  (0)
#define PEARL_REG_TPHY_MODE_LENG  (2)
#define PEARL_REG_TPHY_SPEED_OFFT (2)
#define PEARL_REG_TPHY_SPEED_LENG (2)

#define PEARL_FPGA_CTRL(p) (PEARL_SGMII_BASE_ADDR + (p * PEARL_SGMII_PORT_OFFT) + 0xA400)

#define PEARL_PORT_TRUNK_OFFSET (0x0400)
#define PEARL_PTC               (PEARL_REG_ARL_BASE_ADDRESS + (PEARL_PORT_TRUNK_OFFSET + 0x00))
/* fields of PEARL_PTC */
#define PEARL_PTC_INFO_OFFT      (0)
#define PEARL_PTC_INFO_LEN       (7)
#define PEARL_PTC_INFO_SEL_SP    (1 << 0)
#define PEARL_PTC_INFO_SEL_SA    (1 << 1)
#define PEARL_PTC_INFO_SEL_DA    (1 << 2)
#define PEARL_PTC_INFO_SEL_SIP   (1 << 3)
#define PEARL_PTC_INFO_SEL_DIP   (1 << 4)
#define PEARL_PTC_INFO_SEL_SPORT (1 << 5)
#define PEARL_PTC_INFO_SEL_DPORT (1 << 6)
#define PEARL_PTC_SP_SEL         (1 << 20)

#define PEARL_PTC_HASH_CONTROL_OFFT (8)
#define PEARL_PTC_HASH_CONTROL_LEN  (2)

#define PEARL_PTSEED (PEARL_REG_ARL_BASE_ADDRESS + (PEARL_PORT_TRUNK_OFFSET + 0x04))

#define PEARL_PTGC                    (PEARL_REG_ARL_BASE_ADDRESS + (PEARL_PORT_TRUNK_OFFSET + 0x08))
#define PEARL_PTGC_GROUP_EN_OFFSET(g) (g)
#define PEARL_PTGC_GROUP_EN_LEN       (1)

#define PEARL_PTG_BASE (8)

#define PEARL_PTG_1(g)               (PEARL_REG_ARL_BASE_ADDRESS + (PEARL_PORT_TRUNK_OFFSET + 0x0C + ((g) * 0x8)))
#define PEARL_PTG_2(g)               (PEARL_REG_ARL_BASE_ADDRESS + (PEARL_PORT_TRUNK_OFFSET + 0x10 + ((g) * 0x8)))
#define PEARL_PTGN_PORT_OFFSET(p)    ((PEARL_PTG_BASE * ((p) % 4)) + 0x0)
#define PEARL_PTGN_PORT_LEN          (5)
#define PEARL_PTGN_PORT_EN_OFFSET(p) ((PEARL_PTG_BASE * ((p) % 4)) + 0x7)
#define PEARL_PTGN_PORT_EN_LEN       (1)

/* Register of MIB Base address */
#define PEARL_MIB_BASE        (PEARL_REG_ARL_BASE_ADDRESS + 0x14000)
#define PEARL_MIB_PORT_OFFSET 0x0200

#define PEARL_MIB_TCDPC(p)    (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x00)
#define PEARL_MIB_TCEPC(p)    (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x04)
#define PEARL_MIB_TUPC(p)     (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x08)
#define PEARL_MIB_TMPC(p)     (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x0C)
#define PEARL_MIB_TBPC(p)     (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x10)
#define PEARL_MIB_TCEC(p)     (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x14)
#define PEARL_MIB_TSCEC(p)    (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x18)
#define PEARL_MIB_TMCEC(p)    (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x1C)
#define PEARL_MIB_TDEC(p)     (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x20)
#define PEARL_MIB_TLCEC(p)    (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x24)
#define PEARL_MIB_TXCEC(p)    (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x28)
#define PEARL_MIB_TPPC(p)     (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x2C)
#define PEARL_MIB_TL64PC(p)   (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x30)
#define PEARL_MIB_TL65PC(p)   (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x34)
#define PEARL_MIB_TL128PC(p)  (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x38)
#define PEARL_MIB_TL256PC(p)  (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x3C)
#define PEARL_MIB_TL512PC(p)  (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x40)
#define PEARL_MIB_TL1024PC(p) (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x44)
#define PEARL_MIB_TL1519PC(p) (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x48)
#define PEARL_MIB_TOCL(p)     (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x4C)
#define PEARL_MIB_TOCH(p)     (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x50)
#define PEARL_MIB_TODPC(p)    (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x54)

#define PEARL_MIB_RDPC(p)     (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x80)
#define PEARL_MIB_RFPC(p)     (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x84)
#define PEARL_MIB_RUPC(p)     (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x88)
#define PEARL_MIB_RMPC(p)     (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x8C)
#define PEARL_MIB_RBPC(p)     (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x90)
#define PEARL_MIB_RAEPC(p)    (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x94)
#define PEARL_MIB_RCEPC(p)    (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x98)
#define PEARL_MIB_RUSPC(p)    (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x9C)
#define PEARL_MIB_RFEPC(p)    (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0xA0)
#define PEARL_MIB_ROSPC(p)    (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0xA4)
#define PEARL_MIB_RJEPC(p)    (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0xA8)
#define PEARL_MIB_RPPC(p)     (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0xAC)
#define PEARL_MIB_RL64PC(p)   (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0xB0)
#define PEARL_MIB_RL65PC(p)   (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0xB4)
#define PEARL_MIB_RL128PC(p)  (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0xB8)
#define PEARL_MIB_RL256PC(p)  (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0xBC)
#define PEARL_MIB_RL512PC(p)  (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0xC0)
#define PEARL_MIB_RL1024PC(p) (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0xC4)
#define PEARL_MIB_RL1519PC(p) (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0xC8)
#define PEARL_MIB_ROCL(p)     (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0xCC)
#define PEARL_MIB_ROCH(p)     (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0xD0)
#define PEARL_MIB_RCDPC(p)    (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0xD4)
#define PEARL_MIB_RIDPC(p)    (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0xD8)
#define PEARL_MIB_RADPC(p)    (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0xDC)

#define PEARL_MIB_TMIB_HF_STS(p) (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0x7C)
#define PEARL_MIB_RMIB_HF_STS(p) (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0xFC)

#define PEARL_MIB_FCDPC(p)  (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0xE0)
#define PEARL_MIB_WRDPC(p)  (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0xE4)
#define PEARL_MIB_MRDPC(p)  (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0xE8)
#define PEARL_MIB_RSFSPC(p) (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0xF4)
#define PEARL_MIB_RSFTPC(p) (PEARL_MIB_BASE + (p) * PEARL_MIB_PORT_OFFSET + 0xF8)

/* Register of DoS Attack Prevention address */
#define PEARL_ATTACK_PREVENT_GLB         (PEARL_REG_ARL_BASE_ADDRESS + 0x0540)
#define PEARL_ATTACK_PREVENT_GLB_EN_OFFT (0)
#define PEARL_ATTACK_PREVENT_GLB_EN_LENG (1)

#define PEARL_ATTACK_LENGTH_CFG       (PEARL_ATTACK_PREVENT_GLB + 0x04)
#define PEARL_ATTACK_LENGTH_THLD_OFFT (0)
#define PEARL_ATTACK_LENGTH_THLD_LENG (16)

#define PEARL_ATTACK_TCP_FLAG_CFG        (PEARL_ATTACK_PREVENT_GLB + 0x08)
#define PEARL_ATTACK_TCP_FLAG_MSK        (PEARL_ATTACK_PREVENT_GLB + 0x0c)
#define PEARL_ATTACK_TCP_SETTING_OFFT(i) ((i) * (PEARL_ATTACK_TCP_SETTING_LENG + 1))
#define PEARL_ATTACK_TCP_SETTING_LENG    (9)
#define PEARL_ATTACK_TCP_FLAG_SEL_NS     (1 << 8)
#define PEARL_ATTACK_TCP_FLAG_SEL_CWR    (1 << 7)
#define PEARL_ATTACK_TCP_FLAG_SEL_ECE    (1 << 6)
#define PEARL_ATTACK_TCP_FLAG_SEL_URG    (1 << 5)
#define PEARL_ATTACK_TCP_FLAG_SEL_ACK    (1 << 4)
#define PEARL_ATTACK_TCP_FLAG_SEL_PSH    (1 << 3)
#define PEARL_ATTACK_TCP_FLAG_SEL_RST    (1 << 2)
#define PEARL_ATTACK_TCP_FLAG_SEL_SYN    (1 << 1)
#define PEARL_ATTACK_TCP_FLAG_SEL_FIN    (1 << 0)

#define PEARL_ATTACK_CFG_DONE_OFFT  (31)
#define PEARL_ATTACK_CFG_DONE_LENG  (1)
#define PEARL_ATTACK_CFG_EN_OFFT    (0)
#define PEARL_ATTACK_CFG_WR_OFFT    (1)
#define PEARL_ATTACK_CFG_CLEAR_OFFT (2)

#define PEARL_ATTACK_ACTION_CFG           (PEARL_ATTACK_PREVENT_GLB + 0x10)
#define PEARL_ATTACK_ACTION_CFG_PID_OFFT  (4)
#define PEARL_ATTACK_ACTION_CFG_PID_LENG  (5)
#define PEARL_ATTACK_ACTION_SRAM_WR_DATA0 (PEARL_ATTACK_PREVENT_GLB + 0x18)
#define PEARL_ATTACK_ACTION_SRAM_WR_DATA1 (PEARL_ATTACK_PREVENT_GLB + 0x1c)
#define PEARL_ATTACK_ACTION_RATE_ID_LENG  (7)
#define PEARL_ATTACK_ACTION_RATE_EN_LENG  (1)
#define PEARL_ATTACK_ACTION_DROP_LENG     (1)
#define PEARL_ATTACK_RATE_EN_OFFT(g)      ((g) + PEARL_ATTACK_ACTION_RATE_ID_LENG)
#define PEARL_ATTACK_DROP_EN_OFFT(g)      ((g) + PEARL_ATTACK_ACTION_RATE_ID_LENG + PEARL_ATTACK_ACTION_RATE_EN_LENG)
#define PEARL_ATTACK_LAND_OFFT            (0)
#define PEARL_ATTACK_BLAT_OFFT            (9)
#define PEARL_ATTACK_LENGTH_OFFT          (18)
#define PEARL_ATTACK_TCP1_OFFT            (4)
#define PEARL_ATTACK_TCP2_OFFT            (13)
#define PEARL_ATTACK_PING_OFFT            (22)
#define PEARL_ATTACK_TCP0_RATE_ID_LO_OFFT (27)
#define PEARL_ATTACK_TCP0_RATE_ID_LO_LENG (5)
#define PEARL_ATTACK_TCP0_RATE_ID_HI_OFFT (0)
#define PEARL_ATTACK_TCP0_RATE_ID_HI_LENG (2)
#define PEARL_ATTACK_TCP0_RATE_EN_OFFT    (2)
#define PEARL_ATTACK_TCP0_DROP_OFFT       (3)
#define PEARL_ATTACK_ACTION_SRAM_RE_DATA0 (PEARL_ATTACK_PREVENT_GLB + 0x20)
#define PEARL_ATTACK_ACTION_SRAM_RE_DATA1 (PEARL_ATTACK_PREVENT_GLB + 0x24)

#define PEARL_ATTACK_RATE_CFG               (PEARL_ATTACK_PREVENT_GLB + 0x30)
#define PEARL_ATTACK_RATE_CFG_RATE_ID_OFFT  (4)
#define PEARL_ATTACK_RATE_CFG_RATE_ID_LENG  (7)
#define PEARL_ATTACK_RATE_SRAM_WR_DATA0     (PEARL_ATTACK_PREVENT_GLB + 0x38)
#define PEARL_ATTACK_RATE_SRAM_WR_DATA1     (PEARL_ATTACK_PREVENT_GLB + 0x3c)
#define PEARL_ATTACK_RATE_WR_CFG_LENG       (16)
#define PEARL_ATTACK_RATE_WR_TICK_SEL_LENG  (1)
#define PEARL_ATTACK_RATE_TIME_SPAN_OFFT    (0)
#define PEARL_ATTACK_RATE_PKT_NUM_THLD_OFFT (16)
#define PEARL_ATTACK_RATE_BLOCK_TIME_OFFT   (0)
#define PEARL_ATTACK_RATE_TICK_SEL_OFFT     (16)
#define PEARL_ATTACK_RATE_SRAM_RE_DATA0     (PEARL_ATTACK_PREVENT_GLB + 0x40)
#define PEARL_ATTACK_RATE_SRAM_RE_DATA1     (PEARL_ATTACK_PREVENT_GLB + 0x44)

#define PEARL_ATTACK_DROP_CNT        (PEARL_REG_ARL_BASE_ADDRESS + 0x0590)
#define PEARL_ATTACK_DROP_CNT_CLR    (PEARL_ATTACK_DROP_CNT + 0x04)
#define PEARL_ATTACK_DROP_CNT_CLR_A0 (1 << 0)
/* Register of ACL address */
#define PEARL_ARL_GLOBAL_CNTRL    (PEARL_REG_ARL_BASE_ADDRESS + 0x00c)
#define PEARL_ACL_BASE            (PEARL_REG_ARL_BASE_ADDRESS + 0x500)
#define PEARL_ACL_GLOBAL_CFG      (PEARL_ACL_BASE + 0x00)
#define PEARL_ACL_PORT_EN         (PEARL_ACL_BASE + 0x04)
#define PEARL_ACL_GROUP_CFG       (PEARL_ACL_BASE + 0x08)
#define PEARL_ACL_MEM_CFG         (PEARL_ACL_BASE + 0x0c)
#define PEARL_ACL_MEM_CFG_WDATA0  (PEARL_ACL_BASE + 0x10)
#define PEARL_ACL_MEM_CFG_WDATA1  (PEARL_ACL_BASE + 0x14)
#define PEARL_ACL_MEM_CFG_WDATA2  (PEARL_ACL_BASE + 0x18)
#define PEARL_ACL_MEM_CFG_WDATA3  (PEARL_ACL_BASE + 0x1c)
#define PEARL_ACL_MEM_CFG_RDATA0  (PEARL_ACL_BASE + 0x20)
#define PEARL_ACL_MEM_CFG_RDATA1  (PEARL_ACL_BASE + 0x24)
#define PEARL_ACL_MEM_CFG_RDATA2  (PEARL_ACL_BASE + 0x28)
#define PEARL_ACL_MEM_CFG_RDATA3  (PEARL_ACL_BASE + 0x2c)
#define PEARL_ACL_STATUS          (PEARL_ACL_BASE + 0x30)
#define PEARL_ACL_MIB_CNT_CFG     (PEARL_ACL_BASE + 0x34)
#define PEARL_ACL_MIB_CNT         (PEARL_ACL_BASE + 0x38)
#define PEARL_ACL_TRTCM           (PEARL_REG_ARL_BASE_ADDRESS + 0x100)
#define PEARL_ACL_TRTCMA          (PEARL_REG_ARL_BASE_ADDRESS + 0x104)
#define PEARL_ACL_TRTCM_CBS_WDATA (PEARL_REG_ARL_BASE_ADDRESS + 0x108)
#define PEARL_ACL_TRTCM_EBS_WDATA (PEARL_REG_ARL_BASE_ADDRESS + 0x10C)
#define PEARL_ACL_TRTCM_CIR_WDATA (PEARL_REG_ARL_BASE_ADDRESS + 0x110)
#define PEARL_ACL_TRTCM_EIR_WDATA (PEARL_REG_ARL_BASE_ADDRESS + 0x114)
#define PEARL_ACL_TRTCM_CBS_RDATA (PEARL_REG_ARL_BASE_ADDRESS + 0x118)
#define PEARL_ACL_TRTCM_EBS_RDATA (PEARL_REG_ARL_BASE_ADDRESS + 0x11C)
#define PEARL_ACL_TRTCM_CIR_RDATA (PEARL_REG_ARL_BASE_ADDRESS + 0x120)
#define PEARL_ACL_TRTCM_EIR_RDATA (PEARL_REG_ARL_BASE_ADDRESS + 0x124)
#define PEARL_ACLRMC              (PEARL_REG_ARL_BASE_ADDRESS + 0x470)
#define PEARL_ACLRMD1             (PEARL_REG_ARL_BASE_ADDRESS + 0x474)
#define PEARL_ACLRMD2             (PEARL_REG_ARL_BASE_ADDRESS + 0x478)

#define PEARL_ACL_EN_MASK                  (0x1)
#define PEARL_ACL_MEM_CFG_DONE_OFFSET      (31)
#define PEARL_ACL_MEM_CFG_RULE_ID_OFFSET   (16)
#define PEARL_ACL_MEM_CFG_TCAM_CELL_OFFSET (12)
#define PEARL_ACL_MEM_CFG_DATA_BN_OFFSET   (8)
#define PEARL_ACL_MEM_CFG_MEM_SEL_OFFSET   (4)
#define PEARL_ACL_MEM_CFG_FUNC_SEL_OFFSET  (1)
#define PEARL_ACL_MEM_CFG_EN               (1)
#define PEARL_ACL_ACT_GROUP_END_0_OFFSET   (7)
#define PEARL_ACL_ACT_GROUP_END_1_OFFSET   (15)
#define PEARL_ACL_ACT_GROUP_END_2_OFFSET   (21)
#define PEARL_ACL_LAST_LINE_0_OFFSET       (0)
#define PEARL_ACL_LAST_LINE_1_OFFSET       (8)
#define PEARL_ACL_LAST_LINE_2_OFFSET       (16)
#define PEARL_ACL_LAST_LINE_3_OFFSET       (24)
#define PEARL_ACL_LAST_LINE_MASK           (0x1f)
#define PEARL_ACL_MIB_SEL_OFFSET           (4)
#define PEARL_ACL_MIB_CLEAR                (1)
#define PEARL_ACL_MIB_SEL_MASK             (0x3f)
#define PEARL_ACL_TRTCM_EN_OFFSET          (31)
#define PEARL_ACL_TRTCM_BUSY_OFFSET        (31)
#define PEARL_ACL_TRTCM_WRITE              (1U << 27)
#define PEARL_ACL_TRTCM_READ               (0U << 27)
#define PEARL_ACL_TRTCM_ID_OFFSET          (0)
#define PEARL_ACL_TRTCM_ID_MASK            (0x1f)
#define PEARL_ACL_TRTCM_CBS_OFFSET         (0)
#define PEARL_ACL_TRTCM_CBS_MASK           (0x1ffff)
#define PEARL_ACL_TRTCM_EBS_OFFSET         (0)
#define PEARL_ACL_TRTCM_EBS_MASK           (0x1ffff)
#define PEARL_ACL_TRTCM_CIR_OFFSET         (0)
#define PEARL_ACL_TRTCM_CIR_MASK           (0x1ffff)
#define PEARL_ACL_TRTCM_EIR_OFFSET         (0)
#define PEARL_ACL_TRTCM_EIR_MASK           (0x1ffff)
#define PEARL_ACL_RATE_BUSY_OFFSET         (31)
#define PEARL_ACL_RATE_WRITE               (1U << 30)
#define PEARL_ACL_RATE_READ                (0U << 30)
#define PEARL_ACL_RATE_ID_OFFSET           (20)
#define PEARL_ACL_RATE_ID_MASK             (0x1f)
#define PEARL_ACL_RATE_EN_OFFSET           (19)
#define PEARL_ACL_RATE_EN                  (1U << 19)
#define PEARL_ACL_RATE_DIS                 (0U << 19)
#define PEARL_ACL_RATE_TOKEN_MASK          (0xffff)

#define PEARL_ACL_UDF_BASE (PEARL_REG_ARL_BASE_ADDRESS + 0x200)
#define PEARL_ACL_AUTC     (PEARL_ACL_UDF_BASE + 0x00)
#define PEARL_ACL_AUTW0    (PEARL_ACL_UDF_BASE + 0x08)
#define PEARL_ACL_AUTW1    (PEARL_ACL_UDF_BASE + 0x0c)
#define PEARL_ACL_AUTW2    (PEARL_ACL_UDF_BASE + 0x10)
#define PEARL_ACL_AUTR0    (PEARL_ACL_UDF_BASE + 0x20)
#define PEARL_ACL_AUTR1    (PEARL_ACL_UDF_BASE + 0x24)
#define PEARL_ACL_AUTR2    (PEARL_ACL_UDF_BASE + 0x28)

#define PEARL_ACL_UDF_ACC_OFFSET (31)
#define PEARL_ACL_UDF_READ_MASK  (0x0)
#define PEARL_ACL_UDF_WRITE_MASK (0x1)
#define PEARL_ACL_UDF_CLEAR_MASK (0x2)
#define PEARL_ACL_UDF_CMD_OFFSET (28)
#define PEARL_ACL_UDF_READ       (PEARL_ACL_UDF_READ_MASK << PEARL_ACL_UDF_CMD_OFFSET)
#define PEARL_ACL_UDF_WRITE      (PEARL_ACL_UDF_WRITE_MASK << PEARL_ACL_UDF_CMD_OFFSET)
#define PEARL_ACL_UDF_CLEAR      (PEARL_ACL_UDF_CLEAR_MASK << PEARL_ACL_UDF_CMD_OFFSET)
#define PEARL_ACL_UDF_ADDR_MASK  (0xf)

/* Register of PEARL_DPCR */
#define PEARL_BMU_PORT_BASE          (0x10204000)
#define PEARL_DPCR_COLOR_OFFSET      (0x20)
#define PEARL_DPCR_QUEUE_OFFSET      (0x4)
#define PEARL_FPC_RXCTRL(p)          (0x10218000 + (p * PEARL_PORT_CTRL_PORT_OFFSET) + 0x04)
#define PEARL_FPC_RXCTRL_FP_CNT_OFFT (0)
#define PEARL_FPC_RXCTRL_FP_CNT_LENG (3)
#define PEARL_DPCR_EN(p)             (PEARL_BMU_PORT_BASE + (p * PEARL_PORT_CTRL_PORT_OFFSET) + 0x08)
#define PEARL_DPCR_BASE              (PEARL_BMU_PORT_BASE + 0x10)
#define PEARL_DPCR(p, c, q)          (PEARL_DPCR_BASE + (p * PEARL_PORT_CTRL_PORT_OFFSET) + (c * PEARL_DPCR_COLOR_OFFSET) + (q * PEARL_DPCR_QUEUE_OFFSET))

#define PEARL_DPCR_HIGH_THRSH_OFFSET (11)
#define PEARL_DPCR_PBB_OFFSET        (22)
#define PEARL_DPCR_LOW_THRSH_WIDTH   (0x7ff)
#define PEARL_DPCR_HIGH_THRSH_WIDTH  (0x7ff)
#define PEARL_DPCR_PBB_WIDTH         (0x3ff)
#define PEARL_DP_MFRM_EX_OFFSET      (24)
/*Register of Min-Max shaper value*/
/*SCH perport base addr*/
#define PEARL_REG_SCH_PORT_ADDRESS (PEARL_REG_ARL_BASE_ADDRESS + 0xc000)

#define PEARL_MMSCR0_Q0(p) (PEARL_REG_SCH_PORT_ADDRESS + PEARL_PORT_CTRL_PORT_OFFSET * (p))
#define PEARL_MMSCR1_Q0(p) (PEARL_REG_SCH_PORT_ADDRESS + PEARL_PORT_CTRL_PORT_OFFSET * (p) + 0x4)
#define PEARL_MMSCR0_Q1(p) (PEARL_REG_SCH_PORT_ADDRESS + PEARL_PORT_CTRL_PORT_OFFSET * (p) + 0x8)
#define PEARL_MMSCR1_Q1(p) (PEARL_REG_SCH_PORT_ADDRESS + PEARL_PORT_CTRL_PORT_OFFSET * (p) + 0xc)
#define PEARL_MMSCR0_Q2(p) (PEARL_REG_SCH_PORT_ADDRESS + PEARL_PORT_CTRL_PORT_OFFSET * (p) + 0x10)
#define PEARL_MMSCR1_Q2(p) (PEARL_REG_SCH_PORT_ADDRESS + PEARL_PORT_CTRL_PORT_OFFSET * (p) + 0x14)
#define PEARL_MMSCR0_Q3(p) (PEARL_REG_SCH_PORT_ADDRESS + PEARL_PORT_CTRL_PORT_OFFSET * (p) + 0x18)
#define PEARL_MMSCR1_Q3(p) (PEARL_REG_SCH_PORT_ADDRESS + PEARL_PORT_CTRL_PORT_OFFSET * (p) + 0x1c)
#define PEARL_MMSCR0_Q4(p) (PEARL_REG_SCH_PORT_ADDRESS + PEARL_PORT_CTRL_PORT_OFFSET * (p) + 0x20)
#define PEARL_MMSCR1_Q4(p) (PEARL_REG_SCH_PORT_ADDRESS + PEARL_PORT_CTRL_PORT_OFFSET * (p) + 0x24)
#define PEARL_MMSCR0_Q5(p) (PEARL_REG_SCH_PORT_ADDRESS + PEARL_PORT_CTRL_PORT_OFFSET * (p) + 0x28)
#define PEARL_MMSCR1_Q5(p) (PEARL_REG_SCH_PORT_ADDRESS + PEARL_PORT_CTRL_PORT_OFFSET * (p) + 0x2c)
#define PEARL_MMSCR0_Q6(p) (PEARL_REG_SCH_PORT_ADDRESS + PEARL_PORT_CTRL_PORT_OFFSET * (p) + 0x30)
#define PEARL_MMSCR1_Q6(p) (PEARL_REG_SCH_PORT_ADDRESS + PEARL_PORT_CTRL_PORT_OFFSET * (p) + 0x34)
#define PEARL_MMSCR0_Q7(p) (PEARL_REG_SCH_PORT_ADDRESS + PEARL_PORT_CTRL_PORT_OFFSET * (p) + 0x38)
#define PEARL_MMSCR1_Q7(p) (PEARL_REG_SCH_PORT_ADDRESS + PEARL_PORT_CTRL_PORT_OFFSET * (p) + 0x3c)

/* Register of serial LED control */
#define PEARL_SLED_CTRL0 (0x1021c024)
#define PEARL_SLED_CTRL1 (0x1021c028)
/* Per port LED control b[23..8] */
#define PEARL_SLED_SRC_SEL         (0x1021c02c)
#define PEARL_SLED_FLASH_SET_CTRL0 (0x1021c030)
#define PEARL_SLED_FLASH_SET_CTRL1 (0x1021c034)
#define PEARL_SLED_FLASH_SET_CTRL2 (0x1021c038)
#define PEARL_SLED_FLASH_SET_CTRL3 (0x1021c03c)

/* fields of serial LED control register */
#define PEARL_SLED_SOURCE_NORMAL_MODE       (0)
#define PEARL_SLED_SOURCE_INTERLEAVING_MODE (1 << 0)
#define PEARL_SLED_NUM_LED0                 (1 << 1)
#define PEARL_SLED_NUM_LED0_LED1            (2 << 1)
#define PEARL_SLED_NUM_LED0_LED1_LED2       (3 << 1)
#define PEARL_SLED_OUTPUT_TRANSITION_MODE   (0)
#define PEARL_SLED_OUTPUT_CONTINUOUS_MODE   (1 << 3)
#define PEARL_SLED_FALLING_EDGE             (0)
#define PEARL_SLED_RISING_EDGE              (1 << 4)

/* Register of parallel LED control */
#define PEARL_RG_LAN_LED_IOMUX            (0x10000054)
#define PEARL_RG_GPIO_SLED_MODE0          (1 << 21)
#define PEARL_RG_GPIO_LED_SEL(gpio)       (0x10000058 + ((gpio / 4) * 4))
#define PEARL_RG_GPIO_LED_MASK(gpio)      (0xFF << ((gpio % 4) * 8))
#define PEARL_RG_GPIO_LED_VAL(gpio, data) (((data) & 0xFF) << ((gpio % 4) * 8))

/* GPIO flash map config*/
#define PEARL_RG_GPIO_FLASH_MODE_CFG (0x1000a334)
#define PEARL_RG_GPIO_RSP_MODE_CFG   (0x1000a338)
#define PEARL_RG_GPIO_FLASH_PRD_SET0 (0x1000a33c)
#define PEARL_RG_GPIO_FLASH_PRD_SET1 (0x1000a340)
#define PEARL_RG_GPIO_FLASH_PRD_SET2 (0x1000a344)
#define PEARL_RG_GPIO_FLASH_PRD_SET3 (0x1000a348) /* period 7 & 6 */

#define PEARL_RG_GPIO_FLASH_MAP_CFG0 (0x1000a34c)
#define PEARL_RG_GPIO_FLASH_MAP_CFG1 (0x1000a350) /* map 12,13,13,15 */
#define PEARL_RG_CYCLE_CFG_VALUE0    (0x1000a398)
#define PEARL_RG_CYCLE_CFG_VALUE1    (0x1000a39C)

#define PEARL_GPIO_WAVE_ACTIVE_LOW  (0x000000ff)
#define PEARL_GPIO_WAVE_ACTIVE_HIGH (0x00ff0000)

#define PEARL_GPIO_WAVE_LED_ON  (0xeeee0000)
#define PEARL_GPIO_WAVE_LED_OFF (0xffff0000)

/* GPIO low byte TX Driving control */
#define PEARL_GPIO_L_E2_TX_DRIVING_CTRL (0x10000018)
#define PEARL_GPIO_SPI_E2_BITS          (0x00001e00)
#define PEARL_GPIO_SMI_E2_BITS          (0x00000180)
#define PEARL_GPIO_I2C_E2_BITS          (0x00180000)

/* Operation Register Base */
#define PEARL_REG_EFUSE_BASE_ADDRESS (0x10004000)
#define PEARL_EFUSE_CTRL             (PEARL_REG_EFUSE_BASE_ADDRESS + 0x08)
#define PEARL_EFUSE_RDATA0           (PEARL_REG_EFUSE_BASE_ADDRESS + 0x30)
#define PEARL_EFUSE_RDATA1           (PEARL_REG_EFUSE_BASE_ADDRESS + 0x34)
#define PEARL_EFUSE_RDATA2           (PEARL_REG_EFUSE_BASE_ADDRESS + 0x38)
#define PEARL_EFUSE_RDATA3           (PEARL_REG_EFUSE_BASE_ADDRESS + 0x3C)

/**************************************** SIF MODULE *****************************************/
/* HW Trap Normal Mode Read Back Register, used for I2C Mode */
#define PEARL_REG_RGS_CPU_EN (0x100000A8UL)

/* I2C Master Register Base */
#define PEARL_REG_SIF_MASTER0_BASE_ADDRESS (0x10008000UL)
#define PEARL_REG_SIF_AUTO_CTRL            (0xA0UL)
#define PEARL_AUTOMODE_EN_BIT              (31UL)
#define PEARL_AUTOMODE_EN_MSK              (0x1UL)

/* I2C Master Register Offset */
#define PEARL_SIF_SIFMCTL0 (0x40UL)
#define PEARL_SIF_SIFMCTL1 (0x44UL)
#define PEARL_SIF_SIFMD0   (0x50UL)
#define PEARL_SIF_SIFMD1   (0x54UL)

/* SIFM Configuration Register 0 Mask */
#define PEARL_SIF_EN_MSK        (1UL)
#define PEARL_SIF_SDA_STATE_MSK (1UL)
#define PEARL_SIF_SCL_STATE_MSK (1UL)
#define PEARL_SIF_CLK_DIV_MSK   (0xfffUL)

/* SIFM Configuration Register 1 Mask */
#define PEARL_SIF_TRI_MSK   (1UL)
#define PEARL_SIF_MODE_MSK  (0x7UL)
#define PEARL_SIF_PGLEN_MSK (0x7UL)
#define PEARL_SIF_ACK_MSK   (0xffUL)

/* HW Trap Normal Mode Bit */

/* SIFM Configuration Register 0 Bit Position */
#define PEARL_SIF_EN_BIT        (1UL)
#define PEARL_SIF_SDA_STATE_BIT (2UL)
#define PEARL_SIF_SCL_STATE_BIT (3UL)
#define PEARL_SIF_CLK_DIV_BIT   (16UL)

/* SIFM Configuration Register 1 Bit Position */
#define PEARL_SIF_TRI_BIT   (0UL)
#define PEARL_SIF_MODE_BIT  (4UL)
#define PEARL_SIF_PGLEN_BIT (8UL)
#define PEARL_SIF_ACK_BIT   (16UL)

/* SIFM Configuration Register 0 Shifted Mask */
#define PEARL_SIF_EN_SM        ((PEARL_SIF_EN_MSK) << (PEARL_SIF_EN_BIT))
#define PEARL_SIF_SDA_STATE_SM ((PEARL_SIF_SDA_STATE_MSK) << (PEARL_SIF_SDA_STATE_BIT))
#define PEARL_SIF_SCL_STATE_SM ((PEARL_SIF_SCL_STATE_MSK) << (PEARL_SIF_SCL_STATE_BIT))
#define PEARL_SIF_CLK_DIV_SM   ((PEARL_SIF_CLK_DIV_MSK) << (PEARL_SIF_CLK_DIV_BIT))

/* SIFM Configuration Register 1 Mask */
#define PEARL_SIF_TRI_SM   ((PEARL_SIF_TRI_MSK) << (PEARL_SIF_TRI_BIT))
#define PEARL_SIF_MODE_SM  ((PEARL_SIF_MODE_MSK) << (PEARL_SIF_MODE_BIT))
#define PEARL_SIF_PGLEN_SM ((PEARL_SIF_PGLEN_MSK) << (PEARL_SIF_PGLEN_BIT))
#define PEARL_SIF_ACK_SM   ((PEARL_SIF_ACK_MSK) << (PEARL_SIF_ACK_BIT))

/**************************************** SIF MODULE *****************************************/

/**************************************** PERIPHERAL *****************************************/
/* peripheral register definition */
#define PEARL_RG_I2C_IOMUX             (0x1000006CUL)
#define PEARL_RG_I2C_MST_IOMUX_RELMASK (1)
#define PEARL_RG_I2C_MST_IOMUX_OFFT    (2)
#define PEARL_RG_I2C_MST_IOMUX_MASK    (PEARL_RG_I2C_MST_IOMUX_RELMASK << PEARL_RG_I2C_MST_IOMUX_OFFT)
#define PEARL_RG_SMI_IOMUX             (0x10000070UL)
#define PEARL_RG_SMI_MST_IOMUX_RELMASK (1)
#define PEARL_RG_SMI_MST_IOMUX_OFFT    (1)
#define PEARL_RG_SMI_MST_IOMUX_MASK    (PEARL_RG_SMI_MST_IOMUX_RELMASK << PEARL_RG_SMI_MST_IOMUX_OFFT)
#define PEARL_RG_GPIO_EN_REG           (0x1000007CUL)
#define PEARL_RG_GPIO_INVERSE          (0x10000010UL)

/* GPIO Register definition */
#define PEARL_REG_GPIOCTRL  (0x1000A300UL)
#define PEARL_REG_GPIOCTRL1 (0x1000A320UL)

#define PEARL_REG_GPIODATA (0x1000A304UL)

#define PEARL_REG_GPIOOE (0x1000A314UL)

#define PEARL_REG_GPIOINT (0x1000A308UL)

#define PEARL_REG_GPIOINTEDG  (0x1000A30CUL)
#define PEARL_REG_GPIOINTEDG1 (0x1000A380UL)

#define PEARL_REG_GPIOINTLVL  (0x1000A310UL)
#define PEARL_REG_GPIOINTLVL1 (0x1000A38CUL)
/**************************************** PERIPHERAL *****************************************/
#define PEARL_REG_BGPOR_CTRL1 (0x10000124UL)
#define PEARL_REG_HUID_HIGH   (0x1000A570UL)
#define PEARL_REG_HUID_LOW    (0x1000A56CUL)

#define PEARL_REG_RGS_PKG_SEL        (0x10000094UL)
#define PEARL_REG_REVISION_ID        (0x10005004UL)
#define PEARL_REG_GDMP_RAM           (0x10010000UL)
#define PEARL_REG_CLK_CPU_ICG_ENABLE (0x10005034UL)
#define PEARL_REG_TIMERCTLR          (0x1000A100UL)

/* MACRO FUNCTION DECLARATIONS
 */

/* DATA TYPE DECLARATIONS
 */

/* EXPORTED SUBPROGRAM SPECIFICATIONS
 */

#endif /* PEARL_HAL_PEARL_REG_H */
