/*******************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of Airoha Technology Corp. (C) 2024
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("AIROHA SOFTWARE")
*  RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE AIROHA SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. AIROHA SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY AIROHA SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE AIROHA SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT AIROHA'S OPTION, TO REVISE OR REPLACE THE AIROHA SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*******************************************************************************/

/* FILE NAME:   mw_msg.h
 * PURPOSE:
 *      Define well-known message IDs and other message related types.
 * NOTES:
 *
 */

#ifndef MW_MSG_H
#define MW_MSG_H

/* INCLUDE FILE DECLARATIONS
 */
#include "mw_types.h"

/* NAMING CONSTANT DECLARATIONS
 */
#define MW_MSG_ID_COMMON_HEADER \
    UI8_T msg_id;

#define MW_MSG_ID_REQ_COMMON_HEADER \
    MW_MSG_ID_COMMON_HEADER

#define MW_MSG_ID_RSP_COMMON_HEADER \
    MW_MSG_ID_COMMON_HEADER \
    UI8_T result;    /* MW_ERROR_NO_T */

#define MW_MSG_ID_NOTI_COMMON_HEADER \
    MW_MSG_ID_COMMON_HEADER

#define MW_MSG_ID_SELF_DEFINED_BASE (MW_MSG_ID_WELL_KNOWN_LAST + 1)

typedef enum
{
    MW_MSG_ID_WELL_KNOWN_BASE = 0,
    MW_MSG_ID_ETHERNET_PBUF = MW_MSG_ID_WELL_KNOWN_BASE,
    MW_MSG_ID_DB,

    /* Define well known message IDs above this line. */
    MW_MSG_ID_WELL_KNOWN_LAST = 63
} MW_MSG_ID_WELL_KNOWN_T;

/* MACRO FUNCTION DECLARATIONS
 */

/* DATA TYPE DECLARATIONS
 */
typedef struct
{
    MW_MSG_ID_COMMON_HEADER
    UI8_T msg_data[0];
} __attribute__((packed)) MW_MSG_T;
/* GLOBAL VARIABLE DECLARATIONS
*/

/* EXPORTED SUBPROGRAM SPECIFICATIONS
 */
#endif /* MW_MSG_H */

