export
CONFIG_PLATFORM=en8851
#
# EN8851 features
#
ifeq ($(AIR_SUPPORT_ACE),1)
CONFIG_ACE=y
CONFIG_PDMA=y
CONFIG_PDMA_COMMON=y
CONFIG_ETHERNETIF=y
CONFIG_PBUF=y
CONFIG_GPHY_EN8851=y
ifeq ($(AIR_SUPPORT_ACE_ETHERNET_LOG),1)
CONFIG_ACE_CMD_DEBUG=y
endif
endif
CONFIG_NDS32=y
CONFIG_GPIO=y
CONFIG_GPIO_COMMON=y
CONFIG_I2C=y
CONFIG_I2C_COMMON=y
CONFIG_SLED=y
CONFIG_SLED_EN8851=y
CONFIG_SPI=y
CONFIG_SPI_COMMON=y
CONFIG_TIMER=y
CONFIG_TIMER_COMMON=y
CONFIG_UART=y
CONFIG_UART_COMMON=y
#CONFIG_GPHY_AN8855 is not set
# end of EN8851 features