obj-$(CONFIG_CMD_SHELL) += cmd_func.o
obj-$(CONFIG_CMD_SHELL) += cmd_interpreter.o
obj-$(CONFIG_CMD_SHELL) += cmd_peripheral.o
obj-$(CONFIG_CMD_SHELL) += cmd_shell.o
obj-$(CONFIG_CMD_SHELL) += xmodem.o
obj-$(CONFIG_CMD_SHELL) += tftp_client.o
obj-$(CONFIG_DRIVER_GPIO) += gpio_cmd.o
obj-$(CONFIG_DRIVER_CHIPSCU) += chipscu_cmd.o
obj-$(CONFIG_DRIVER_I2C) += i2c_cmd.o

