/*******************************************************************************
 *  Copyright Statement:
 *  --------------------
 *  This software is protected by Copyright and the information contained
 *  herein is confidential. The software may not be copied and the information
 *  contained herein may not be used or disclosed except with the written
 *  permission of Airoha Technology Corp. (C) 2021
 *
 *  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 *  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("AIROHA SOFTWARE")
 *  RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
 *  AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 *  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 *  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 *  NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 *  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 *  SUPPLIED WITH THE AIROHA SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
 *  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. AIROHA SHALL ALSO
 *  NOT BE RESPONSIBLE FOR ANY AIROHA SOFTWARE RELEASES MADE TO BUYER'S
 *  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
 *
 *  BUYER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND CUMULATIVE
 *  LIABILITY WITH RESPECT TO THE AIROHA SOFTWARE RELEASED HEREUNDER WILL BE,
 *  AT AIROHA'S OPTION, TO REVISE OR REPLACE THE AIROHA SOFTWARE AT ISSUE,
 *  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
 *  AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
 *
 *  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
 *  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
 *  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
 *  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
 *  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
 *
 *******************************************************************************/

/* FILE NAME:  hal_dev.h
 * PURPOSE:
 *  Provide a list of device IDs.
 *
 * NOTES:
 */

#ifndef HAL_DEV_H
#define HAL_DEV_H

/* INCLUDE FILE DECLARATIONS
 */
/* NAMING CONSTANT DECLARATIONS
 */
#define HAL_CHIP_FAMILY_ID_SCO   (0x8851)
#define HAL_CHIP_FAMILY_ID_PEARL (0x8855)
#define HAL_CHIP_FAMILY_ID_CORAL (0x8856)

#define HAL_SCO_DEVICE_ID_EN8851C (1)
#define HAL_SCO_DEVICE_ID_EN8851E (2)
#define HAL_SCO_DEVICE_ID_EN8853C (4)
#define HAL_SCO_DEVICE_ID_EN8860C (6)

#define HAL_SCO_REVISION_ID_E1 (0)
#define HAL_SCO_REVISION_ID_E2 (1)

#define HAL_PEARL_DEVICE_ID_AN8855M (4)
#define HAL_PEARL_DEVICE_ID_AN8855H (2)
#define HAL_PEARL_REVISION_ID_E1    (0)

#define HAL_CORAL_DEVICE_ID_AN8858E (2)
#define HAL_CORAL_DEVICE_ID_AN8858C (6)
#define HAL_CORAL_DEVICE_ID_AN8858H (10)
#define HAL_CORAL_DEVICE_ID_AN8858B (14)
#define HAL_CORAL_DEVICE_ID_AN8858F (1)
#define HAL_CORAL_DEVICE_ID_AN8858D (5)

#define HAL_CORAL_REVISION_ID_E1 (0)
#define HAL_INVALID_DEVICE_ID    (0xFFFFFFFF)

#define HAL_POE_DEVICE_ID_IP804AR (0x000004A2)
#define HAL_POE_DEVICE_ID_IP808AR (0x0000808A)
#define HAL_POE_DEVICE_ID_AN8502  (0x000004B0)
#define HAL_POE_DEVICE_ID_AN8503  (0x00008503)

#endif /* #ifndef HAL_DEV_H */
