#ifndef AIR_RTOS_CONFIG_H
#define AIR_RTOS_CONFIG_H

#if defined(FREERTOS_CONFIG_FILE)
#include FREERTOS_CONFIG_FILE
#endif

#define configTICK_RATE_HZ						( ( TickType_t ) 1000 )

#define configUSE_PREEMPTION					1
#ifndef configMAX_PRIORITIES
#define configMAX_PRIORITIES                    ( 8 )
#endif
#ifndef rtosMAX_PRIORITIES
#define rtosMAX_PRIORITIES                      ( configMAX_PRIORITIES - 1 )
#endif
#define configMINIMAL_STACK_SIZE				( 202 )
#define configMAX_TASK_NAME_LEN					( 16 )
#define configUSE_16_BIT_TICKS					0
#define configIDLE_SHOULD_YIELD					1
#define configUSE_TASK_NOTIFICATIONS			1
#define configUSE_MUTEXES						1
#define configUSE_RECURSIVE_MUTEXES				1
#define configUSE_COUNTING_SEMAPHORES			1
#define configQUEUE_REGISTRY_SIZE				10
#define configUSE_QUEUE_SETS					1


/* Memory allocation definitions. */
#define configSUPPORT_STATIC_ALLOCATION			1
#define configSUPPORT_DYNAMIC_ALLOCATION		1

#ifndef __ASSEMBLER__
#include <stdint.h>
extern uint32_t ucHeap_size(void);
#define configTOTAL_HEAP_SIZE ucHeap_size()
#endif

/* Hook function definitions. */
#define configUSE_IDLE_HOOK						1
#define configUSE_TICK_HOOK						1
#define configCHECK_FOR_STACK_OVERFLOW			2
#define configUSE_MALLOC_FAILED_HOOK			1
#define configUSE_DAEMON_TASK_STARTUP_HOOK		0

/* Run time and task stats gathering definitions. */
#define configGENERATE_RUN_TIME_STATS			1
#define configUSE_TRACE_FACILITY    			1		// Awareness debugging used
#define configUSE_STATS_FORMATTING_FUNCTIONS	1

/* Co-routine definitions. */
#define configUSE_CO_ROUTINES 					0
#define configMAX_CO_ROUTINE_PRIORITIES         ( 2 )

/* Software timer definitions. */
#define configUSE_TIMERS						1
#define configTIMER_TASK_PRIORITY				( rtosMAX_PRIORITIES - 1 )
#define configTIMER_QUEUE_LENGTH				8
#define configTIMER_TASK_STACK_DEPTH			( configMINIMAL_STACK_SIZE * 2 )

/* Set the following definitions to 1 to include the API function, or zero
to exclude the API function. */
#define INCLUDE_vTaskPrioritySet				1
#define INCLUDE_uxTaskPriorityGet				1
#define INCLUDE_vTaskDelete						1
#define INCLUDE_vTaskCleanUpResources			1
#define INCLUDE_vTaskSuspend					1
#define INCLUDE_vTaskDelayUntil					1
#define INCLUDE_vTaskDelay						1
#define INCLUDE_xTaskGetCurrentTaskHandle		1
#define INCLUDE_xTimerPendFunctionCall			1
#define INCLUDE_eTaskGetState					1
#define INCLUDE_xTaskAbortDelay					1
#define INCLUDE_xTaskGetHandle					1
#define INCLUDE_xSemaphoreGetMutexHolder		1

/* The size of the global output buffer that is available for use when there
are multiple command interpreters running at once (for example, one on a UART
and one on TCP/IP).  This is done to prevent an output buffer being defined by
each implementation - which would waste RAM.  In this case, there is only one
command interpreter running. */
/* The buffer into which output generated by FreeRTOS+CLI is placed.  This must
be at least big enough to contain the output of the task-stats command, as the
example implementation does not include buffer overlow checking. */
#define configCOMMAND_INT_MAX_OUTPUT_SIZE		2096
#define configINCLUDE_QUERY_HEAP_COMMAND		1

/* This file is included from assembler files - make sure C code is not included
in assembler files. */
#ifndef __ASSEMBLER__
	void vAssertCalled( const char * pcFile, unsigned long ulLine );

	void vConfigureTickInterrupt( void );
	void vClearTickInterrupt( void );
	void vEnableTickInterrupt( long xEnable );
	void vSetTickReload( uint32_t ulReload );
    void vUpdateTickReload( void );
	uint32_t ulGetTickCounter( void );

	void vPreSleepProcessing( unsigned long uxExpectedIdleTime );
	void vPostSleepProcessing( unsigned long uxExpectedIdleTime );
#endif /* __ASSEMBLER__ */



/* Normal assert() semantics without relying on the provision of an assert.h
header file. */
#define configASSERT( x ) if( ( x ) == 0 ) vAssertCalled( __FILE__, __LINE__ );



/****** Hardware/compiler specific settings. *******************************************/

/*
 * Support zero-overhead loop mechanism or not.
 * If configSUPPORT_ZOL is set to 1 then tasks can optionally have a ZOL system
 * registers context (the ZOL system registers will be saved as part of the task
 * context).
 *
 * If configSUPPORT_ZOL is set to 0 then ZOL system registers must never be used.
 */
#define configSUPPORT_ZOL                       0

/*
 * The application must provide a function that configures a peripheral to
 * create the FreeRTOS tick interrupt, then define configSETUP_TICK_INTERRUPT()
 * in FreeRTOSConfig.h to call the function.  This file contains a function
 * that is suitable for use on the Andes AE210P.  FreeRTOS_Tick_Handler() must
 * be installed as the peripheral's interrupt handler.
 */
#define configSETUP_TICK_INTERRUPT()     vConfigureTickInterrupt()
#define configCLEAR_TICK_INTERRUPT()     vClearTickInterrupt()
#define configENABLE_TICK_INTERRUPT( x ) vEnableTickInterrupt( x )
#define configSET_TICK_RELOAD( x )       vSetTickReload( x )
#define configUPDATE_TICK_RELOAD( x )    vUpdateTickReload()
#define configGET_TICK_COUNTER()         ulGetTickCounter()

/* The configPRE_SLEEP_PROCESSING() and configPOST_SLEEP_PROCESSING() macros
allow the application writer to add additional code before and after the MCU is
placed into the low power state respectively.  The empty implementations
provided in this demo can be extended to save even more power. */
#define configPRE_SLEEP_PROCESSING( uxExpectedIdleTime ) vPreSleepProcessing( uxExpectedIdleTime );
#define configPOST_SLEEP_PROCESSING( uxExpectedIdleTime ) vPostSleepProcessing( uxExpectedIdleTime );

/* Compiler specifics. */
#define fabs( x ) __builtin_fabs( x )

/* Enable Hardware Stack Protection and Recording mechanism. */
#define configHSP_ENABLE			0

/* Record the highest address of stack. */
#if (configHSP_ENABLE == 1 && configRECORD_STACK_HIGH_ADDRESS != 1 )
#define configRECORD_STACK_HIGH_ADDRESS		1
#endif

#define configMAC_ISR_SIMULATOR_PRIORITY    ( rtosMAX_PRIORITIES - 1 )
#define configLWIP_TASK_PRIORITY            ( rtosMAX_PRIORITIES - 2 )

#define portCONFIGURE_TIMER_FOR_RUN_TIME_STATS() vConfigureTimerForRunTimeStats()
#define portGET_RUN_TIME_COUNTER_VALUE() ulGetRunTimeCounterValue()

#endif