/*
 * Copyright (C) Airoha.Inc 2024
 * This file is auto generated by pinctrl tool
 *
 * Source file is an8856_pindef_0723.csv
 */
#include <stdint.h>
#include <pinctrl.h>
#include <util.h>
#include <string.h>
#include <stdio.h>

/*
 * register definition
 */

#define PINCTRL_REG_BASE            (0x10006000UL)
#define PINCTRL_REG_MODE            (PINCTRL_REG_BASE + 0x00UL)
#define PINCTRL_REG_MODE1           (PINCTRL_REG_BASE + 0x04UL)
#define PINCTRL_REG_MODE2           (PINCTRL_REG_BASE + 0x08UL)
#define PINCTRL_REG_HWTRAP_BYPASS   (PINCTRL_REG_BASE + 0x10UL)

#define PINCTRL_PER_REG             (8)
#define PINCTRL_PER_PIN_BIT         (32 / PINCTRL_PER_REG)

#define mask(n)                     (~(~0 << (n)))

#define COLOR_RED                   "\033[0;31m"
#define COLOR_YELLOW                "\033[0;33m"
#define COLOR_CYAN                  "\033[0;36m"
#define COLOR_WHITE                 "\033[0;37m"

#define INIT_MSG                    COLOR_YELLOW "[INIT ]" COLOR_WHITE
#define DEBUG_MSG                   COLOR_CYAN "[DEBUG]" COLOR_WHITE
#define ERROR_MSG                   COLOR_RED "[ERROR]" COLOR_WHITE

#define pr_init(s, ...)             printf(INIT_MSG s, ##__VA_ARGS__)
#define pr_info(s, ...)             printf(DEBUG_MSG s, ##__VA_ARGS__)
#define pr_err(s, ...)              printf(ERROR_MSG s, ##__VA_ARGS__)


static void io_writeMask(unsigned int addr, unsigned int data, unsigned int mask)
{
    io_write32(addr, (io_read32(addr) & ~(mask)) | (data & mask));
}
/*
 * pin definition
 */
static const unsigned char pindef[AIR_PIN_COUNT][AIR_FUNC_COUNT] = {
    /* pin 0 */
    {
        AIR_PINCTRL_GPIO,
        AIR_PINCTRL_SLED_SCLK,
        AIR_PINCTRL_LED_SCTRL_SGPIO_CLK,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_LED_A,
        AIR_PINCTRL_LED_SCTRL_SGPO,
        AIR_PINCTRL_CHIP_PROBE,
    },
    /* pin 1 */
    {
        AIR_PINCTRL_GPIO,
        AIR_PINCTRL_SLED_SDAT,
        AIR_PINCTRL_LED_SCTRL_SGPIO_DATA,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_LED_B,
        AIR_PINCTRL_LED_SCTRL_SGPO,
        AIR_PINCTRL_CHIP_PROBE,
    },
    /* pin 2 */
    {
        AIR_PINCTRL_GPIO,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_LED_SCTRL_SGPIO_RCLK,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_LED_C,
        AIR_PINCTRL_LED_SCTRL_SGPO,
        AIR_PINCTRL_CHIP_PROBE,
    },
    /* pin 3 */
    {
        AIR_PINCTRL_GPIO,
        AIR_PINCTRL_SGPIO_CLK,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_INTER_IRQ,
        AIR_PINCTRL_EXT_IRQ0,
        AIR_PINCTRL_EXT_IRQ1,
        AIR_PINCTRL_EXT_IRQ2,
        AIR_PINCTRL_LED_D,
        AIR_PINCTRL_LED_SCTRL_SGPO,
        AIR_PINCTRL_CHIP_PROBE,
    },
    /* pin 4 */
    {
        AIR_PINCTRL_GPIO,
        AIR_PINCTRL_SGPIO_DATA,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_INTER_IRQ,
        AIR_PINCTRL_EXT_IRQ0,
        AIR_PINCTRL_EXT_IRQ1,
        AIR_PINCTRL_EXT_IRQ2,
        AIR_PINCTRL_LED_E,
        AIR_PINCTRL_LED_SCTRL_SGPO,
        AIR_PINCTRL_CHIP_PROBE,
    },
    /* pin 5 */
    {
        AIR_PINCTRL_GPIO,
        AIR_PINCTRL_SGPIO_RCLK,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_CPU_JTAG_TRST,
        AIR_PINCTRL_LED_MCU_JTAG_TRST,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_LED_F,
        AIR_PINCTRL_LED_SCTRL_SGPO,
        AIR_PINCTRL_NAN,
    },
    /* pin 6 */
    {
        AIR_PINCTRL_GPIO,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_CPU_JTAG_SRSTN,
        AIR_PINCTRL_LED_MCU_JTAG_SRSTN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_LED_G,
        AIR_PINCTRL_LED_SCTRL_SGPO,
        AIR_PINCTRL_NAN,
    },
    /* pin 7 */
    {
        AIR_PINCTRL_GPIO,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_CPU_JTAG_TCK,
        AIR_PINCTRL_LED_MCU_JTAG_TCK,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_LED_H,
        AIR_PINCTRL_LED_SCTRL_SGPO,
        AIR_PINCTRL_NAN,
    },
    /* pin 8 */
    {
        AIR_PINCTRL_GPIO,
        AIR_PINCTRL_MDIO_MST_MDC,
        AIR_PINCTRL_MDC,
        AIR_PINCTRL_I2C_SCLK,
        AIR_PINCTRL_I2C2RBUS_SCL,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_INTER_IRQ,
        AIR_PINCTRL_EXT_IRQ0,
        AIR_PINCTRL_EXT_IRQ1,
        AIR_PINCTRL_EXT_IRQ2,
        AIR_PINCTRL_LED_I,
        AIR_PINCTRL_LED_SCTRL_SGPO,
        AIR_PINCTRL_PXP_SFP_RX_LOS,
    },
    /* pin 9 */
    {
        AIR_PINCTRL_GPIO,
        AIR_PINCTRL_MDIO_MST_MDIO,
        AIR_PINCTRL_MDIO,
        AIR_PINCTRL_I2C_SD,
        AIR_PINCTRL_I2C2RBUS_SD,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_INTER_IRQ,
        AIR_PINCTRL_EXT_IRQ0,
        AIR_PINCTRL_EXT_IRQ1,
        AIR_PINCTRL_EXT_IRQ2,
        AIR_PINCTRL_LED_J,
        AIR_PINCTRL_LED_SCTRL_SGPO,
        AIR_PINCTRL_PXP_SFP_RX_LOS,
    },
    /* pin 10 */
    {
        AIR_PINCTRL_GPIO,
        AIR_PINCTRL_UART_TXD,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_EXT_SPI_HOLD_B,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_INTER_IRQ,
        AIR_PINCTRL_EXT_IRQ0,
        AIR_PINCTRL_EXT_IRQ1,
        AIR_PINCTRL_EXT_IRQ2,
        AIR_PINCTRL_LED_K,
        AIR_PINCTRL_LED_SCTRL_SGPO,
        AIR_PINCTRL_NAN,
    },
    /* pin 11 */
    {
        AIR_PINCTRL_GPIO,
        AIR_PINCTRL_UART_RXD,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_EXT_SPI_WP_B,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_INTER_IRQ,
        AIR_PINCTRL_EXT_IRQ0,
        AIR_PINCTRL_EXT_IRQ1,
        AIR_PINCTRL_EXT_IRQ2,
        AIR_PINCTRL_LED_L,
        AIR_PINCTRL_LED_SCTRL_SGPO,
        AIR_PINCTRL_PXP_SFP_RX_LOS,
    },
    /* pin 12 */
    {
        AIR_PINCTRL_GPIO,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_EXT_SPI_CLK,
        AIR_PINCTRL_SHIFTMUX_SPI_CLK,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_INTER_IRQ,
        AIR_PINCTRL_EXT_IRQ0,
        AIR_PINCTRL_EXT_IRQ1,
        AIR_PINCTRL_EXT_IRQ2,
        AIR_PINCTRL_LED_M,
        AIR_PINCTRL_LED_SCTRL_SGPO,
        AIR_PINCTRL_CHIP_PROBE,
    },
    /* pin 13 */
    {
        AIR_PINCTRL_GPIO,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_EXT_SPI_MOSI,
        AIR_PINCTRL_SHIFTMUX_SPI_MOSI,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_INTER_IRQ,
        AIR_PINCTRL_EXT_IRQ0,
        AIR_PINCTRL_EXT_IRQ1,
        AIR_PINCTRL_EXT_IRQ2,
        AIR_PINCTRL_LED_N,
        AIR_PINCTRL_LED_SCTRL_SGPO,
        AIR_PINCTRL_CHIP_PROBE,
    },
    /* pin 14 */
    {
        AIR_PINCTRL_GPIO,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_EXT_SPI_MISO,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_INTER_IRQ,
        AIR_PINCTRL_EXT_IRQ0,
        AIR_PINCTRL_EXT_IRQ1,
        AIR_PINCTRL_EXT_IRQ2,
        AIR_PINCTRL_LED,
        AIR_PINCTRL_LED_SCTRL_SGPO,
        AIR_PINCTRL_CHIP_PROBE,
    },
    /* pin 15 */
    {
        AIR_PINCTRL_GPIO,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_EXT_SPI_CSB,
        AIR_PINCTRL_SHIFTMUX_SPI_CSN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_INTER_IRQ,
        AIR_PINCTRL_EXT_IRQ0,
        AIR_PINCTRL_EXT_IRQ1,
        AIR_PINCTRL_EXT_IRQ2,
        AIR_PINCTRL_LED_P,
        AIR_PINCTRL_LED_SCTRL_SGPO,
        AIR_PINCTRL_NAN,
    },
    /* pin 16 */
    {
        AIR_PINCTRL_GPIO,
        AIR_PINCTRL_TOD_1PPS_IN,
        AIR_PINCTRL_TOD_1PPS_OUT,
        AIR_PINCTRL_SYNC_E_CLK_A,
        AIR_PINCTRL_CPU_JTAG_TDI,
        AIR_PINCTRL_LED_MCU_JTAG_TDI,
        AIR_PINCTRL_INTER_IRQ,
        AIR_PINCTRL_EXT_IRQ0,
        AIR_PINCTRL_EXT_IRQ1,
        AIR_PINCTRL_EXT_IRQ2,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_LED_SCTRL_SGPO,
        AIR_PINCTRL_PXP_SFP_RX_LOS,
    },
    /* pin 17 */
    {
        AIR_PINCTRL_GPIO,
        AIR_PINCTRL_TOD_1PPS_IN_GM,
        AIR_PINCTRL_TOD_1PPS_OUT,
        AIR_PINCTRL_SYNC_E_CLK_B,
        AIR_PINCTRL_CPU_JTAG_TMS,
        AIR_PINCTRL_LED_MCU_JTAG_TMS,
        AIR_PINCTRL_INTER_IRQ,
        AIR_PINCTRL_EXT_IRQ0,
        AIR_PINCTRL_EXT_IRQ1,
        AIR_PINCTRL_EXT_IRQ2,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_LED_SCTRL_SGPO,
        AIR_PINCTRL_PXP_SFP_RX_LOS,
    },
    /* pin 18 */
    {
        AIR_PINCTRL_GPIO,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_LED_SCTRL_LED_SYNC,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_CPU_JTAG_TDO,
        AIR_PINCTRL_LED_MCU_JTAG_TDO,
        AIR_PINCTRL_INTER_IRQ,
        AIR_PINCTRL_EXT_IRQ0,
        AIR_PINCTRL_EXT_IRQ1,
        AIR_PINCTRL_EXT_IRQ2,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_LED_SCTRL_SGPO,
        AIR_PINCTRL_PXP_SFP_RX_LOS,
    },
    /* pin 19 */
    {
        AIR_PINCTRL_GPIO,
        AIR_PINCTRL_MDIO_MST_MDC,
        AIR_PINCTRL_MDC,
        AIR_PINCTRL_I2C_SCLK,
        AIR_PINCTRL_I2C2RBUS_SCL,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_LED_SCTRL_SGPO,
        AIR_PINCTRL_NAN,
    },
    /* pin 20 */
    {
        AIR_PINCTRL_GPIO,
        AIR_PINCTRL_MDIO_MST_MDIO,
        AIR_PINCTRL_MDIO,
        AIR_PINCTRL_I2C_SD,
        AIR_PINCTRL_I2C2RBUS_SD,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_NAN,
        AIR_PINCTRL_LED_SCTRL_SGPO,
        AIR_PINCTRL_NAN,
    },
};

static int pintctrl_checkPinAndFunc(int pin, int func) {
    return !(pin < AIR_PIN_COUNT && func < AIR_FUNC_COUNT && pindef[pin][func] != AIR_PINCTRL_NAN);
}

static unsigned int pinctrl_getAddr(int pin) {
    unsigned int offset = (pin / PINCTRL_PER_REG) * PINCTRL_PER_PIN_BIT;
    unsigned int addr = offset + (unsigned int)PINCTRL_REG_BASE;

    return addr;
}

/**
 * @brief Deinitialize pin control.
 */
void pinctrl_deinit(void) {
    io_write32(PINCTRL_REG_MODE, 0);
    io_write32(PINCTRL_REG_MODE1, 0);
    io_write32(PINCTRL_REG_MODE2, 0);
    // io_write32(PINCTRL_REG_HWTRAP_BYPASS, 0);
}

/**
 * @brief Request a pin to be set to a specific function.
 * @param pin The pin number to be set.
 * @param func The function to set the pin to.
 * @param flag ignore the hardware trap or not
 * @return the result of pinctrl_request
 *         0 as execute successful
 *         other as error
 */
int pinctrl_request(int pin, int func) {

    unsigned int addr, index;

    /* check the pin and function are available */
    if(pintctrl_checkPinAndFunc(pin, func)) {
        pr_err("Pin %d or func %d do not exist!\n", pin, func);
        return -1;
    }

    addr = pinctrl_getAddr(pin);
    index = pin % PINCTRL_PER_REG;

    io_writeMask(addr, func << index * PINCTRL_PER_PIN_BIT, mask(4) << index * PINCTRL_PER_PIN_BIT);

    return 0;
}

/**
 * @brief Free a pin, setting its function code to 0.
 * @param pin The pin number to be freed.
 */
int pinctrl_free(int pin) {

    int result = 0;

    result = pinctrl_request(pin, 0);
    if(result) {
        pr_err("pin request failed\n");
    }

    return result;
}

/**
 * @brief Get the function of a specific pin.
 * @param pin The pin number to query.
 * @return The function code of the pin and the pin status
 *         hardware trap or iomux
 */
int pinctrl_getFunc(int pin) {

    unsigned int addr, index, func;

    if(pintctrl_checkPinAndFunc(pin, 0)) {
        return -1;
    }

    addr = pinctrl_getAddr(pin);
    index = pin % PINCTRL_PER_REG;

    func = (io_read32(addr) >> index * PINCTRL_PER_PIN_BIT) & mask(4);

    return func;
}

