/*******************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of Airoha Technology Corp. (C) 2023
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("AIROHA SOFTWARE")
*  RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE AIROHA SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. AIROHA SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY AIROHA SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE AIROHA SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT AIROHA'S OPTION, TO REVISE OR REPLACE THE AIROHA SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*******************************************************************************/

/* FILE NAME:  syncd_msg.h
 * PURPOSE:
 *      Define the Message IDs sent to SYNCD task.
 *
 * NOTES:
 */

#ifndef _SYNCD_MSG_H_
#define _SYNCD_MSG_H_

/* INCLUDE FILE DECLARATIONS
 */
#include "mw_msg.h"

/* NAMING CONSTANT DECLARATIONS
*/
typedef enum
{
    /* Naming format: MW_MSG_ID_[module]_[sender]_[request/response/event]_[REQ/RSP/NOTI] */
    MW_MSG_ID_SYNCD_TIMER_BASE_TIMER_EXPIRED_NOTI = MW_MSG_ID_SELF_DEFINED_BASE,
    MW_MSG_ID_SYNCD_TIMER_MIB_COUNTER_TIMER_EXPIRED_NOTI,
#ifdef SYNCD_TEST_ENABLE
    MW_MSG_ID_SYNCD_SYNCD_TEST_REQ,
#endif

    MW_MSG_ID_SYNCD_LAST
} SYNCD_MSG_ID_T;

/* MACRO FUNCTION DECLARATIONS
*/

/* DATA TYPE DECLARATIONS
*/
typedef struct
{
    MW_MSG_ID_COMMON_HEADER
} SYNCD_MSG_BASE_TIMER_T;

#ifdef SYNCD_TEST_ENABLE
typedef struct
{
    MW_MSG_ID_REQ_COMMON_HEADER
    UI8_T solo;
} SYNCD_MSG_TEST_REQ_T;
#endif
/* EXPORTED SUBPROGRAM SPECIFICATIONS
 */

#endif  /*_SYNCD_MSG_H_*/

