include $(AIR_MW_SYSTEM)/make/make_prologue.mk

dir = $(d)/common-lib
include $(dir)/Makefile

dir = $(d)/rate-limit
include $(dir)/Makefile

dir = $(d)/sif
include $(dir)/Makefile

dir = $(d)/log
include $(dir)/Makefile

include $(AIR_MW_SYSTEM)/make/make_epilogue.mk