MW_CFLAGS  = -DMW_VER_STR=\"$(MW_SYS_VER)\"

ifeq ($(findstring ENABLED, $(AIR_LITE_MW)), ENABLED)
MW_CFLAGS += -DAIR_LITE_MW
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_IGMP_SNP)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_IGMP_SNP
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_IGMPV3_AWARE)), ENABLED)
ifneq ($(findstring ENABLED, $(AIR_SUPPORT_IGMP_SNP)), ENABLED)
$(error AIR_SUPPORT_IGMPV3_AWARE shall be Enabled with AIR_SUPPORT_IGMP_SNP!)
endif
MW_CFLAGS += -DAIR_SUPPORT_IGMPV3_AWARE
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_PIM_AWARE)), ENABLED)
ifneq ($(findstring ENABLED, $(AIR_SUPPORT_IGMP_SNP)), ENABLED)
$(error AIR_SUPPORT_PIM_AWARE shall be Enabled with AIR_SUPPORT_IGMP_SNP!)
endif
MW_CFLAGS += -DAIR_SUPPORT_PIM_AWARE
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_IGMP_SNP_SEARCH_MAC_TABLE)), ENABLED)
ifneq ($(findstring ENABLED, $(AIR_SUPPORT_IGMP_SNP)), ENABLED)
$(error AIR_SUPPORT_IGMP_SNP_SEARCH_MAC_TABLE shall be Enabled with AIR_SUPPORT_IGMP_SNP!)
endif
MW_CFLAGS += -DAIR_SUPPORT_IGMP_SNP_SEARCH_MAC_TABLE
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_IGMP_SNP_QUERIER)), ENABLED)
ifneq ($(findstring ENABLED, $(AIR_SUPPORT_IGMP_SNP)), ENABLED)
$(error AIR_SUPPORT_IGMP_SNP_QUERIER shall be Enabled with AIR_SUPPORT_IGMP_SNP!)
endif
MW_CFLAGS += -DAIR_SUPPORT_IGMP_SNP_QUERIER
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_IGMP_SNP_QUERIER_IGMPV3)), ENABLED)
ifneq ($(findstring ENABLED, $(AIR_SUPPORT_IGMP_SNP_QUERIER)), ENABLED)
$(error AIR_SUPPORT_IGMP_SNP_QUERIER_IGMPV3 shall be Enabled with AIR_SUPPORT_IGMP_SNP_QUERIER!)
endif
MW_CFLAGS += -DAIR_SUPPORT_IGMP_SNP_QUERIER_IGMPV3
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_LP)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_LP
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_SNMP)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_SNMP
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_IPV6)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_IPV6
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_RSTP)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_RSTP
MW_CFLAGS += -DNDEBUG
MW_CFLAGS += -DLLC_SUPPORT
ifeq ($(findstring ENABLED, $(AIR_SUPPORT_RSTP_SECURITY)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_RSTP_SECURITY
endif
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_MSTP)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_MSTP
MW_CFLAGS += -DLLC_SUPPORT
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_CABLE_DIAG)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_CABLE_DIAG
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_LP_WITH_SOFTWARE)), ENABLED)
ifneq ($(findstring ENABLED, $(AIR_SUPPORT_LP)), ENABLED)
$(error AIR_SUPPORT_LP_WITH_SOFTWARE shall be Enabled with AIR_SUPPORT_LP!)
endif
MW_CFLAGS += -DAIR_SUPPORT_LP_WITH_SOFTWARE
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_DHCP_SNOOP)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_DHCP_SNOOP
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_ICMP_CLIENT)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_ICMP_CLIENT
endif
ifeq ($(findstring ENABLED, $(AIR_SUPPORT_VOICE_VLAN)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_VOICE_VLAN
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_SURVEILLANCE_VLAN)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_SURVEILLANCE_VLAN
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_VOVLAN_SECURITY)), ENABLED)
ifneq ($(findstring ENABLED, $(AIR_SUPPORT_VOICE_VLAN)), ENABLED)
$(error AIR_SUPPORT_VOVLAN_SECURITY shall be Enabled with AIR_SUPPORT_VOICE_VLAN!)
endif
MW_CFLAGS += -DAIR_SUPPORT_VOVLAN_SECURITY
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_MQTTD)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_MQTTD
ifeq ($(findstring ENABLED, $(AIR_SUPPORT_MQTTD_STARTONBOOT)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_MQTTD_STARTONBOOT
endif
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_LLDPD)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_LLDPD
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_SFP)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_SFP
ifeq ($(findstring ENABLED, $(AIR_SUPPORT_SFP_DDM)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_SFP_DDM
endif
ifeq ($(findstring ENABLED, $(AIR_SUPPORT_SFP_WITH_THREAD)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_SFP_WITH_THREAD
endif
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_POE)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_POE
ifeq ($(findstring ENABLED, $(AIR_SUPPORT_POE_WATCHDOG)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_POE_WATCHDOG
endif
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_ERPS)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_ERPS
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_SNTP)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_SNTP
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_LACP)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_LACP
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_SECOND_NETIF)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_SECOND_NETIF
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_MGMT_VLAN_CFG)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_MGMT_VLAN_CFG
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_LACP)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_LACP
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_HTTPD)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_HTTPD
ifeq ($(findstring ENABLED, $(AIR_SUPPORT_HTTPD_SECURE)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_HTTPD_SECURE
endif
endif

CONFIG_METHOD_STR := $(findstring ENABLED,$(AIR_SUPPORT_HTTPD))$(findstring ENABLED,$(AIR_SUPPORT_MQTTD))$(findstring ENABLED,$(AIR_SUPPORT_CLI))
ifneq ($(findstring ENABLEDENABLED,$(CONFIG_METHOD_STR)),)
MW_CFLAGS += -DAIR_SUPPORT_HTTPD_MUTEX
endif

MW_CFLAGS += -D'__FILENAME__=(strrchr(__FILE__, 47) ? (strrchr(__FILE__, 47) + 1) : __FILE__)'

ifneq ($(findstring FREERTOS_CONFIG_FILE, $(CFLAGS)), FREERTOS_CONFIG_FILE)
MW_CFLAGS += -DFREERTOS_CONFIG_FILE='"$(AIR_MW_DIR)/project/$(PROJECT)/customer/freertos/rtos_config.h"'
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_REMOTE_DEBUG)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_REMOTE_DEBUG
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_TELNET)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_TELNET
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_CLI)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_CLI
CONFIG_CMD_SHELL=n
endif

ifeq ($(findstring ENABLED, $(AIR_SUPPORT_SSH)), ENABLED)
MW_CFLAGS += -DAIR_SUPPORT_SSH
CONFIG_USE_SSH = y
endif

export MW_CFLAGS
